enactjs/sandstone

CHANGELOG.md, RangePicker/RangePicker.js
- Displayed value did not change when it became out of range(min or max has changed)
- Limited the label value to be in range
PLAT-127114
=> PLAT-127114: Fixed RangePicker label when value is out of range

samples/qa-a11y/src/views/ContextualPopupDecorator.js
qa-a11y sampler ContextualPopup doesn't open when another ContextualPopup opens
Made ContextualPopup open
PLAT-125063
=> PLAT-125063: ContextualPopup doesn't open when another ContextualPopup opens

CHANGELOG.md, useScroll/useEvent.js
In current status, voice intent is always exist. For this reason, guide message of voice control can be listen.
Check scrolling is possible and declare scroll intent dynamically.
N/A
PLAT-129000
N/A
=> PLAT-129000: Scroller: Activate voice intent when scrolling is possible

CHANGELOG.md, Input/Input.js
- The issue was discovered in the qa-sampler for a picker with add/remove items which contains an input, with default value 0 Click on the index input field. --> Input '0'. --> Index Button's inner text is still 'Index'
- Updated the computed value for ButtonLabel inside InputBase to take a value of `0` as a valid value
PLAT-127115
=> PLAT-127115: Fixed Input label when value is 0

samples/sampler/stories/qa/Scroller.js
The scrollbar for the second scroller was not focusable
Added focusableScrollbar to second scroller
PLAT-134499
=> PLAT-134499: Added focusableScrollbar to second scroller

CHANGELOG.md, WizardPanels/WizardPanels.js, samples/sampler/stories/qa/WizardPanels.js
Touch effect is shown at other button
Add key value to prevent reuse DOM in footer
PLAT-139620
=> PLAT-139620: WizardPanels: Fixed touch effect to not be shown at another button

samples/qa-a11y/src/views/ContextualPopupDecorator.js, samples/sampler/stories/qa/ContextualPopupDecorator.js
Added sampler to test layering order between ContextualPopup and tooltip
ENYO-6132
=> ENYO-6132: Sample to test layering order with ContextualPopup and tooltip

CHANGELOG.md, PopupTabLayout/PopupTabLayout.js, TabLayout/TabLayout.js, TabLayout/tests/TabLayout-specs.js
PopupTabLayout should collapse its tab only when a user enters a menu.
To notify a user enters a menu, added `TabLayoutContext` to handle `onTransition` from `PopupTabLayout.TabPanels`.
PLAT-132843
=> PLAT-132843: PopupTabLayout: Collapse Tab only when a user enters a menu

CHANGELOG.md, MediaPlayer/MediaSlider.module.less
In `VideoPlayer` as the video plays back, by pressing 5-way down to show mediaControls, then 5-way up to focus the mediaSlider, the knob is not shown alongside thumbnail
Added an opacity to knob when mediaSlider gets focused
PLAT-112207
=> PLAT-112207: Knob does not show on the Slider by the thumbnail with 5-way Down then 5-way Up immediately after

CHANGELOG.md, WizardPanels/WizardPanels.js, samples/sampler/stories/qa/WizardPanels.js
Touch effect is shown at another button in the footer of WizardPanels when navigating panels.
This issue was solved in https://github.com/enactjs/sandstone/pull/871.
This PR is for applying the patch to develop.
PLAT-140367
=> PLAT-140367: WizardPanels: Fix touch effect is shown at another button

CHANGELOG.md, Panels/Header.js, Panels/Header.module.less, Panels/Panel.js
back button on Header is shown always on 2022 UX 
* Cherry-pick
https://github.com/enactjs/sandstone/pull/782
https://github.com/enactjs/sandstone/pull/869
* Remove unused handler
* Remove animation
PLAT-132840
=> PLAT-132840: Show back button on Header

CHANGELOG.md, useScroll/Scrollbar.js, useScroll/Scrollbar.module.less, useScroll/ScrollbarTrack.js, useScroll/ScrollbarTrack.module.less, useScroll/useEvent.js, useScroll/useScroll.js
TV UX was changed to hide Scrollbar after N seconds.
Revert "PLAT-123585: Scroller: keep showing scroll thumb (#776)"
PLAT-132842
=> PLAT-132842: Hide Scrollbar after N secs

CHANGELOG.md, Input/Input.js, Input/Input.module.less, Input/tests/Input-specs.js, samples/qa-a11y/src/views/Input.js, samples/qa-a11y/src/views/InputField.js, samples/sampler/stories/default/Input.js, samples/sampler/stories/default/InputField.js, samples/sampler/stories/qa/common/Input_Common.js, tests/screenshot/apps/components/Input.js, tests/screenshot/apps/components/InputField.js
Add url type in Input and InputPopup
Added `url` to the list of acceptable values for `type` prop in Input and InputPopup
PLAT-140535
=> PLAT-140535: Add url type in Input

CHANGELOG.md, Heading/Heading.js, Panels/Header.js
In some tricky cases, by timing issue, the title of Panels.Header in FixedPopupPanel doesn't start marquee when the title is centered.
The reason why the marquee not starting is, when Header is centered and the `slotSize` updated, the Marquee itself thinks the props are not changed so it does not recalculate its metrics.
To be specific, when Header is centered, it calculates `slotSize` to give the size for `slotAfter` and `slotBefore` by `Measurable`. The title is in between `slotAfter` and `slotBefore` so if the size of the slots changed, the …
=> PLAT-141464: Fix Panels.Header to remeasure marquee metrics when `slotSize` changed

CHANGELOG.md, Input/Input.js, Input/Input.module.less, Input/Keypad.js, samples/qa-a11y/src/views/Input.js, samples/sampler/stories/default/Input.js, styles/variables.less, tests/screenshot/apps/components/Input.js
Need to add a back button in the Input
Migrate back button on Input patches from 2021 NMRM TV ("release/1.4.3-touch.x" branch)
PLAT-132839
=> PLAT-132839: Show back button on Input

CHANGELOG.md, TabLayout/TabLayout.js, tests/ui/specs/PopupTabLayout/PopupTabLayout-specs.js
When the back key pressed from the content which is the first panel, it should not close the popup but it should move the focus to tabs area.
Added `onKeyUp` handler to TabLayout and see if the target is from the content that is the first panel, move the spotlight to the tabs and call `stopPropagation` to not close the Popup.
PLAT-141390
=> PLAT-141390: Changed back key behavior on PopupTabLayout

Button/Button.js, Button/Button.module.less, CHANGELOG.md, WizardPanels/WizardPanels.js, internal/Panels/NavigationButton.js, internal/Panels/NavigationButton.module.less, styles/variables.less, tests/screenshot/apps/components/WizardPanels.js
GUI requires to show button labels separated from icon buttons.
Resize focus effects' size and update labels' text color on press to match latest designs.
PLAT-126939
=> PLAT-126939: Separate labels for navigation buttons in WizardPanels

CHANGELOG.md, FixedPopupPanels/FixedPopupPanels.js, PopupTabLayout/PopupTabLayout.js, TabLayout/TabLayout.js, samples/sampler/stories/default/PopupTabLayout.js, samples/sampler/stories/qa/FixedPopupPanels.js, samples/sampler/stories/qa/PopupTabLayout.js, tests/ui/specs/FixedPopupPanels/FixedPopupPanels-specs.js, tests/ui/specs/PopupTabLayout/PopupTabLayout-specs.js
Added new UX that navigating with left and right keys in PopupTablayout and FixedPopupPanels.
For right key navigation, the framework cannot support this feature so I added some example to the sampler
For left key navigation, added handles for the left key to the component and if it's the left-most spottable then it calls `onBack`.
Miscellaneous sampler bug also fixed.
[//]: # (Related issues, …
=> PLAT-132841: Navigating with left and right keys in PopupTabLayout and FixedPopupPanels

Scroller/useThemeScroller.js
Scroller focus moves wrong target when using "byEnter"
- Spotlight moved to scroller-body instaed of scroller-thumb via 5-way key.
After updating ref, update spotlight navigableFilter.
Changed `useEffect` to `useLayoutEffec` for safety. `useEffect` is sometime invoked too late.
PLAT-141375
=> PLAT-141375: Fix Scroller  initial focus filter when `focusableScrollbar = byEnter`

samples/sampler/src/ThemeEnvironment/ThemeEnvironment.js
The global knob setting stays even if the story changes.
The storybook offers object 'globals' in the decorator and story.
I added properties that need to be worked globally to the object.
(Referred link: https://storybook.js.org/docs/react/essentials/toolbars-and-globals#globals)
PLAT-123715
=> PLAT-123715: Sampler: Fix global knob setting resets when component changes

Input/Input.js
The error occurs when `value` prop of `Input` is 0 due to `split` function call for number type value.
The logic is to manipulate string value, so `toString` is added to handle it properly.
PLAT-142955
=> PLAT-142955: Fix error when `value` prop of `Input` is 0

tests/screenshot/apps/Sandstone-View.js, tests/screenshot/apps/components/FormCheckboxItem.js
There is screenshot test fail on Sansdstone release/2.0.0-beta.1 about focus
Set default input-type class for focus.
Fix wrong  TC on `FormCheckboxItem` (regression from https://github.com/enactjs/sandstone/pull/856)
PLAT-143413
=> PLAT-143413: [Screenshot test] Set default input-type class for focus

CHANGELOG.md, useScroll/useEvent.js, useScroll/useOverscrollEffect.js
For better UX, the default overscroll effect factor needs to be refined. From this PR, the default effect factor is 0.5 which is half of the maximum effect (1.0) and the maximum effect factor for flick input is still 1.0 as it shows bigger for the speed of flicking.
Change the default effect factor from 1 to 0.5 except for flick input.
PLAT-126935
=> PLAT-126935: Refined overscroll effect

Input/Input.js
Unit test fails due to missing default prop value
Add default value for Input component's `text` prop
=> Add default value for Input component's `text` prop

Input/InputField.js
Unintended paddings inside `InputField` are added accidentally after #907.
Removed unintended class names.
=> Removed unintended class names from `InputField`

CHANGELOG.md, Input/InputFieldSpotlightDecorator.js
The input tag within the InputField is double focused by the onMouseDown handler and clicking it.
So when the cursor is outside the field and focused by the onMouseDown handler, the text inside the field moves so that the cursor shows. And then, the mouse click is actually applied, the cursor seems to be jumped unexpectedly.
It needs to be fixed.
Prevent scroll while focusing when the mouse button is downed.
It might generate some side-effects, so should be tested with the screenshot test and existed TCs.
PLAT-110254
=> PLAT-110254: InputField: Fix cursor jumps unexpectedly when the cursor is at the end of the text and clicking the field

CHANGELOG.md, Picker/Picker.js, ThemeDecorator/ThemeDecorator.js, samples/qa-a11y/src/views/Picker.js, samples/sampler/stories/default/Picker.js, samples/sampler/stories/qa/Picker.js
We need to use Picker for irregular number list.
To support picker with number list properly (increase button position, accessibility) , we added  `reverse` and `type` props
I added a minor guard code on ThemeDecorator for side loading on webOS
PLAT-129853
=> PLAT-129853: Support number list in Picker

TabLayout/TabLayout.js, ThemeDecorator/ThemeDecorator.js
The current API to handle the last input type imported by callback prop for `SpotlightRootDecorator` and it will be better to be imported in a normal way.
Updated to import key APIs from the module, not through callback function prop.
Also, updated TabLayout to use the API without querying a specific node to get the type info.
PLAT-140745
=> PLAT-140745: Refine logic to handle the last input type

CHANGELOG.md, MediaPlayer/MediaControls.js
After applying React 17, the React synthetic event root was changed from document to React DOM tree "root".
-Enact/Sandstone changed the dispatcher's on/off to add the event handler to the root of the React DOM tree rather than the document accordingly.
- In the case of MediaControls' wheel event, the event target must be explicitly designated as document to operate normally. There is no problem when side-loads after doing `enact serve` or `enact pack`, but target designation is required on `isomorphic+snapshot` builds.
It added `document` to `on('wheel')` function in `MediaControls`.
[//]: # (How should …
=> PLAT-142531: MediaPlayer: cannot show media controls with wheel event

CHANGELOG.md, Popup/Popup.js, samples/sampler/stories/qa/FixedPopupPanels.js
The original issue happened in FixedPopupPanels. When FixedPopupPanels opened with `noAnimation` prop is `true`, the last focused element got focused instead of the first element which is the result of `noAnimation` prop is `false`.
The difference between the two cases came from `data-spotlight-container-disabled` attribute.
When `noAnimation` prop is `false`, Popup pauses spotlight and so the container of the popup turns to be disabled. But when it's `true`, there is no such step since the node will be destroyed after all.
Spotlight stores …
=> PLAT-127486: Fix Popup to have proper focus when opening with `noAnimation` is `true`

CHANGELOG.md, internal/Panels/useAutoFocus.js
Spotlight exits out of FixedPopupPanels when pressing 5-way after click
- Delegate the sequence of finding the target to the spotlight.
- Cause 
It is regression from https://github.com/enactjs/sandstone/pull/667
in the problem cases, the placeholder get focus and be disappeared.
If user press the arrow key afterwards, there is no last focus container information, because the focus was given by
`Spotlight.focus(element)` not `Spotlight.focus(container)`;
To save the last container information, focus target should be found by `Spotlight.focus(container)`
[//]: # …
=> PLAT-125057: Fix Spotlight exits out of FixedPopupPanels

CHANGELOG.md, useScroll/useEvent.js
In VirtualList > 'with extra items' qa-sampler Spotlight moves to wrong target with PageDown key. 
Change direction to find target in the content
`epsilon` is 1. so the" translated" and "native" code is equivalent.
So I cleaned the if condition.
PLAT-139778
=> PLAT-139778: Scroller: Fix Spotlight moves to wrong target with PageUp/Down key 

CHANGELOG.md, FixedPopupPanels/FixedPopupPanels.js, PopupTabLayout/PopupTabLayout.js, samples/sampler/stories/default/PopupTabLayout.js, samples/sampler/stories/qa/FixedPopupPanels.js, samples/sampler/stories/qa/PopupTabLayout.js
Disable left key handler to go to previous panel in `FixedPopupPanels` and `PopupTabLayout` in RTL locales
Use `I18nContextDecorator` to get `rtl` props in `FixedPopupPanels` and `PopupTabLayout` and disable left key handler 
PLAT-142878
=> PLAT-142878: Disable left and right keys navigation in FixedPopupPanels and PopupTabLayout when locale is RTL

CHANGELOG.md, Picker/Picker.js
The value of Picker marquees when adding or changing the title.
Marquee for Picker is under control by MarqueeController but the Heading which is used for title starts marquee on "render" so the value starts marquee on "render" also.
So I changed Heading's `marqueeOn` prop to `hover`.
PLAT-143663
=> PLAT-143663: Fixed Picker value to not marquee when changing title

ContextualPopupDecorator/ContextualPopupDecorator.js
Fix  `direction` prop bleed in `ContextualPopupDecorator`
Delete `direction` prop before passing it down as props to component
ENYO-6332
=> ENYO-6332: Fix direction prop bleed in ContextualPopupDecorator

CHANGELOG.md, Input/Input.js
InputField has to re-focused by app when "show password" checkbox is clicked in Input component
Add spotlightId to InputField
N/A
PLAT-140537
N/A
=> PLAT-140537: Add spotlightId in InputField to support VKB reopen

CHANGELOG.md, Input/Input.js, Input/NumberField.js, Input/tests/Input-specs.js, samples/sampler/stories/default/Input.js
When number field used as 'joined', submit button show by default.
But some case, app don't want show submit button and use custom button.
Add prop for hide submit button
N/A
PLAT-145596
N/A
=> PLAT-145596: Hide submit button in Input

CHANGELOG.md, useScroll/HoverToScroll.js, useScroll/useScroll.js
Elements on scroll edges don't get focus by hover when `hoverToScroll` is `true`.
The cause of this bug is that a DOM node to catch hovering blocks mouse events on elements.
This PR shows and hides the DOM node along with scroll status.
PLAT-145554
enactjs/enact/pull/2930
=> PLAT-145554: Fix to focus elements at scroll boundaries by hover when `hoverToScroll` is `true`

CHANGELOG.md, VirtualList/useEvent.js, VirtualList/useThemeVirtualList.js, useScroll/useEvent.js
- Sometimes, 5way down/up doesn't work.
- If the user wheels down and up repeatedly, the focused effect stays at some items.
- Sometimes, scrolls to jump by 5way without animation.
- Sometimes, 5way down/up doesn't work. : Reset internal flag that is critical to 5way behavior.
- If the user wheels down and up repeatedly, the focused effect stays at some items. : Added and cleared logic related scaled effect
- Sometimes, scrolls to jump by 5way without animation. : Always on `animateOnFocus` option when `snapToCenter` …
=> PLAT-145128: Fix VirtualList snapToCenter issues

CHANGELOG.md, WizardPanels/Panel.js, WizardPanels/WizardPanels.js, samples/sampler/stories/qa/WizardPanels.js
WizardPanels: Items contained in the panel being removed are rendered twice
3 renderings are performed when the Wizard Panel is loaded.
- The 2nd render is called by useReverseTransition so I modified it to use Ref.
- The 3rd render is by `WizardPanels.Panel`, which is difficult to fix due to the current structure. The reported problem occurs in the 3rd render situation, because the key value is updated before the panel contents are updated.
So I fixed the key value is specified on `WizardPanels.Panel` instead of `WizardPanels`
[//]: # (Are there any outstanding …
=> PLAT-143483: Fixed Wizardpanel to not re-render the previous panel

CHANGELOG.md, VideoPlayer/VideoPlayer.js, samples/sampler/stories/qa/VideoPlayer.js
Fix `VideoPlayer` to handle playback rate with decimal point 
Use parseFloat instead of parseInt in `calcNumberValueOfPlaybackRate` func
PLAT-145625
=> PLAT-145625: Fix VideoPlayer to handle playback rate with decimal point

CHANGELOG.md, tests/ui/specs/VirtualList/VirtualGridList/With5-way/VirtualGridList-GT-28454-specs.js, tests/ui/specs/VirtualList/VirtualGridList/With5-way/VirtualGridList-GT-28584-specs.js, tests/ui/specs/VirtualList/VirtualGridList/qa-VirtualGridList/VirtualGridList-GT-28990-specs.js, tests/ui/specs/VirtualList/VirtualList/Samples/VirtualList-GT-32197-specs.js, useScroll/useEvent.js, useScroll/useScroll.js
Sandstone Touch: VirtualGridList> No animation when an item scrolls into a view
Set `animateOnFocus`=true by default. 
on the Moonstone, `animateOnFocus` was `undefined` by default. so scrollTo show animation by default.  
I fixed some ui-test to wait animation.
and Fix GT-28454-specs.js to avoid intermittent failed. (Sometimes spotlight right doesn't move the focus to inputMinHeight.)
PLAT-125066, WRN-929 …
=> WRN-929: Scroller: fix to show scroll animation when pressing 5-way key

CHANGELOG.md, ImageItem/ImageItem.js, tests/screenshot/apps/components/ImageItem.js, tests/screenshot/apps/components/ImageItem.module.less
It is already stated that it supports imageIcon css override.
CSS override for imageIcon class is not supported.
Added ImageItem publicClass `imageIcon`.
WRN-1539
=> WRN-1539: ImageItem: add `imageIcon` to publicClassNames

Checkbox/Checkbox.module.less, Icon/Icon.module.less, Switch/Switch.module.less, ThemeDecorator/ThemeDecorator.js, samples/qa-virtuallist/package.json, samples/qa-virtuallist/template.ejs, styles/skin.less
To see if we could change the skin runtime
To support runtime variable skin name, I've added `window.CUSTOM_SKIN` variable which can be injected from `custom_skin.js` file.
WRN-1582
=> WRN-1582: POC: Apply and load configure file

CHANGELOG.md, Slider/Slider.js, Slider/utils.js, samples/sampler/stories/default/Slider.js
Add `wheelInterval` props in Slider to prevent firing wheel event too frequently
Ignore wheel events occurred within `wheelInterval`(ms) of the last processed wheel event
WRN-1663
=> WRN-1663: Add wheelEventInterval in Slider to prevent firing wheel event too frequently

ActionGuide/tests/ActionGuide-specs.js, RadioItem/tests/RadioItem-specs.js
Migrated `ActionGuide` and `RadioItem` unit tests to react-testing-library
WRN-1351
=> WRN-1351: Migrate ActionGuide and RadioItem unit tests to Testing Library

CHANGELOG.md, Scroller/useThemeScroller.js, samples/sampler/stories/default/Panels.js
When enter to panel, Scroller body get focus 
This is a problem occurred because the containerId value was not updated even though the ref was updated. 
It was missing from (https://github.com/enactjs/sandstone/pull/900))
So I updated the containerId inside setNavigableFilter.
In order for the scroll thumb to receive focus, `verticalScrollbar`=`"visible"` is needed on the Scroller.
WRN-2467
Enact-DCO-1.0-Signed-off-by: Jeonghee …
=> WRN-2467: Fix wrong initial focus on scroll body when `focusableScrollbar` is `byEnter`

ContextualPopupDecorator/tests/ContextualPopupDecorator-specs.js
Migrated unit tests from Enzyme to Testing Library for ContextualPopupDecorator component.
WRN-1347
=> WRN-1347: Migrate ContextualPopupDecorator unit tests to Testing Library

.gitignore
We use WebStorm from IDEA IntelliJ and there are always some untracked files that we need to leave aside when making a commit. So I updated gitignore file to ignore editor folder. 
When committing from command line: ![image](https://user-images.githubusercontent.com/63341832/119624813-3272b880-be12-11eb-97ba-c9182f8ffe54.png)
When committing from editor: ![image](https://user-images.githubusercontent.com/63341832/119624922-4e765a00-be12-11eb-8289-e7bf9a0c3f41.png)
=> Updated gitignore file to ignore editor folder

CHANGELOG.md, DatePicker/DatePickerBase.js, DatePicker/tests/DatePicker-specs.js, TimePicker/TimePickerBase.js, TimePicker/tests/TimePicker-specs.js, internal/DateTime/DateTime.js, samples/sampler/stories/default/DatePicker.js, samples/sampler/stories/default/TimePicker.js, tests/screenshot/apps/components/DatePicker.js, tests/screenshot/apps/components/TimePicker.js
The GUI requirement is to display the Date/TimePicker without a label.
There are several scenarios for hiding time/date labels.
It Added prop `noLabel`  to DatePicker and TimePicker.
And then, if `label` is not valid, not displays Heading.
WRN-2465
=> WRN-2465: Date/TimePicker: add prop to hide label

CHANGELOG.md, MediaPlayer/MediaControls.js
Not work trick play via key event. This issue occurs on snapshot build (EPK image).
Added `document` as event target to on() event method.
WRN-3543
=> WRN-3543: MediaControls: Fix not working trick play via key

CHANGELOG.md, FixedPopupPanels/FixedPopupPanels.js, PopupTabLayout/PopupTabLayout.js, samples/sampler/stories/qa/FixedPopupPanels.js, samples/sampler/stories/qa/PopupTabLayout.js
FixedPopupPanels: onBack is called during key navigation in additional popup
Added a guard for the case
I'm not sure we need to handle cancel key on sandstone to prevent onBack.
In this PR, I just add handler on sampler side.
WRN-3473
=> WRN-3473: FixedPopupPanels, PopupTabLayout: Prevent left key navigation when popup opened inside

CHANGELOG.md, ContextualPopupDecorator/ContextualPopupDecorator.js
Fixed `ContextualPopupDecorator` not focusing items in `ContextualPopup` with 5WaySelector when `spotlightRestrict` is `self-first` 
`ContextualPopup` prop `direction` was changed compared to moonstone. For example, `down` to `below` and `up` to `above`.
As `ContextualPopup` direction (e.g., below, above) cannot be directly compared to the key event direction (e.g., up, down, right, left), convert direction of `ContextualPopup`.
[//]: # (Were any …
=> WRN-1658: Fixed ContextualPopupDecorator not focusing items in ContextualPopup when spotlightRestrict is self-first

CHANGELOG.md, MediaPlayer/MediaSlider.js, Slider/Slider.js
When scrolling wheel in video player, media list should be show up.
But in current status, try to seek media file.
Wheel event handler in Slider is accept event more higher priority than video panel.
For resolve this issue, new prop is added to slider and used in MediaSlider.
N/A
WRN-3709
N/A
=> WRN-3709: Block wheel event in VideoPlayer

CHANGELOG.md, Item/Item.js, samples/sampler/stories/qa/Item.js, samples/sampler/stories/qa/Item.module.less
When changing `slotAfter` or `slotBefore` dynamically, sometimes marquee doesn't update properly.
The reason why this issue happens is that we don't re-calculate the distance for marquee after `slotAfter` or `slotBefore` changed.
I've added `MarqueeDecorator` to add `invalidateProps` to trigger the re-calculation of the distance for those props.
When we implement the Item for the first time, in #5, …
=> WRN-3886: Item: Fix to update marquee when `slotAfter` or `slotBefore` changed

CHANGELOG.md, samples/sampler/stories/qa/Scroller.js, useScroll/ScrollbarTrack.js
When the Scroller has short content and the scrollbar is visible, the focus is not moving via up down key from the scroll thumb. 
When the content is short, the `--scrollbar-thumb-progress-ratio` is NaN since the client size and scrollable size is the same.
We didn't care about this case when we move the focus from scroll thumb. I've added a guard to care about this case.
[//]: # (Related issues, …
=> WRN-5464: Fixed Scroller to move focus via up/down keys from scroll thumb when the content is short but the scrollbar is visible

Alert/Alert.js, Alert/Alert.module.less, CHANGELOG.md
Alert root `div` node has a default display `block` which can affect the app layout breaking.
Apply display `inline` instead.
WRN-5836
=> WRN-5836: Alert: Remove display `block` from the root node

CHANGELOG.md, VirtualList/useThemeVirtualList.js
VirtualList is focusing the item again if focus moved out of the list via 5way quickly when `snapToCenter`.
Added a guard that checks if scrolling is ongoing and the current focus is in the list. If not, the list will not focus again.
WRN-6815
=> WRN-6815: Fixed VirtualList to not focus the item again if focus moved out of the list via 5way when `snapToCenter`

CHANGELOG.md, internal/Panels/Arrangers.js
Panel transition took long time after wheel. 
Add timeout option to requestIdleCallback
(refer : https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback
"Note: A timeout option is strongly recommended for required work, as otherwise it's possible multiple seconds will elapse before the callback is fired.")
WRN-6875
=> WRN-6875: Panels: Fixed to perform transition without delay when wheeling

samples/sampler/stories/qa/Spotlight.js, samples/sampler/stories/qa/Spotlight.module.less
Need to test to check whether the Spottable component is re-rendered when the focus is changed .
Add a qa-sample for checking re-render of Spottable component on focus change.
WRN-797
=> WRN-797: Create a sample to test spotlight/Spottable: Prevent re-render on focus change

Skinnable/Skinnable.js, ThemeDecorator/ThemeDecorator.js, styles/skin.less
A background color of overlayed Alert when high contrast mode.
- Removed unintended class 'highContrast' from app root
- Removed unnecessary class on app root since it will be added by Skinnable
- Restored applySkins() mixin code to apply high contrast mode
WRN-6634
=> WRN-6634: Fixed background color of overlayed Alert when high contrast mode

CHANGELOG.md, ProgressBar/ProgressBar.module.less, Slider/Slider.module.less, styles/colors-light.less, styles/colors.less, tests/screenshot/specs/light/Light-specs.js, tests/screenshot/specs/light/Light2-specs.js, tests/screenshot/specs/light/Light3-specs.js, tests/screenshot/specs/light/Light4-specs.js, tests/screenshot/specs/light/Light5-specs.js, tests/screenshot/specs/light/Light6-specs.js, tests/screenshot/specs/light/Light7-specs.js, tests/screenshot/specs/light/Light8-specs.js, tests/screenshot/specs/light/Light9-specs.js, tests/screenshot/specs/light/SandstonePage.js
In light skin, 
There was not much difference between the progress bar and fill or load colors.
Add alpha 40% for bar color to improve visibility.
Add Light skin spec to screenshot test
WRN-8227
=> WRN-8227: change light skink progressbar color for visibility

CHANGELOG.md, TimePicker/TimePicker.module.less, TimePicker/TimePickerBase.js
When it is changed to disabled state, only the text color of the Picker is changed except for the separator.
By passing the `disabled` prop to the separator node, `sand-disabled` mixins are applied.
WRN-9173
=> WRN-9173: TimePicker: Fixed disabled color of separator

ActionGuide/ActionGuide.js, ActionGuide/tests/ActionGuide-specs.js, CHANGELOG.md, MediaPlayer/MediaControls.js, samples/qa-a11y/src/views/VideoPlayer.js, samples/sampler/stories/default/ActionGuide.js, samples/sampler/stories/default/VideoPlayer.js
There is no way to set aria-label of actionGuide button
Add `sandstone/ActionGuide` prop `buttonAriaLabel` 
Add `sandstone/MediaControls` prop `actionGuideButtonAriaLabel` 
WRN-11532
=> WRN-11532: Added props to override aria-label of ActionGuide's button

samples/sampler/stories/default/Panels.js
Fixed panels sampler not to flickers when transitioning panel
Updated panels sampler to render `VirtualGridList` with fixed items 
WRN-1236
=> WRN-1236: Updated panels sampler to render VirtualGridList within panel with fixed items

samples/sampler/stories/qa/Item.js
Sandstone Item component only supports single-line content but sample with multi-line case exists.
Remove unused QA sample Item integrated with other components
WRN-10967
=> Remove unused QA sample Item integrated with other components

CHANGELOG.md, useScroll/useEvent.js
Scroll position is rollback after voice control scroll
In pointer mode, reset last-focus to the item currently visible
WRN-12780
=> WRN-12780: Fix Scroller and VirtualList to focus the topmost element after scroll via voice control in pointer mode

samples/sampler/stories/qa/Scroller.js
In QA Scroller sampler, a control for `noScrollByWheel` is missing.
Update code to show up the control.
WRN-13078
=> WRN-13078: Fix missing Control `noScrollByWheel` for Scroller sampler

CHANGELOG.md, Scroller/useThemeScroller.js
- fixed `sandstone/Scroller` to scroll correctly on Android Chrome 85 or higher in RTL locales
- fixed jsdoc for calculateScrollLeft function
WRN-12781
=> WRN-12781: Fixed Scroller to scroll correctly on AndroidChrome in RTL locales

BodyText/BodyText.module.less, CHANGELOG.md, styles/variables.less
`BodyText` does not change size when RTL locale is used
Added a new `@sand-non-latin-body-small-font-size: 48px` variable. An old PR (#6) removed this variable when upgrading variables from FHD to 4k
WRN-12697
=> WRN-12697: Cross-Platform Enact Android/iOS: BodyText - font size should change for rtl locale

styles/internal/fonts.less
On android devices, some tall strings(th-TH locale) is truncated since they use system font.
Make web font to be rendered instead of system font for this specific case.
@font-face rule related to thai font will be stacked onto Manual Sandstone Locale Fonts rules.
Need to be tested with enact:feature/WRN-12676 branch (https://github.com/enactjs/enact/pull/2990) …
=> WRN-12676: Use web font(thai) instead of system font to avoid truncating tall strings

CHANGELOG.md, Input/Input.js, Input/NumberField.js, Input/tests/Input-specs.js, samples/sampler/stories/default/Input.js
We need to backport #971 into the old touch branch to provide apps a way to hide a submit button.
Cherry-picked #971
#971
WRN-14493
PLAT-145596
=> WRN-14493: Hide submit button in Input

CHANGELOG.md, Scroller/Scroller.js, VirtualList/VirtualList.js
Feature to show overscroll effect for flicking input on touchable devices
Updated default effect option for lists and scrollers.
For better tracking, I cherry-picked an old PR from an experimental branch for touch support testing.
On touchable devices, flicking by a press-and-hold pointer also makes overscroll effects when a scrollable component reaches the edge. This is intended behavior as a pointer scrolls contents when a user press-and-hold a button.
[//]: # …
=> WRN-13076: Support overscroll effect for flicking

CHANGELOG.md, MediaPlayer/MediaControls.js, VideoPlayer/VideoPlayer.js, VideoPlayer/VideoPlayer.module.less, samples/sampler/stories/default/VideoPlayer.js, styles/variables.less
Video player needs backbutton and a prop for aria-label override.
- Cherrypick https://github.com/enactjs/sandstone/pull/803 
- Add backButtonAriaLabel.
- To support RTL, add iconFlip="auto"
WRN-12963, WRN-127111
=> WRN-12963: Add back button to Video Player

CHANGELOG.md, internal/Picker/Picker.js
Fixed joined horizontal Picker to go to the next item by touch
Go to the next item by clicking on the joined horizontal Picker was introduced sandstone by https://github.com/enyojs/sandstone/pull/179.
When this feature added, I assume the touch behavior was not considered.
When we interact with the mouse, `onDown` event is fired after `onMouseDown`. But, with touch, `onDown` event is fired before `onMouseDown` so the logic flows the wrong way.
To resolve this, I moved the `setIncPickerButtonPressed` related logic into `handleDown` so that even if the order of the events is swapped, the behavior could be …
=> WRN-12845: Fixed joined horizontal Picker to go to the next item by touch

samples/sampler/stories/qa/Spinner.js
The container for the qa-samplers for "Spinner with long content" and "Spinner blocking click events" had a height bigger than the screen size or the 2 buttons were overlapping
Changed the height of the container to "fit-content" in order to make all the content fit on screens with portrait mode ( phones and tablets)
WRN-12703
=> WRN-12703: Fixed container height for Spinner qa-samples

CHANGELOG.md, useScroll/HoverToScroll.js, useScroll/useScroll.js
VirtualList/VirtualGridList: hoverToScroll not working after rendering
Cause : 
`HoverToScrollBase` hook function and life cycle functions should be invoked properly when `scrollContainer` is updated.
However, the lifecycle functions are called later by setState from update().
It is becuase `HoverToScrollBase` receive `scrollContainerHandle` instead of `scrollContainer`.
Resolution : 
I changed `HoverToScrollBase` to get `scrollContainerHandle.current` instead of `scrollContainerHandle`.
[//]: # …
=> WRN-15665: VirtualList: Fix `HoverToScroll` to update properly after changing `dataSize`

tests/screenshot/specs/light/SandstonePage.js, tests/screenshot/specs/neutral/SandstonePage.js, tests/ui/specs/Alert/Alert-specs.js, tests/ui/specs/Alert/Alert-utils.js, tests/ui/specs/Alert/AlertPage.js, tests/ui/specs/Button/Button-specs.js, tests/ui/specs/Button/ButtonPage.js, tests/ui/specs/CheckboxItem/CheckboxItem-specs.js, tests/ui/specs/CheckboxItem/CheckboxItem-utils.js, tests/ui/specs/CheckboxItem/CheckboxItemPage.js, tests/ui/specs/ContextualMenuDecorator/ContextualMenuDecorator-specs.js, tests/ui/specs/ContextualMenuDecorator/ContextualMenuDecoratorPage.js, tests/ui/specs/ContextualPopupDecorator/ContextualPopupDecorator-specs.js, tests/ui/specs/ContextualPopupDecorator/ContextualPopupDecoratorPage.js, tests/ui/specs/DatePicker/DatePicker-specs.js, tests/ui/specs/DatePicker/DatePicker-utils.js, tests/ui/specs/DatePicker/DatePickerPage.js
@wdio/sync was depreacted on node 16.
Fix ui-test TC to use async mode
To resolve intermittent TC fail "stale element reference: element is not attached to the page", I add `await` when Page.open()
WRN-14979
=> WRN-14979: Fix ui-test to use async test

samples/sampler/stories/qa/Heading.js
Words scattered when LTR and RTL characters are mixed
To guide the way of binding proper noun, add a Heading qa-sampler for bidirectional text.
WRN-14715
=> WRN-14715: add Heading qa-sampler for bidirectional text

Drawing/ColorPicker.js, Drawing/ColorPicker.module.less
Close color pickers on touch outside or on ESC key.
Changed the base component from ButtonBase wrapped with ContextualPopupDecorator to Popup.
WRN-18221
=> WRN-18221: Close color pickers on touch outside or on ESC key.

CHANGELOG.md, WizardPanels/useFocusOnTransition.js, samples/sampler/stories/qa/WizardPanels.js
If app change focus on onTransition,  WizardPanel re-change the focus to panel element.
Allow preventDefault on onTransition to prevent spotlight to panel element.
So, App should call the ev.preventDefault() to resolve the previous bug.
WRN-19246
=> WRN-19246: WizardPanels: Allow preventDefault on onTransition to prevent spotlight to panel element

Scroller/EditableWrapper.js, Scroller/EditableWrapper.module.less, Scroller/Scroller.js, Scroller/Scroller.module.less, Scroller/useThemeScroller.js, samples/sampler/stories/qa/Scroller.js, useScroll/useScroll.js
Added `editable` prop to Scroller to support editing items
To support editing, added a flex wrapper and used flex `order` to order items. 
WRN-18729
=> WRN-18729: Added `editable` prop to Scroller to support editing items

Drawing/ColorPicker.js, Drawing/ColorPicker.module.less, Drawing/Drawing.js, Drawing/DrawingControls.js
Implemented functionality to set/get preset colors to/from localStorage.
WRN-18649
=> WRN-18649: [Drawing POC] - Set/Get preset colors to/from localStorage

CHANGELOG.md, samples/sampler/stories/qa/Scroller.js, samples/sampler/stories/qa/VirtualList.js, useScroll/useScroll.js
There is new 2023 TV UX about the restoring focus after scroll.  Focus should be set on the current visible top-most item in pointer mode.
In pointer mode, reset last-focus to the item currently visible
WRN-16710, WRN-12780, https://github.com/enactjs/sandstone/pull/1118
=> WRN-16710: Fix Scroller and VirtualList to focus the topmost element after scroll in pointer mode

Drawing/ColorPicker.js, Drawing/Drawing.js, samples/sampler/stories/default/Drawing.js
Added storybook color picker control for changing brush, canvas and fill color for drawing component.
WRN-19924
=> Feature/WRN-19924: Add color picker control in storybook

.travis.yml, samples/sampler/stories/qa/FixedPopupPanels.js, samples/sampler/stories/qa/Panels.js
When two floatinglayers are displayed, there is a bug that a popup which open later shown on down of other popup .
Add a story to test two floating layers in FixedPopupPanel qa-sampler 
I fixed minor console error on Panels qa-sampler
WRN-18494
=> WRN-18494: Add a story to test two floating layers in FixedPopupPanel qa-sampler

tests/ui/specs/Scroller/ListOfThings/Scroller-QWT-2662-specs.js, tests/ui/specs/VirtualList/VirtualList/Samples/VirtualList-QWT-2137-specs.js
- Need to add delay for VirtualList ui-test(QWT-2317).
- Need to skip Scroller ui-test(QWT-2662).
- Add delay for VirtualList ui-test(QWT-2137).
- Skip Scroller ui-test(QWT-2662).
WRN-20381
WRN-20012
QWT-2137
QWT-2662
QWT-2662 will skip test until WRN-20012 will be resolved.
=> WRN-20381: Skip scroller ui-test.

Scroller/EditableWrapper.js
- Added acceleration feature for holding-down 5-way keys
- Updated to work only once when holding down `enter` key
WRO-242
=> WRO-242: Refine 5-way control for a editable scroller

Button/Button.js
Receiving the "className" config on MarqueeDecorator is not our standard way.
Replace `className` config to `css` for `ui/MarqueeDecorator`
WRO-608
=> WRO-608: Replace `className` config to `css` of `ui/MarqueeDecorator`

Scroller/EditableWrapper.js
The isomorphic test is failed on EditableWrapper.
```
@enact/sandstone/Scroller/EditableWrapper<EditableWrapper>: FAILURE
TypeError: Cannot read property 'centered' of undefined    
```
Added checking variable to prevent errors.
WRO-3909
=> WRO-3909: Fix isomorphic test

Scroller/EditableWrapper.js
Fixed editable wrapper to set proper index of selected item when scrolled by 5way mode
Check if it is pointer mode when moving items by scroll event
WRO-4073
=> WRO-4073: Fixed editable wrapper to set proper index of selected item when scrolled by 5way mode

.travis.yml, CHANGELOG.md, Scroller/EditableWrapper.js
The UX guide specifies changing the order of items when 1/3 of the items have passed.
- Fix `sandstone/Scroller` sensitivity to swap items on the editable mode.
- Fix `centeredOffset` formular (Because ev.clientX value is based on root element rather than `editable` wrapper div. So I used body width) 
WRO-591
=> WRO-591: Fixed editable wrapper to adjust sensitivity to swap the items

.travis.yml, CHANGELOG.md, Popup/Popup.js, Popup/tests/Popup-specs.js
App developers want to know which user input invokes `onClose` event from `Popup`, `PopupTabLayout`, `FixedPopupPanels`, and `FlexiblePopupPanels` to provide different actions based on the input type.
Added `detail` property that contains `inputType` value: its value is `'key'` for `ESC` key, and `'click'` for clicking outside a popup.
WRO-3415
enactjs/enact/pull/3060
=> WRO-3415: Provides event payload info for input type

.travis.yml, Scroller/EditableWrapper.js, useScroll/HoverToScroll.js
Scroller does not scroll properly by wheel when `editable` is given and one item is selected.
Update calculation for a position of the selected item to compensate the position only for hovering on edge not for a wheel input.
WRO-4786
=> WRO-4786: Fix editable scroller to scroll properly by wheel

CHANGELOG.md, TabLayout/TabLayout.js
2023 UX requirements have changed to the number of horizontal tabs 6->8
Remove limitation of the number of horizontal tabs. 
Enact tab width automatically stretches on horizontal tabs and the number 8 can be changed to any number in the future. Rather than changing the limited number, I’d delegate the choice of horizontal tab numbers to apps with proper tab title length or only with icon.
I just removed check logic from the computed but I also thought the other …
=> WRO-4544: Remove limitation of the number of horizontal tabs

CHANGELOG.md, ContextualPopupDecorator/ContextualPopupDecorator.js, samples/sampler/stories/qa/Dropdown.js
Popup location is not updated when the screen composition is changed while `Dropdown` is open
Update position whenever `componentDidUpdate` with open status.
(Because already there is a logic to calculate the position when it is opened, I have updated the position when it was open before and now)
With the structure of calculate position/setState in didUpdate, performance issues may occur. In this case, revert should be considered.
[//]: # (Related issues, …
=> WRO-5469: Fixed `ContextualPopupDecorator` to update `ContextualPopup` position properly when repositioned in open

CHANGELOG.md, FixedPopupPanels/FixedPopupPanels.module.less, samples/sampler/stories/default/FixedPopupPanels.js, samples/sampler/stories/default/FixedPopupPanels.module.less
Using fixedPopupPanels.panel with fullHeight option, footer cannot be placed as intended with padding or margin.
Since the flex-grow value of the panel body is set to 0, so the height of the body cannot be 100%. When setting padding value for the footer, the footer component overlaps with the component above it.
Fixed flex-grow value of fixedPopupPanels.panel body from 0 to 1 to place the last children component of the panel body as intended, not collapsed with other components.
[//]: # (Were any side-effects caused by …
=> WRO-5477: Fixed fixedPopupPanels.panel to place the last children component as intended.

samples/sampler/stories/qa/TabLayout.js
- Need to remove 'collapsed' prop in TabLayout sample.
- Remove 'collapsed' prop in TabLayout sample.
WRO-5036
As a result of the discussion, we decided to remove 'collapsed' prop from sampler controls. None of the TCs related to this sample used 'collapsed' prop, and there is no related history.
=> WRO-5036: Tab does not collapse when enters a menu.

CHANGELOG.md, samples/sampler/stories/qa/Scroller.js, useScroll/useScroll.js
Current scroller scroll to the top when resizing event regardless of current focused item and position.
Fixed scroller to allow input via VKB into inputfields within the scroller even when the window is resized.
When handling resize window, element.scrollIntoView when focused item exist.
WRO-398
=> Fixed scroller to position focused item into view when the window is resized

CHANGELOG.md, Picker/Picker.js, internal/Picker/Picker.js, internal/Picker/tests/Picker-specs.js, samples/qa-a11y/src/views/Picker.js, samples/sampler/stories/qa/TabLayout.js, useScroll/ScrollbarTrack.js, useScroll/useScroll.js
There was A11y UX update for Picker / ScrollbarTrack.
I changed `sandstone/Scroller` scrollbar thumb to read out "Press ok button button to read text" additionally when `focusableScrollbar` prop is `byEnter`
I changed `sandstone/Scroller` scrollbar thumb to read out 'leftmost', 'rightmost', 'topmost', or 'downmost' when reaching the end of the scroll
I changed `sandstone/Picker` and `sandstone/RangePicker` to read out `title` …
=> WRO-4785: Update A11y UX (Picker / ScrollbarTrack)

CHANGELOG.md, Scroller/EditableWrapper.js, samples/sampler/stories/qa/Scroller.js
Need to support A11y feature on for editable scroller
Specs : 
* When focus item in Scroller (I fixed sampler. It should be implemented on App)
<item label> + <"Edit mode to press and hold OK key")
* When entering edit mode and focusing for the first time
<item label> + <"Move left and right or press up key to delete")
*  press left / right
<item label> + <"moved to the left of"> + <item label.position+1>
<item label> + <"moved to the right of"> + <item label.position-1>
App should add `data-item-label` on the each item's container
* press left/right when focus on leftmost/rightmost
<"Leftmost"> …
=> WRO-4784: Added A11y feature for editable scroller

CHANGELOG.md, Scroller/EditableWrapper.js, samples/sampler/stories/qa/Scroller.js, tests/ui/specs/Scroller/EditableScroller/Scroller-QWT-4513-specs.js, tests/ui/specs/Scroller/EditableScroller/Scroller-QWT-4514-specs.js, tests/ui/specs/Scroller/EditableScroller/Scroller-QWT-4515-specs.js
UX changed to select item in editable scroller by long pressing the OK button or enter key.
Used `@enact/ui/touchable.hold` to handle long press of the OK button, and long press of the enter key was handled by setTimeout.
WRO-6262
=> WRO-6262: Fixed editable scroller to select item by long press

ContextualPopupDecorator/ContextualPopupDecorator.js, Popup/Popup.js
`noAutoDismiss` prop doesn't explain about clicking the outside of the floating layer
Update doc
WRO-5805
=> WRO-5805: Fix docs for 'noAutoDismiss'

tests/ui/specs/VideoPlayer/VideoPlayer-specs.js, tests/ui/specs/VirtualList/VirtualList/WithMultipleSpottables/VirtualList-QWT-2389-specs.js
- Need to add delay before long press in ui-test.
- Need to add delay wait for loading video in ui-test(VideoPlayer).
- Add delay before long press in ui-test.
- Add delay wait for loading video in ui-test(VideoPlayer).
WRO-6793
It only reproduced in jenkins.
=> WRO-6793: Add delay before long Press in ui-test(QWT-2389).

.travis.yml, CHANGELOG.md, WizardPanels/WizardPanels.js, WizardPanels/tests/WizardPanels-specs.js
The event payload of `onBack` event of `WizardPanels` does not have `stopPropagation` method.
This PR changes `WizardPanels` to provide `stopPropagation` method in `onBack` event payload.
This PR relies on enactjs/enact#3067.
WRO-6848
enactjs/enact#2982
enactjs/sandstone#1120
enactjs/sandstone#1136
=> WRO-6848: Provide `stopPropagation` method in `onBack` event payload of `WizardPanels`

styles/internal/fonts.less
TH Webfont always loads and it occur cause flicker.
The flicker cause screenshot test fail on Khmer TC.
Prevent to webfont loading when the webos font is installed.
WRO-2688
https://github.com/enactjs/sandstone/pull/1138
=> WRO-2688: Prevent to webfont loading when the webos font is installed

CHANGELOG.md, FixedPopupPanels/FixedPopupPanels.js, PopupTabLayout/PopupTabLayout.js, TabLayout/TabLayout.js, samples/sampler/stories/qa/FixedPopupPanels.js, samples/sampler/stories/qa/PopupTabLayout.js, samples/sampler/stories/qa/TabLayout.js
Unable to move caret using left and right keys in the InputField, when InputField is located in FixedPopupPanels, PopupTabLayout and TabLayout. When left or right keys pressed, focus moved to other spottable. 
In this change, I fixed to move the caret when left or right keys are pressed in InputField.
Added condition in FixedPopupPanels, PopupTabLayout, and TabLayout handlers to check whether event target is INPUT.
Fixed not to follow the onKeyDownHandler logic associated with the left and right keys if event target is INPUT.
[//]: # (Are there any outstanding …
=> WRO-7201: Fixed FixedPopupPanels, PopupTabLayout, and TabLayout onKeyDown handlers to check whether event target is INPUT

samples/sampler/.qa-storybook/main.js, samples/sampler/.storybook/main.js, samples/sampler/npm-shrinkwrap.json, samples/sampler/package.json
Storybook uses the default builder as webpack4, but we want to update this to webpack5.
Configurations were added as https://storybook.js.org/docs/react/builders/webpack guided.
WRO-614
=> WRO-614: Migrate storybook sampler builder to Webpack5

Alert/Alert.module.less, CHANGELOG.md, samples/sampler/stories/qa/Alert.js, samples/sampler/stories/qa/ProgressBar.js, styles/colors-light.less, styles/colors.less, tests/screenshot/apps/components/Alert.js
ProgressBar is not distinguished in Alert 
Fix override color about progressbar
This issue is releated with https://github.com/enactjs/sandstone/pull/1220 / https://github.com/enactjs/sandstone/pull/1257
After 1220, skin should override `@sand-progress-bg-color-rgb` value instead of `@sand-progress-bg-color`
WRO-7722
=> WRO-7722: Fix Alert override color to show Progressbar properly 

tests/screenshot/apps/Sandstone-View.js, tests/screenshot/apps/components/ContextualMenuDecorator.js
In ContextualMenuDecorator screenshot test, there were some symptoms that button in screenshot image get truncated as attached image.
Because of the large padding value set in ContextualMenuDecorator screenshot test view, vertical scrollbar created when screenshot image generated. And this scroll bar moved the button.
As screenshot test view need to be fit in 1920 * 1080 size,  we added overflow property value to be hidden.
This style can prevent the same problem from occurring in other RTL locale tests.
[//]: # (Were …
=> WRO-2545: Fixed ss test Sandstone-View outer div overflow property value to hidden

samples/qa-a11y/src/views/Panels.js
In qa-a11y panel sample, when navigating from panel 1 to panel 0, focus did not properly restored to the last focused item.
If the `virtualList` in panel 0 does not set spotlightId, data-spotlight-id is set to container-#. And when switching to panel 0, the data-spotlight-id of panel 0 is updated, for example from container-9 to container-13.
In this case, the spotlight cannot restore focus to the `virtualList` as the spotlight remember the lastFocusedElement information as old data (e.g., container-9).
Added `spotlightId` prop in `VirtualList` …
=> WRO-7341: Fixed qa-a11y panel sample to restore focus properly

CHANGELOG.md, useScroll/HoverToScroll.js
hoverToScroll props is not work properly with translate scrollMode
Cause : 
In Translate mode, the timing when the `update()` is called by the `onScroll` event is after `RequsetAnimation`(RAF).
Therefore, it does not `stop` and the `RAF` is executed forever.
Resolution:
So, in addition to calling `cancelAnimationFrame` in the `stopRaf` function, we should use more certain way to prevent the next `RAF` execution.
In this patch, I use the `hoveredPosition` variable we already have to check if the `RAF` has stopped to prevent further `RAF`s.
FYI : The current invoking order is as follows.
`startRaf` -> …
=> WRO-8225: Fixed scoll by hover to work properly when `scrollMode` is translate

CHANGELOG.md, Panels/Panel.js, samples/sampler/stories/qa/FixedPopupPanels.js, useScroll/ScrollbarPlaceholder.js, useScroll/ScrollbarTrack.js
Focus restored to wrong element when returning panel in case focusable scrollbar
Ignore scrollThumb and scrollbarPlaceholder when focus persist and restore.
This method has already been applied at https://github.com/enactjs/enact/pull/2994 (for moonstone)
I found FixedPopupPanels/WithVirtualList qa-sampler does not restore focus. So I fixed it in this PR.
WRO-4920
=> WRO-4920: Ignore scrollThumb and scrollbarPlaceholder when focus persist and restore

Input/Input.js, Input/InputFieldSpotlightDecorator.js, samples/qa-a11y/src/views/Input.js
Need refactoring to remove `aria-hidden` in Input component
Revmoe `noReadoutOnFocus` prop and `aria-hidden` prop in Input component.
To meet the A11y UX specifications, I  use `role="region"` and `aria-labelledby` to read title and subtile when open Input popup  instead `aria-live="alert"`.
With `aria-live="alert"`, read all children element, so we needed `aria-hidden` to avoid reading the focused element twice.
But With `role="region"` and `aria-labelledby`, We can only read the title/subtitle. and the focus item will be read after.
I apply the same method used by Panel.
* The text read when Input popup …
=> WRO-679: Remove aria-hidden in Input component

CHANGELOG.md, FixedPopupPanels/FixedPopupPanels.js, PopupTabLayout/PopupTabLayout.js, samples/sampler/stories/qa/FixedPopupPanels.js, samples/sampler/stories/qa/PopupTabLayout.js, tests/ui/specs/FixedPopupPanels/FixedPopupPanels-specs.js
Cannot restore scroll position when go back to the previous panel by left key on FixedPopupPanles or PopupTabLayout
- Invoke preventDefault for scroll. (keyDown event prevented scroll action)
- Invoke Spotlight.setPointerMode(false); to change mode after click and left key for PC
There was Intermittent fail on ui-test, So i fixed it although it has nothing to do with this issue. 
WRO-9081
Enact-DCO-1.0-Signed-off-by: Jeonghee Ahn …
=> WRO-9081: Fixed `FixedPopupPanles` and `PopupTabLayout` to restore scroll position when going back to the previous panel by left key

VideoPlayer/VideoPlayer.module.less, samples/sampler/stories/qa/VideoPlayer.js
VideoPlayer: Back button is not visible when layer is created on top of VideoPlayer.
Add z-index value  for .back class selector.
WRO-9819
=> WRO-9819: [VideoPlayer] Back button is not visible

TimePicker/TimePickerBase.js
`qa-scroller` failed to build when `enact pack --isomorphic`.
When `TimePicker` is at the first view, the isomorphic build is failed.
There were accessing a property of `undefined` from TimePickerBase. So I've added a guard code.
WRO-8219
=> WRO-8219: TimePicker: Fix isomorphic build error

CHANGELOG.md, VideoPlayer/VideoPlayer.js
`VideoPlayer` seeks infinitely when pointer moves while holding left or right key
Currently, `VideoPlayer` seeking logic is two fold. One is inside `VideoPlayer` and another is in `MediaControls`.
The one in `MediaControls` seems redundant and causes this issue so I removed `onJump` handler from it.
WRO-10990
=> WRO-10990: Fixed `VideoPlayer` to not seek inifinitely when pointer moves while holding key

TransferList/TransferList.js, samples/sampler/stories/default/TransferList.js
For dragging and dropping items from a list to another, by default only the item that is dragged was moved to the other list
Added a new prop "allowMultipleDrag". When this is true, all the selected items, together with the dragged item will be moved to the destination list
WRO-614
=> WRO-10614: TransferList POC: Added support for drag&drop for multiple items

CHANGELOG.md, Scroller/Scroller.module.less
Focus effect was shown when click the body in pointer mode
According to the UX document, focus effect should not be shown in pointer mode.
So I fixed related style. the focus color will be shown only in key mode.
WRO-11388
=> WRO-11388: Scroller: Fixed to not show the focus effect of the body in pointer mode when focusableScrollbar is `byEnter`

samples/sampler/.qa-storybook/preview.js, samples/sampler/.storybook/preview.js, samples/sampler/stories/default/KeyGuide.js, samples/sampler/stories/qa/Dropdown.js, samples/sampler/stories/qa/Text.js
After migrating Storybook 6.5, sampler- KeyGuide, qa-sampler- Dropdown - with array of children objects, and Text - Languages stories are not opened.
The issue is caused by `jsxDecorator` function from `@storybook/react/dist/esm/client/docs/jsxDecorator.js` (https://github.com/storybookjs/storybook/blob/main/app/react/src/client/docs/jsxDecorator.tsx#L206)
When I looked at this code, this is for the show code section in Docs tab in the sampler. So I think we could work around it by skipping the part that throws errors since it's not related to rendering the story.
We could "skip" this code by setting …
=> WRO-9259: Fix some stories are not shown with storybook 6.5

samples/qa-a11y/src/views/Alert.js, samples/qa-a11y/src/views/ImageItem.js, samples/qa-a11y/src/views/TabLayout.js, samples/qa-a11y/src/views/VideoPlayer.js, samples/qa-a11y/src/views/VirtualGridList.js, samples/qa-virtualgridlist/src/utils/index.js, samples/qa-virtualgridlistnative-preserve-focus/src/components/SampleVirtualGridList.js, samples/sampler/npm-shrinkwrap.json, samples/sampler/stories/default/Alert.js, samples/sampler/stories/default/Image.js, samples/sampler/stories/default/ImageItem.js, samples/sampler/stories/default/Panel.js, samples/sampler/stories/default/Panels.js, samples/sampler/stories/default/TabLayout.js, samples/sampler/stories/default/VideoPlayer.js, samples/sampler/stories/default/VirtualGridList.js, samples/sampler/stories/helper/svg.js, samples/sampler/stories/qa/Alert.js, samples/sampler/stories/qa/ImageItem.js, samples/sampler/stories/qa/Panels.js, samples/sampler/stories/qa/Scroller.js, samples/sampler/stories/qa/VirtualGridList.js
There is a problem that image download often fails on the placeholder website used in samples
Instead of downloading the image from the site, change it to create and use the image as svg
WRO-11048
=> WRO-11048: Change the image used in the sample to svg

Scroller/EditableWrapper.js, internal/Picker/Picker.js
As we added `usePublicClassNames` from https://github.com/enactjs/enact/pull/3079, we'd like to adopt it to sandstone/Scroller/EditableWrapper.
Applied `usePublicClassNames` to `EditableWrapper`.
WRO-10211
=> WRO-10211: Apply `usePublicClassNames` to `EditableWrapper`

CHANGELOG.md, Slider/Slider.module.less
In some environment, the position of `Slider`'s tooltip arrow is not properly synced when a value is changed.
The issue occurs when some old versions of browsers handle `will-change: left, bottom` attribute. As a workaround, `will-change: transform` is used to fix this.
WRO-12236
=> WRO-12236: Fix `Slider` tooltip arrow to show properly

styles/colors-game.less
There is a request from GUI to change the background color of focused item.
The background color of focused item is changed to `#6D2FA1` from `#982929` in Game skin.
WRO-11412
=> Change the bg color of focused item in game skin

CHANGELOG.md, MediaPlayer/MediaControls.js
Focus does not move to Slider from MediaControls of VideoPlayer when left or right keys are held in pointer mode
It seems that spotlight didn't have chance to resume after the sequence.
So I added a condition for resetting spotlight when `visible` prop became true.
WRO-13031
=> WRO-13031: Fixed `MediaControls` to focus properly

CHANGELOG.md, MediaPlayer/MediaControls.js
Focus does not move to Slider from MediaControls of VideoPlayer when left or right keys are held in pointer mode
It seems that spotlight didn't have chance to resume after the sequence.
So I added a condition for resetting spotlight when `visible` prop became true.
Cherry-picked #1331.
WRO-13031
=> WRO-13031: Fixed MediaControls to focus properly (#1331)

CHANGELOG.md, useScroll/HoverToScroll.js, useScroll/useScroll.js
When horizontalScrollbar or verticalScrollbar is set to `hidden` scroll did not work with hover action in VirtualList.
To resolve the issue, we have to revert https://github.com/enactjs/sandstone/pull/1150.
In PR 1150, It fixed `HoverToScrollBase` to receive `scrollContainerHandle.current` instead of `scrollContainerHandle`.
However, this fix caused an error when the scrollbar is hidden, as VirtualList rendered only once in this case. 
So we reverted PR 1150. And then we have to fix `HoverToScroll` to scroll properly by hover after `dataSize` is changed(after rendering). Add the props to the useLayoutEffect …
=> WRO-13221: Fixed VirtualList to scroll properly by hover when scrollbar is hidden

CHANGELOG.md, useScroll/HoverToScroll.js, useScroll/useScroll.js
When horizontalScrollbar or verticalScrollbar is set to hidden scroll did not work with hover action in VirtualList.
To resolve the issue, we have to revert https://github.com/enactjs/sandstone/pull/1150.
In PR 1150, It fixed HoverToScrollBase to receive scrollContainerHandle.current instead of scrollContainerHandle.
However, this fix caused an error when the scrollbar is hidden, as VirtualList rendered only once in this case.
So we reverted PR 1150. And then we have to fix HoverToScroll to scroll properly by hover after dataSize is changed(after rendering). Add the props to the useLayoutEffect (line 177) …
=> WRO-13221: Fixed VirtualList to scroll properly by hover when scrollbar is hidden (2.5.x)

CHANGELOG.md, useScroll/HoverToScroll.js, useScroll/useScroll.js
When horizontalScrollbar or verticalScrollbar is set to hidden scroll did not work with hover action in VirtualList.
To resolve the issue, we have to revert https://github.com/enactjs/sandstone/pull/1150.
In PR 1150, It fixed HoverToScrollBase to receive scrollContainerHandle.current instead of scrollContainerHandle.
However, this fix caused an error when the scrollbar is hidden, as VirtualList rendered only once in this case.
So we reverted PR 1150. And then we have to fix HoverToScroll to scroll properly by hover after dataSize is changed(after rendering). Add the props to the useLayoutEffect (line 177) …
=> WRO-13221: Fixed VirtualList to scroll properly by hover when scrollbar is hidden (2.0.x)

CHANGELOG.md, ImageItem/ImageItem.module.less, VirtualList/useThemeVirtualList.js, VirtualList/useThemeVirtualList.module.less, tests/screenshot/apps/components/VirtualGridList.js
ImageItem would have the wrong size of an image when it's horizontal with importing VirtualList or Dropdown like below.
The root cause of this issue is that VirtualList imports ImageItem.module.less in useThemeVirtualList.js to apply the scale class to ImageItem when `snapToCenter` is true.
When webpack bundles css, the sandstone/ImageItem/ImageItem.module.less is imported first for the above reason and then ui/Imageitem/ImageItem.module.less imported so the issue occurred.
To resolve this, I made `useThemeVirtualList.module.less` to have the scale class instead of importing ImageItem.module.less.
[//]: # …
=> WRO-12412: Fixed ImageItem to have proper size with importing VirtualList

.travis.yml
Node 19 is now published(https://nodejs.org/en/blog/announcements/v19-release-announce/)
After this change, travis failure occurred continually so we need to block the current node temporarily.
Update .travis.yml to use the node 18
WRO-14562
Enact-DCO-1.0-Signed-off-by: Taeyoung Hong taeyoung.hong@lge.com
=> WRO-14562: Update .travis.yml to use the node 18

TransferList/TransferList.js, samples/sampler/stories/default/TransferList.js
Added selected order for each selected item and created a control for the story.
TransferList now has a showSelectionOrder control that can display the order in which the items are being selected.
WRO-14595
Enact-DCO-1.0-Signed-off-by: Andrei Tirla andrei.tirla@lgepartner.com
=> WRO-14595: Add selected order for each selected item

CHANGELOG.md, Input/Input.js, Input/Input.module.less
Tv reads out previous page's header after return the `PopupTabLayout` page from `Input` 's `Popup`
It is regression from https://github.com/enactjs/sandstone/pull/1289.
After removing "aria-hidden", the bug occurs.
So I add a wrapper `div` and set aria-own to prevent read parent page after return the previous page. 
It is exactly same way with `Alert` https://github.com/enactjs/sandstone/pull/813/
Screenshot test pass : Jenkins enact-screenshot-tests/1086/
[//]: # …
=> WRP-3423: Add aria-own to prevent read parent page

ActionGuide/ActionGuide.js, CHANGELOG.md, samples/qa-a11y/src/views/VideoPlayer.js, samples/sampler/stories/default/ActionGuide.js, tests/ui/specs/VideoPlayer/VideoPlayer-specs.js, tests/ui/specs/VideoPlayer/VideoPlayerPage.js
- Need to fix ui test as change the UX for VideoPlayer
- Need to change aria-label for ActionGuideButton as change the UX for VideoPlayer
- Fix ui test as change the UX for VideoPlayer
- Change aria-label for ActionGuideButton 'more' to 'More'
WRP-852
=> WRP-852: Fix ui-test and aria-label for ActionGuideButton in VideoPlayer

CHANGELOG.md, MediaPlayer/MediaControls.js, MediaPlayer/MediaControls.module.less
Buttons in the MediaControls were focusable and clickable even though it was hidden. 
They need to be disabled when they are hidden.
Added `visibility:hidden` css property to the related elements(moreButtonComponents, actionGuide).
WRP-4977
=> WRP-4977: Fixed MediaControls to disable hidden button properly

CHANGELOG.md, MediaPlayer/MediaControls.js, MediaPlayer/MediaControls.module.less
Buttons in the MediaControls were focusable and clickable even though when they are hidden.
They need to be disabled when they are hidden.
Added `visibility:hidden` css property to the related elements(moreComponents, actionGuide)
WRP-4977
=> WRP-4977: Fixed MediaControls to disable buttons properly when buttons are hidden

Scroller/tests/Scroller-specs.js, codecov.yml
Increased test coverage of Scroller component
- Add `focusableScrollbar` TCs.
- Ignore EditableWrapper.js file. 
It was decided to skip the tests for EditableScroller by internal discussion.
Most of the EditableWrapper code is a scenario after selection using long press. So it is impossible to verify this in unit tests.
I wanted to verify the Scrolling operation, not simply verify the DOM structure after the render, but I failed.
I tried several things as shown …
=> WRP-857: Add focusableScrollbar TC

TransferList/TransferList.js, TransferList/TransferList.module.less, samples/sampler/stories/default/TransferList.js
TransferList only supported VirtualList as component for source or destination list
Added support for VirtualGridList. Now there is a prop that can choose which component to use to render the lists
For the moment, the width of each ImageItem in the list is hardcoded as 5*height
WRP-4952
=> WRP-4952: TransferListPOC - Added support for VirtualGridList

CHANGELOG.md, styles/variables.less, useScroll/HoverToScroll.js
For better customer experience, we're going to tune hovering area and scroll speed by hovering in lists and scrollers.
Reduced hovering area and reduced scroll speed.
WRP-5352
=> WRP-5352: Tuning a horizontal scrolling speed by hover

CHANGELOG.md, useScroll/HoverToScroll.js
The issue was reported that when the pointer is in the hover area it scrolls for a while and then stopped in some cases.
We found that scrolls stopped because of stopRaf function in hoverToScroll.js invoked unintentionally. 
stopRaf function is invoked when scrollContainer is updated.
We removed the code that the stopRaf function is called because of scrollerContainer update.
We found in hoverToScroll.js …
=> WRP-5920: Fixed hoverToScroll not to invoke stopRaf when scrollContainer is updated

tests/ui/specs/VirtualList/VirtualList/WithMultipleSpottables/VirtualList-QWTC-2260-specs.js
- Need to delay when long-press button in virtuallist.
- Add delay when long-press button in virtuallist.
WRP-6869
=> WRP-6869: Fix ui-test fail for virtuallist.

TransferList/TransferList.js
When 'showSelectionOrder' is set to 'true' the wrong drag image is being displayed
Fixed drag image for 'showSelectionOrder' by adding an if else statement to 'potentialIndex' that checks for 'showSelectionOrder'.
WRP-6275
Enact-DCO-1.0-Signed-off-by: Andrei Tirla andrei.tirla@lgepartner.com
=> WRP-6275: Incorrect drag image when showSelection={true}

CHANGELOG.md, MediaPlayer/MediaControls.js, MediaPlayer/MediaControls.module.less
`MediaControls`' buttons should have a round shape but a rounded-square shape when `highContrast` skin variant is applied.
Made `MediaControls` skinnable.
WRP-7056
=> WRP-7056: Fix `MediaControls` to show round buttons correctly in high-contrast mode

samples/sampler/stories/qa/Touchable.js
PR enactjs/enact#3114 on enact repo "WRP-6259:ui:Touchable: add scale payload to pinch event doc" changes the names of pinchConfig.min/maxZoom to min/maxScale. So this fix is the follow-up.
change the use of min/maxZoom to min/maxScale
WRP-6259
enactjs/enact#3114
Enact-DCO-1.0-Signed-off-by: Hoeun Ryu <hoeun.ryu@lge.com>
=> WRP-6259:qa-sampler:Touchable: change min/maxZoom to min/maxScale

.travis.yml, internal/DateTime/tests/DateTimeDecorator-specs.js, samples/sampler/stories/qa/Slider.js
Enact-DCO-1.0-Signed-off-by: Alexandru Morariu alexandru.morariu@lgepartner.com
Removed unused property from unit test and applied suggested fix for qa story.
WRP-6651
=> WRP-6651: Fixed lint warnings in sandstone.

DatePicker/tests/DatePicker-specs.js, TimePicker/tests/TimePicker-specs.js, internal/DateTime/DateTimeDecorator.js
DatePicker and TimePicker's `onComplete` event payload does not have 'value' property due to a typo.
Fix typo of `onComplete` event payload.
WRP-8540
=> WRP-8540: Fix typo of `onComplete` event payload of DatePicker and TimePicker

DayPicker/tests/DayPicker-specs.js
Unit Test failed in enact-cli-test of jenkins.
The unit test failed right after the `selected` prop unit test that receives the number type as a parameter. Looking at the failure log, the unit test was run on es-ES, not en-US.
Here is a snippet of jenkins console failure output:
FAIL DayPicker/tests/DayPicker-specs.js
DayPicker › should emit an onSelect event with 'onSelect' type when selecting days
expect(jest.fn()).toHaveBeenCalledWith(...expected)
- Expected
+ Received
Object {
-   "content": "Mon",
+   "content": "lun",
"selected": Array [
1,
],
"type": "onSelect",
},
Number of calls: 1
48 | 		userEvent.click(item);
49 |
> 50 | 		expect(handleSelect).toHaveBeenCalledWith({content: 'Mon', selected: [1], type: …
=> WRP-6648:DayPicker: Fixed unit test failure from cli testing on Jenkins

useScroll/useScroll.js
`scrollContainerHandle` has a initial object having several properties, but its `current` object is replaced by `setScrollContainerHandle` in the first rendering cycle. So, it looks better to make the initial object empty for better understanding in later visits.
Make the initial object empty, then add comments about properties that should be inside `scrollContainerHandle`.
I found that `scrollPos` does …
=> WRP-5951: Refine `scrollContainerHandle` of `useScroll` to be clearly understandable

Button/Button.js, Button/Button.module.less, CHANGELOG.md, samples/sampler/stories/default/Button.js, samples/sampler/stories/qa/Button.js, tests/screenshot/apps/components/Button.js
As a result of a discussion with the GUI team, it was decided to provide a boolean prop to have both the left and right sides of the button completely round. Therefore, a `roundBorder` boolean prop is added to achieve that.
Use
- `--button-height: $height`
- `border-radius: calc(--button-height / 2)`.
Use CSS custom property `--button-height` and LESS property as variable `$height`. CSS custom property `--button-height` is overridden wherever CSS property `height` is defined.
[//]: # (Were any side-effects caused by …
=> WRP-8078:Button: Add roundBorder prop making both sides of button fully round

.travis.yml
There is a difference between 'npm install gitbranch' and 'git clone gitbranch' -> 'npm install'.
Need to use the git clone method to follow the already tested npm-shrinkwrap.json during travis build.
Update .travis.yml to download the cli source code with git clone and then run 'npm install' and 'npm link' in the cli directory. 
WRP-9221
=> WRP-9221: Update .travis.yml to change the CLI downloading method

TimePicker/tests/TimePicker-specs.js, package-lock.json, package.json, samples/sampler/package.json
Unit test fails occur on Enact Frameworks(sandstone, moonstone, agate)
Reason: 
Since [ilib v14.17.0](https://github.com/iLib-js/iLib/releases/tag/v14.17.0), the whitespace in locale value has been changed to prevent ui issues.
This is an intended action so the changed whitespace should be applied to the test scripts in the enact framework.
- Update ilib v14.17.0
- Fix unit test errors: remove the normalize option in `getByText` function to support the changed whitespace
(https://testing-library.com/docs/queries/about/#normalization)
[//]: # (Are there any …
=> WRP-10590: Update ilib v14.17.0 and fix unit test errors

.travis.yml, Button/Button.js, Button/Button.module.less, Button/tests/Button-specs.js, CHANGELOG.md, Panels/Header.js, Panels/Header.module.less, Panels/tests/Header-specs.js, internal/DateTime/tests/DateTimeDecorator-specs.js, samples/sampler/stories/default/Button.js, samples/sampler/stories/default/Header.js, samples/sampler/stories/qa/Slider.js, styles/colors.less, tests/screenshot/apps/components/Button.js, tests/screenshot/apps/components/Header.js
Add prop to enable shadow effects on icons and text in ```Panels.Header```.
Use text-shadow CSS property to add shadow to text.
The UX guide only mentioned close button. But for consistency, I also applied a shadow effect to the back button (In Panels/Header.js, line 462).
WRP-4228
=> WRP-4228: Add `shadowed` prop to `Panels.Header` and `Button`

tests/screenshot/apps/components/Layout.js
Reverts enactjs/sandstone#1417
This PR also need to reverted as https://github.com/enactjs/enact/pull/3128 reverted.
=> Revert "WRP-6257: Layout: Added screenshot tests for `grow` prop of `Cell`"

TransferList/CustomDragImage.js, TransferList/TransferList.js
Refactored the code by creating a new component called CustomDragImage and moving all the functionality related to DragImage into this component.
We're now using a custom component to generate the DragImage.
WRP-11626
Enact-DCO-1.0-Signed-off-by: Andrei Tirla andrei.tirla@lgepartner.com
=> WRP-11626: Move custom drag image into own component

tests/screenshot/apps/components/Layout.js
A follow-up PR to add qa-sampler and screenshot tests for `grow` prop in `Cell` (enactjs/enact#3138)
This PR is reopened (#1417) to fix a screenshot test failing on Item component in sandstone.
- ~~Added qa-sampler for `Layout`~~
- Added screenshot tests
~~qa-sampler~~
~~- One Column and Nested three Rows with a total of 9 Cells to control them at once.~~
~~- Three Cells in a Layout to control them individually.~~
~~In principle, this should be added to enact, but since enact does not have qa-sampler, it is added to sandstone instead.~~
screenshot tests
* Row
- Simply set the `grow` prop to check if each …
=> WRP-6257:Layout: add screenshot tests for `grow` prop

CHANGELOG.md, WizardPanels/useFocusOnTransition.js
Until 2.5.8, the focus always exists on the screen in 5-way mode when the next/prev button of the WizardPanels sample is selected. From 2.6.0, focus disappears when moving from view 3 to view 4 via the next button and from view 2 to view 1 via the prev button.
This behavior is observed on PC, and the ui-test on the local machine may fail. The failed test case is described as "should select buttons over header - [QWTC-2390]" in WizardPanels specs. Note that we have yet to get this issue on TV and Jenkins tests.
This problem is observed in Chrome version 104 or higher but not in Chrome version 103 or lower.
The observed problems are as follows: Spotlight refocuses on the item previously focused on in the previous …
=> WRP-10826: Fix `WizardPanels` to restore focus properly after a transition

TransferList/CustomDragImage.js, TransferList/TransferList.js
When an item is selected we want to move that item within its original list by using keyboard.
Added functionality to reorder items in the same list by keyboard selection. Only 1 item can be moved at a time.
WRP-11620
=> WRP-11620: Rearrange list by keyboard selection

CHANGELOG.md, tests/ui/specs/Scroller/EditableScroller/Scroller-QWTC-569-specs.js, tests/ui/specs/TabLayout/VerticalTabsWithoutIcons/VerticalTabsWithoutIcons-specs.js, tests/ui/specs/VirtualList/VirtualList/WithMultipleSpottables/VirtualList-QWTC-11715-specs.js, tests/ui/specs/VirtualList/VirtualList/WithMultipleSpottables/VirtualList-QWTC-2260-specs.js, useScroll/useScroll.js
When a page up/down key is pressed on items in a scroller or a list, an expected behavior is to scroll a page and focus an item at the same visual position normally.
And, if page up is pressed at the first page or page down is pressed at the last page, an expected behavior is to scroll to the edge then focus the first (for page up) or the last (for page down) item.
The reported issue is that, the focus disappears on page down key at the last page when the last item is spotlight container that has a spottable node not attached to the bottom of the item.
`useScroll` has a logic to find an item to focus and it …
=> WRP-12378: Fixed `Scroller` and `VirtualList` to focus Spottable container items properly via page up/down

CHANGELOG.md, tests/ui/specs/Scroller/EditableScroller/Scroller-QWTC-569-specs.js, tests/ui/specs/VirtualList/VirtualList/WithMultipleSpottables/VirtualList-QWTC-11715-specs.js, tests/ui/specs/VirtualList/VirtualList/WithMultipleSpottables/VirtualList-QWTC-2260-specs.js, useScroll/useScroll.js
When a page up/down key is pressed on items in a scroller or a list, an expected behavior is to scroll a page and focus an item at the same visual position normally.
And, if page up is pressed at the first page or page down is pressed at the last page, an expected behavior is to scroll to the edge then focus the first (for page up) or the last (for page down) item.
The reported issue is that, the focus disappears on page down key at the last page when the last item is spotlight container that has a spottable node not attached to the bottom of the item.
`useScroll` has a logic to find an item to focus and it …
=> WRP-12378: Fixed Scroller and VirtualList to focus Spottable container items properly via page up/down

Alert/Alert.js, CHANGELOG.md
`sandstone/Alert` alignment of text content to be left for fullscreen type.
Changed alignment to be left.
WRP-12301
=> WRP-12301: Changed `Alert` alignment of text content to be left for fullscreen type

CHANGELOG.md, internal/Picker/Picker.js
`type: "onChange"` is missing in the object passed when `onChange` is called.
Add `type: "onChange"` in the event object.
`type: "onChange"` must be included in the sampler output in the Actions tab when clicking next or prev buttons.
WRP-11047
Enact-DCO-1.0-Signed-off-by: Hoeun Ryu <hoeun.ryu@lge.com>
=> WRP-11047:Picker: add `type` property to `onChange` event object

ThemeDecorator/screenTypes.json
Need to support WQHD(3440*1440) screen type.
Add WQHD screen type to ThemeDecorator/screenTypes.json
WRP-7784
=> WRP-7784: Add WQHD screen type to screenTypes.json

TransferList/TransferList.js, samples/sampler/stories/default/TransferList.js
Replace 'noMultipleDrag' prop with 'noMultipleSelect' and modify the behaviour to disallow selecting multiple items while 'noMultipleSelect' prop is true.
If an item is already selected while the 'noMultipleSelect' prop is true, selecting a new item should automatically deselect the previously selected one.
WRP-12759
Enact-DCO-1.0-Signed-off-by: Andrei Tirla andrei.tirla@lgepartner.com
=> WRP-12759:  Replace `noMultipleDrag` with `noMultipleSelect` and enhance functionality

Button/Button.js, Checkbox/Checkbox.js, CheckboxItem/CheckboxItem.js, FlexiblePopupPanels/Panel.js, FormCheckboxItem/FormCheckboxItem.js, Icon/Icon.js, ImageItem/ImageItem.js, Input/InputFieldDecoratorIcon.js, Picker/Picker.js, Popup/Popup.js, RangePicker/RangePicker.js, Sprite/Sprite.js, TabLayout/Tab.js, TimePicker/TimePicker.js, TooltipDecorator/Tooltip.js, TooltipDecorator/TooltipDecorator.js, VideoPlayer/VideoPlayer.js, WizardPanels/Panel.js, internal/Picker/Picker.js
There are broken links that refer to other `prop`s in the documentation.
Broken links
- https://enactjs.com/docs/modules/sandstone/Checkbox/#CheckboxBase.children
- https://enactjs.com/docs/modules/sandstone/CheckboxItem/#CheckboxItemBase.icon
- https://enactjs.com/docs/modules/sandstone/CheckboxItem/#CheckboxItemBase.indeterminateIcon
- https://enactjs.com/docs/modules/sandstone/FlexiblePopupPanels/#Panel.nextButton
- https://enactjs.com/docs/modules/sandstone/FlexiblePopupPanels/#Panel.prevButton
- https://enactjs.com/docs/modules/sandstone/FormCheckboxItem/#FormCheckboxItemBase.icon
- https://enactjs.com/docs/modules/sandstone/FormCheckboxItem/#FormCheckboxItemBase.indeterminateIcon
- …
=> WRP-11279: Fix broken links referencing other props in documentation

MediaPlayer/MediaSliderDecorator.js
`VideoPlayer` does not read out 'time' when the focus is moving on a slider.
The root cause is a missing adapter function for `forwardCustom` when a internal module passes 'time' information for `VideoPlayer`.
To fix this issue, I added an adapter function.
No changelog as this bug occurs after the latest release.
WRP-13634
=> WRP-13634: Fixed `VideoPlayer` to read out 'time' on a slider

samples/sampler/stories/default/VideoPlayer.js
There was a UX requirement to enable hoverToScroll in bottomComponents of videoPlayer.
In sampler (VideoPlayer), when we click the more button, virtualList appears. Make virtualList be able to scroll by hovering both edge sides.
WRP-13858
Enact-DCO-1.0-Signed-off-by: Hoeun Ryu <hoeun.ryu@lge.com>
=> WRP-13858:Sampler: add hoverToScroll in bottomComponents of VideoPlayer

TooltipDecorator/tests/useTooltip-specs.js
As for the following PR for #1401, we'd like to add unit tests for useTooltip component which was missing.
Add unit tests for useTooltip.
The below unit tests are derived from TooltipDecorator-specs.js, and two more unit tests (+) are added to increase code covarage.
Unit Tests
- render a tooltip if hovered
- hide tooltip if not hovered
- (+) hide tooltip if not hovered (disabled)
- (+) render a tooltip if keydown
- render a tooltip if hovered for 'tooltipRelative'
- Tooltip position
- tooltipPosition is set to 'above'
- tooltipPosition is set to 'below'
- tooltipPosition is set to 'left middle'
- …
=> WRP-12385:TooltipDecorator: add unit-test for useTooltip

TransferList/TransferList.js
TransferList uses the drag and drop API which does not work on webOS TV. We need to adapt it to work on webOS by using touch events. 
Added touch events for TransferList to work on webOS.
WRP-14783
Enact-DCO-1.0-Signed-off-by: Stanca Pop (stanca.pop@lgepartner.com)
=> WRP-14783: Apply touch events on TransferList

CHANGELOG.md, WizardPanels/WizardPanels.js, WizardPanels/tests/WizardPanels-specs.js
Even when WizardPanels passes value using the `current` prop, `aria-label` always reads "step 1".
Depending on the value of the passed `current` prop, the value of `aria-label` is read correctly as `step ${current}`.
Please check the commit message for more details. [4ce0d6a9](https://github.com/enactjs/sandstone/commit/4ce0d6a94713bd526c35c7e5cdb8bd938cd9cd54)
All unit tests must pass for `WizardPanels/tests/`
`npm run test WizardPanels/tests/`
[//]: # (Related …
=> WRP-14562:WizardPanels: fix audio guidance for step when using `current`

.travis.yml, CHANGELOG.md, VideoPlayer/VideoPlayer.js
- The wheel event listener removed due to UX changes in WRP-852
So the screen automatically disappears after a certain period of time even when the wheel is operated with more component.
- After cli 6.0.0 version, @testing-library/user-event version 14 or higher must be entered and the unit test code must be updated. However, since this branch is for TV MR in 2023, .travis.yml needs to be modified so that the cli is fixed to 5.1.3 and the referenced enact branch is also fixed to the branch for TV MR in 2023.
- Revert the deletion of the wheel event listener so that only the auto close time is extended while …
=> WRP-15824: Fixed to keep showing media controls while the user is wheeling in VideoPlayer

TransferList/TransferList.js
Enact-DCO-1.0-Signed-off-by: Alexandru Morariu alexandru.morariu@lgepartner.com
When transfering items on PC, sometimes there are 2 drop indicators (one above and one below the drop position) The actual drop position is below. The drop indicator should always show the actual drop position.
Now the item is dropped where the indicator is instead of dropping the item always below.
WRP-15621
=> WRP-15621: Fix drop position line on PC.

.travis.yml, useScroll/useScroll.js
`scrollContainerHandle` has a initial object having several properties, but its `current` object is replaced by `setScrollContainerHandle` in the first rendering cycle. So, it looks better to make the initial object empty for better understanding in later visits.
Make the initial object empty, then add comments about properties that should be inside `scrollContainerHandle`.
(Cherry-pick #1396)
WRP-5951
WRP-16065 …
=> WRP-16065: Refine `scrollContainerHandle` of `useScroll` to be clearly understandable

CHANGELOG.md, Scroller/EditableWrapper.js, samples/sampler/stories/qa/IconItem.js, samples/sampler/stories/qa/IconItem.module.less, samples/sampler/stories/qa/Scroller.js, samples/sampler/stories/qa/Scroller.module.less
Add hiding/showing element feature when scroller is in edit mode(when `editable` is given)
- Item will be selected by single tap/click
- The selected item can be hidden and also hidden items can be shown
- Added `longPresMode` feature to `editable` object, allowing long-press or single tap to select an item.
- Fixed a bug where removing a selected item while moving was not working properly.
- Added qa-sampler 
WRP-15428
=> WRP-15428: Add hiding element feature to EditableScroller

samples/sampler/package.json
When you initialize a storybook, the module related to the storybook is automatically installed in devDependencies.
(https://storybook.js.org/docs/react/get-started/install , in simply, $ npx storybook@latest init)
There was no reason to be managed as devDependencies even if you checked related documents or developer sites, and it is right to move to dependencies because the sampler directory itself aims to create samplers through storybooks.
Move storybook-related modules from devDependencies to dependencies
[//]: # …
=> WRP-11048: Move storybook-related modules from devDependencies to dependencies

CHANGELOG.md, Scroller/EditableWrapper.js, samples/sampler/stories/qa/IconItem.js, samples/sampler/stories/qa/IconItem.module.less, samples/sampler/stories/qa/Scroller.js, samples/sampler/stories/qa/Scroller.module.less
In this PR, I fixed 2 issues related to `scroller/EditableWrapper`
1) Fix `scroller/EditableWrapper` to release selectedItem when focus leaves the scroll container.
: When an item is selected in the editable scroller and the focus leaves the scroll container(e.g., by key handling), the selected item remains selected even if the focus moves back into the scroll container. 
-> It is fixed to release selectedItem when the focus leaves the scroll container. 
2) Fix `scroller/EditableWrapper` centeredOffset to calculate properly.
: When deleting an item after scrolling, centeredOffset was miscalculated. 
3) Fix `scroller/EditableWrapper` not to move items …
=> WRP-17258: Fix `scroller/EditableWrapper` to release selectedItem when focus leaves scroll container

CHANGELOG.md, QuickGuidePanels/QuickGuidePanels.js, WizardPanels/WizardPanels.js, WizardPanels/tests/WizardPanels-specs.js, samples/sampler/stories/default/QuickGuidePanels.js
`onClose` event handler prop is missing for `QuickGuidePanels`.
Added `onClose` prop
Note that aria label is not defined yet, so it should be updated later.
A unit test is added.
WRP-19408
=> WRP-19408: Added `QuickGuidePanels` prop `onClose`

CHANGELOG.md, WizardPanels/WizardPanels.module.less, styles/variables.less, tests/screenshot/apps/components/QuickGuidePanels.js
A close buton of `QuickGuidePanels` is always right-side even in RTL locales.
Fixed a close button's position in RTL locales.
WRP-19469
=> WRP-19469: Fixed `QuickGuidePanels` to update a close button position properly in RTL locales

CHANGELOG.md, samples/sampler/stories/qa/VirtualGridList.js, tests/ui/specs/VirtualList/VirtualGridList/qa-VirtualGridList/VirtualGridList-QWTC-2296-specs.js, useScroll/Scrollbar.js, useScroll/Scrollbar.module.less
Scrolling by `hoverToScroll` stops if *ALL* conditions below meet,
- A scroller or list (inner scroller) exists inside another scroller (outer scroller) that has a orthogonal scroll direction to the inner scroller.
- The inner scroller has `hoverToScroll` prop.
- The outer scroller has a (always either during-scroll) visible scrollbar.
- A user moves the pointer on a cross-area of "hoverToScroll" area of the inner scroller and "scrollbar" area of the outer scroller.
This pull request is to make the outer scroller scrolling properly in the situation described above.
The cause is that "scrollbar" DOM of the …
=> WRP-20570: `hoverToScroll` works properly inside another scroller

CHANGELOG.md, VirtualList/useThemeVirtualList.js, useScroll/useEvent.js
When scrolling a list by wheeling when `snapToCenter` is given, scaling effect is applied to not the centered item but a outside DOM if the outside DOM has a specific 'data-index' attribute.
Fixed to find right DOM node to apply the scaling effect
WRP-21338
=> WRP-21338: Fixed `VirtualGridList` to not apply a scale effect to outside DOM when `snapToCenter` is given

CHANGELOG.md, VirtualList/useEvent.js, samples/sampler/stories/qa/VirtualGridList.js
Focus moving by holding 5-way key is blocked when it needs to across Spotlight container. To make it working, a developer can configure option [`continue5WayHold`](https://enactjs.com/docs/modules/spotlight/SpotlightContainerDecorator/#SpotlightContainerDecorator.defaultConfig.continue5WayHold) of spotlight/SpotlightContainerDecorator. In virtual lists, this config option does not work.
Fixed `sandstone/VirtualList` to move focus properly by 5-way directional key hold when `spotlight/SpotlightContainerDecorator` config option `continue5WayHold` is set.
[//]: # (Are …
=> WRP-21706: Fixed `sandstone/VirtualList` to move focus properly by 5-way directional key hold

CHANGELOG.md, Scroller/EditableWrapper.js
An updated UX requires to exit 'selecting' state when 'back' key is pressed just as 'ok' key is pressed.
Added behavior for 'back' key so that selection mode is finished with saving editing.
WRP-22023
=> WRP-22023: Support 'back' key to escape selection mode in EditableScroller

CHANGELOG.md, Scroller/EditableWrapper.js, samples/sampler/stories/qa/IconItem.js
* [] At least one test case is included for this feature or bug fix
Enable the editable scroller to start with the selected item when initial item info is given in the `editable` prop
If editable.initialSelected is given, call startEditing() function to make the initial item selected
Implement qa-sampler of IconItem to start the edit mode of the scroller by long pressing item in the scroller
[//]: # …
=> WRP-21680: Add initialSelected prop in `editable` prop  of scroller

Scroller/EditableWrapper.js, samples/sampler/stories/qa/IconItem.module.less
Apps need to show or hide arrow indicator for moveable direction.
Updated `EditableScroller` to add or remove 'noBefore' and/or 'noAfter' class names so that apps can use to display arrows.
WRP-21684
=> WRP-21684: Support apps to show arrow only for moveable direction

Scroller/EditableWrapper.js, samples/sampler/stories/qa/IconItem.js, samples/sampler/stories/qa/Scroller.js
Need to update A11y feature of the editable scroller as the previous version can only support delete motion
Specs:
- When focus items in Scroller in normal mode (It is implemented in the sampler. It should be implemented on App)
item label + <"Edit mode to press and hold OK key">
- When focus items in Scroller in edit mode
item label + <"Press OK key to move or press up key for other actions">
[//]: # …
=> WRP-20670: Support A11y for Editable scroller according to the latest UX

CHANGELOG.md, WizardPanels/WizardPanels.js, WizardPanels/WizardPanels.module.less, tests/screenshot/apps/components/QuickGuidePanels.js
When the last view of QuickGuidePanels is displayed, focus disappear.
Fix QuickGuidePanels not to lose focus when the last view is displayed.
WRP-21913
=> WRP-21913: Fix QuickGuidePanels to not lose focus when the last view is displayed

CHANGELOG.md, tests/ui/apps/Dropdown/Dropdown-View.js, tests/ui/specs/Dropdown/Dropdown-specs.js, useScroll/useScroll.js
Focus disappears on the first options and the last options when pressing page up/down on Dropdown that has more than 5 options.
The issue occurs after #1437. The cause is that a logic uses DOM node rather than Spotlight container ID to find Spotlight target after scrolling from the same position as before scrolling. To avoid issue of #1437, I updated the logic to use Spotlight container ID of the same DOM node the logic used instead of revert the PR.
UI tests are …
=> WRP-22553: Fix Dropdown to focus properly the first option and the last option via page up and page down

Scroller/EditableWrapper.js, samples/sampler/stories/qa/IconItem.js
Some a11y phrase of editable scroller updated.
Added phrase:
`Press OK button to move or press up button for other actions`
`Press left or right button to move or press up button for other actions`
WRP-20670
=> WRP-20670: Update phrase of editable scroller a11y

CHANGELOG.md, TabLayout/TabLayout.js, TabLayout/tests/TabLayout-specs.js, tests/ui/specs/TabLayout/TabLayout-specs.js, tests/ui/specs/TabLayout/VerticalTabsWithIcons/VerticalTabsWithIcons-specs.js
Change enter key behavior of TabLayout
Move focus to the element of the tab content via 5-way enter key in the tab menu.
WRP-21312
=> WRP-21312: change enter key behavior to match the latest UX

CHANGELOG.md, WizardPanels/WizardPanels.js, samples/sampler/stories/default/QuickGuidePanels.js
Need to support A11y feature for sandstone/QuickGuidePanels
- When entering the panel, read out the step number and read out which button is focused
WRP-23234
=> WRP-23234: Add a11y feature for sandstone/QuickGuidePanels 

CHANGELOG.md, Scroller/EditableWrapper.js, tests/ui/apps/Scroller/EditableScrollerWithIconItem/EditableScrollerWithIconItem-View.js, tests/ui/apps/Scroller/EditableScrollerWithIconItem/EditableScrollerWithIconItem.module.less, tests/ui/specs/Scroller/EditableScrollerWithIconItem/EditableScroller-utils.js, tests/ui/specs/Scroller/EditableScrollerWithIconItem/EditableScrollerWithIconItem-specs.js, tests/ui/specs/Scroller/EditableScrollerWithIconItem/EditableScrollerWithIconItemPage.js
All items show up if a user quit edit mode after hiding all items.
Fix a logic to handle all-hidden cases.
WRP-24596
=> WRP-24596: Fix EditableScroller to allow hiding all items

CHANGELOG.md, Scroller/EditableWrapper.js
The spotlight focus disappears when a user press cancel key during one item is selected for moving in `EditableScroller` that is inside `Panels`.
The issue occurs `onBack` occurs to `Panels` on cancel key press because `Panels`'s event is based on 'keyup' and `EditableScroller`'s event is based on 'keydown'. To fix UX issue, `EditableScroller` is updated to use 'keyup'.
WRP-24016
Enact-DCO-1.0-Signed-off-by: Seungcheon Baek …
=> WRP-24016: Fixed unexpected focus lose when 'cancel' key is pressed

CHANGELOG.md, WizardPanels/WizardPanels.js, WizardPanels/tests/WizardPanels-specs.js, tests/ui/apps/QuickGuidePanels/QuickGuidePanels-View.js, tests/ui/specs/QuickGuidePanels/QuickGuidePanels-specs.js, tests/ui/specs/QuickGuidePanels/QuickGuidePanelsPage.js
When a user selects the previous button on QuickGuidePanels, the focus is on the next button that is the default focus target.
Updated logic to focus the last focused button.
WRP-25233
=> WRP-25233: Fix QuickGuidePanels to focus the last focused button

ColorPicker/ColorPicker.js, samples/sampler/stories/qa/ColorPicker.js
Added noAnimation prop to sandstone/colorPicker
Passed noAnimation prop to Popup inside sandstone/colorPicker
WRP-26288
Enact-DCO-1.0-Signed-off-by: Daniel Stoian ([daniel.stoian@lgepartner.com](mailto:daniel.stoian@lgepartner.com))
=> WRP-26288: Passed noAnimation prop to Popup inside sandstone/colorPicker

samples/qa-a11y/src/views/ReadAlert.js
`PalmServiceBridge` was renamed as `WebOSServiceBridge` in 2018 with an fallback alias for compatibility on legacy webOS.
Updated qa-a11y sample to use `WebOSServiceBridge`
WRP-26268
=> WRP-26268: Rename PalmServiceBridge as WebOSServiceBridge

CHANGELOG.md, Panels/Header.js, samples/sampler/stories/default/Panels.js
When `Panels.Header` is rendered for the first time with `centered` prop, `slotAfter` elements are rendered at unexpected position and they are positioned correctly right after.
To layout `title`, `slotBefore`, and `slotAfter` correctly with the centered title, `slotBefore` and `slotAfter` elements' widths should be measured after rendered. So, `Panels.Header` renders once for measuring and re-renders for the right layout.
In this PR, the logic is changed to hide slots during the inevitable first render for measuring, then to recover slots to show.
[//]: # (Are …
=> WRP-27297: `Panels.Header` to not show `slotAfter` in incorrect position at the first rendering when `centered` is given

TabLayout/TabLayout.js
When the enter key is pressed in the PopupTabLayout menu, the subPanel needs to be changed immediately and moves focus to the sub panel.
Move Spotlight.move() logic to the keyUp handler in TabLayout to move the spotlight to the subPanel after subPanel view is changed
WRP-26238
=> WRP-26238: Fix TabLayout to handle focus properly after pressing enter key

CHANGELOG.md, Scroller/EditableWrapper.js, samples/sampler/stories/qa/IconItem.js, samples/sampler/stories/qa/Panels.js, samples/sampler/stories/qa/Panels.module.less, tests/ui/apps/Scroller/EditableScrollerWithIconItem/EditableScrollerWithIconItem-View.js
Fix the editable scroller a11y feature to not cut off panel's audio guidance
Audio guide statement updated according to the latest UX
Remove announce() which is used in the focus handler in the editable scroller 
Fix audioGuide to be read with aria-label of iconItem when the iconItem is focused
WRP-26318
=> WRP-26318: Fix editable scroller a11y feature to not cut off panel's audio guidance

TabLayout/TabLayout.js, tests/ui/specs/TabLayout/VerticalTabsWithIcons/VerticalTabsWithIcons-specs.js
In https://github.com/enactjs/sandstone/pull/1495, the back key behavior in TabLayout is implemented.
The focus moves to the tab area when the back key is pressed from the tabLayout content.
However, in cursor mode, this back key behavior needs to be ignored.
Check if it is pointer mode by using spotlight.getPointerMode().
WRP-27786
=> WRP-27786: Fix `TabLayout` to ignore back key behavior in cursor mode

CHANGELOG.md, Scroller/EditableWrapper.js
`Scroller` could make a script error on run-time if `editable` prop has an abnormal `initialSelected` value.
Added a guard code to prevent logic from a script error.
WRP-27860
=> WRP-27860: Fix `EditableScroller` to check validity of initial selected item info

CHANGELOG.md, TabLayout/TabLayout.js, TabLayout/tests/TabLayout-specs.js, samples/sampler/stories/default/PopupTabLayout.js, tests/ui/specs/TabLayout/VerticalTabsWithIcons/VerticalTabsWithIcons-specs.js
In https://github.com/enactjs/sandstone/pull/1495, we implemented the back key behavior of TabLayout that moves focus from content to the tab menu(area). However, this behavior causes side effects. We decided to revert back key behavior of TabLayout.
Revert https://github.com/enactjs/sandstone/pull/1495, https://github.com/enactjs/sandstone/pull/1505 changes
WRP-28759
=> Revert back key behavior of TabLayout that moves focus from tab content to tab menu (#1495, #1505)

.travis.yml, samples/sampler/.storybook/preview.js
The cookie banner appears first when running an automation test, which prevents the test from proceeding properly.
So the cookie banner and GA needs to be modified so that it can only be applied when the sandstone sampler is deployed on enactjs.com
Apply GA and cookie banner only when there is a relevant environment variable.
The environment variable name required the prefixed with STORYBOOK_
(https://storybook.js.org/docs/6.5/react/configure/environment-variables) …
=> WRQ-456: Apply GA and cookie banner only when there is a relevant environment variable

CHANGELOG.md, TabLayout/TabLayout.js, TabLayout/tests/TabLayout-specs.js, tests/ui/specs/TabLayout/VerticalTabsWithIcons/VerticalTabsWithIcons-specs.js
When the back key is pressed from the TabLayout content and the `disableBackKeyNavigation` prop is false, the focus should move to the tab menu
Revert #1511 to add back key behavior of TabLayout which enables navigate focus from tab contents to tab menu
Add private prop `disableBackKeyNavigation`
WRQ-1306
=> WRQ-1306: Change back key behavior on TabLayout to navigate focus from tab contents to tab menu

CHANGELOG.md, Scroller/EditableWrapper.js, tests/ui/specs/Scroller/WithEditableSelectItemByPress/ScrollerWithEditableSelectItemByPress-specs.js
A new UX requirement that `Scroller` should complete editing by 'down' key just like by 'enter' key when `editable` is given.
Updated Scroller/EditableWrapper is updated to support 'down' key.
WRQ-155
=> WRQ-155: Update `Scroller` to complete editing by 'down' key when `editable` is given

CHANGELOG.md, Scroller/EditableWrapper.js
In all conditions below met, focus is moving out of an editable scroller but editing mode is not completed and a selected item is kept selected;
- The editable scroller is editing mode
- An item is selected
- Pointer mode
- No item or buttons are focused by pointer
- A user press 'enter' ('OK')
Fixed an editable scroller logic to complete editing when the condition is detected.
WRQ-3732
=> WRQ-3732: Fixed Scroller with editable prop to complete editing when focus is leaving by 5-way key on pointer mode

CHANGELOG.md, Dropdown/Dropdown.js, Dropdown/DropdownList.js
Update audio guidance of Dropdown component
- When dropdown list is opened, read out `Dropdown list opened`
- When dropdown button is focused, read out `Dropdown` after the contents
Updated aria-label in Dropdown
Updated DropdownList to use aria-labelledby to read only when the focus is entered into the list
WRQ-1308
=> WRQ-1308: Update audio guidance of Dropdown component

CHANGELOG.md, Slider/SliderBehaviorDecorator.js, Slider/tests/Slider-specs.js, WizardPanels/WizardPanels.js, WizardPanels/tests/WizardPanels-specs.js
Update audio guidance of Slider component
- When focusing on the thumb, read out `From {startValue} to {lastValue} {value} Change a value with up down button` or `From {startValue} to {lastValue} {value} Change a value with left right button`
Update aria-valuetext of the Slider component
The aria-label of WizardPanels is updated to $L('Exit Quick Guide') in this PR because the UX guide is updated.
WRQ-4089
=> WRQ-4089: Update audio guidance of Slider component

CHANGELOG.md, TabLayout/RefocusDecorator.js, TabLayout/TabGroup.js, TabLayout/tests/TabGroup-specs.js, samples/qa-a11y/src/views/TabLayout.js
Update audio guidance of TabLayout component
- When the focus is entered into the tabList, read out `{total} items in total {tabname} tab {selectedValue} of {total}`
- When the focus is moved to the other tab, read out `tab {selectedValue} of {total}` after reading the tab name
Update role prop in TabGroup component
Update TabGroup to use aria-labelledby to read only when the focus is entered into the list
WRQ-1307
=> WRQ-1307: Update audio guidance of TabLayout component 

CHANGELOG.md, Scroller/EditableWrapper.js
When a user moves a pointer left and right very fast while editing the order of items, sometimes the order of items is broken so that some items look duplicated.
The condition to make a bug happen;
- Select one item to move.
- Move the selected item very fast to one direction so that mousemove event occurs one across multiple items
- Move the selected item very fast to the opposite direction so that mousemove event occurs one across multiple items
The cause of this unexpected behavior is a bug of our logic to check how many items should be rearranged while the selected item is moving back and forth. So, I …
=> WRQ-2636: Fixed Scroller with editable to rearrange items properly when moving pointer very fast

TabLayout/TabLayout.js, TabLayout/tests/TabLayout-specs.js
Fix unknown prop warning in TabLayout
Delete `disableBackKeyNavigation` prop in render 
Add unit test case which has `disableBackKeyNavigation` prop
WRQ-7338
=> WRQ-7338: Fix unknown prop warning in TabLayout

Scroller/EditableWrapper.js
Implement move/hide/remove items in the editable scroller via touch 
Add touchmove, touchend, dragstart event handler to handle items via touch
Selected items can be moved by dragging the mouse
I think hoverToScroll feature in touch mode needs to be updated
When buttons above the item are touched, it does not highlighted
WRQ-202
=> WRQ-202: Implement editing items in touch mode

Panels/Header.js
Panel/Header.marqueeOn's default value is 'render' but 'hover' in JSDoc comment.
Updated JSDoc comment.
WRQ-7944
=> WRQ-7944: Update docs for the default value of Panels/Header.marqueeOn

CHANGELOG.md, VirtualList/useThemeVirtualList.js, tests/ui/specs/VirtualList/VirtualGridList/VirtualGridListPage.js, tests/ui/specs/VirtualList/VirtualGridList/With5-way/VirtualGridList-QWTC-13709-specs.js
In a vertical virtual grid list, scroll position for a focused item could be incorrect by 5-way navigation when the scrolling area (client height) is larger than the item height but is smaller than the item height with affordance.
The case was a sort of gray area in a viewpoint of position calculation. Normally layout is based on the item size, but the scroll position is counting also affordance. This condition makes a negative offset on calculation so that an item's top part is cut off.
The intention of the internal calculation allows only 0 or positive offset, so fixed this issue by limiting any negative …
=> WRQ-171: Fix `VirtualList` to have proper scroll position when item with affordance is larger than scroll area

samples/qa-a11y/src/views/VideoPlayer.js, samples/sampler/stories/default/MediaOverlay.js, samples/sampler/stories/default/VideoPlayer.js, samples/sampler/stories/qa/VideoPlayer.js
Video player does not loads 'big buck bunny' video. We need to be able to play url of video.
- Modify big buck bunny video url in samples.
WRQ-7951
'Big Buck Bunny' is changed to 'Cosmos Laundromat' as we can't find any available links for 'Big Buck Bunny' video.
=> WRQ-7951: Modify big buck bunny video url.

CHANGELOG.md, Scroller/EditableWrapper.js
In the editable scroller, when an item is selected and the pointer hovers next item and then completes editing mode with 4-way key, the focus needs to remain with the selected item.
Manually focus on selected item
WRQ-8636
=> WRQ-8636: Fix editable scroller to remain focus in selected item when editing complete with 4-way key in pointer mode

CHANGELOG.md, Scroller/tests/Scroller-specs.js, Scroller/useThemeScroller.js
When a user press back key on a scroll thumb of a scroller with focusableScrollbar that is rendered inside FixedPopupPanels, Scroller moves focus to the scroll body and FixedPopupPanels forwards 'onBack' event to app at the same time. So, the app changes a view to show up another panel. After all, a user feels the scroll body is flashing.
Moving focus to the scroll body is essential in a11y support to read out its contents. Also, there should be a chance to focus the scroll body if there are spottable elements inside the body. To accomplish this goal, 'onBack' event derived from keyup needs to be prevented …
=> WRQ-7224: Fixed `Scroller` to stop propagation of 'keyup' event when back key moves focus inside a scroller

CHANGELOG.md, VirtualList/useEvent.js
If there is no navigable target when switching from pointer mode to 5-way mode on a partially visible focused item, the focus remains on the focused item, but the item still does not show its whole content as there is no scrolling.
Fixed to re-focus only when no focus moving by switching from pointer mode to 5-way mode, so that a scrolling occurs.
WRQ-6220
=> WRQ-6220: Fixed `VirtualList` to show the focused item properly when switching from pointer mode to 5-way mode

Scroller/useThemeScroller.js
Fixed reversed the logic for determining the coordinateCoefficient on ltr. Horizontal scroller doesn't scroll with 5-way key in LTR locale.
WRQ-188
This PR is a hoxfix for #1559
=> WRQ-188: Fix the coordinateCoefficient logic on ltr

samples/qa-a11y/src/views/Dropdown.js
In qa-a11y Dropdown sample, there are samples that the aria-label and title are both set. We add a guide on how to read out these samples. 
Add comment to the qa-a11y dropdown sample that when aria-label and title are both given, only aria-label of dropdown will be read out
WRQ-4796
=> WRQ-4796: Add comment to Dropdown qa-a11y sample

.travis.yml, ThemeDecorator/ThemeDecorator.js, ThemeDecorator/tests/ThemeDecorator-specs.js
Removed LS2Request call from `ThemeDecorator`
Extracted LS2Request call logic from `ThemeDecorator` and added it under `enact/webos/lastInputType`
Now `sandstone/ThemeDecorator` calls the new method instead of calling LS2Request directly
WRq-6498
=> WRQ-6498: Remove LS2Request call from theme library

TransferList/ButtonList.js, TransferList/TransferList.js, TransferList/utils.js, samples/sampler/stories/default/TransferList.js
I replaced the reset button with 2 buttons. One deselects the currently selected items and one resets the entire lists.
I changed the delete functionality to only work with the delete button.
I changed the lists to handle multiple items move on the same list.
I had to remove the delete list operation because it was unintuitive to use. In order to delete an element using it, you needed to drop it on the other list. It is better to remove items by dragging them over the delete icon button, or by selecting them and pressing that button.
[//]: # (Are there any …
=> WRQ-15803: TransferList enhancements (reset buttons, delete function, same list item move)

CHANGELOG.md, TabLayout/TabLayout.js, samples/sampler/stories/qa/TabLayout.js, tests/ui/apps/TabLayout/WithPanelsHeader/TabLayoutWithPanelsHeader-View.js, tests/ui/specs/TabLayout/WithPanelsHeader/TabLayoutWithPanelsHeader-specs.js
The reported issue is that when the `TabLayout` is in `Panels` and move focus from the tab contents via 5-way key, focus moved to the button located in `Header` rather than the tab menu.
navigableFilter in TabLayout/RefocusDecorator filters tab menu buttons and makes to return the button in Header as the nextSpot item when calling Spotlight.move(direction) in the onKeyDown handler.
In this commit, we check the nextSpot item without setting filter by using `getTargetByDirectionFromElement`. And if the next spot is located in tab menu, make focus to be moved by spotlight`s default onKeyDown handler after the …
=> WRQ-18041: Fix TabLayout to move focus to the tab menu when it is in panels 

CHANGELOG.md, TabLayout/TabLayout.js, samples/sampler/stories/qa/TabLayout.js, tests/ui/apps/TabLayout/WithPanelsHeader/TabLayoutWithPanelsHeader-View.js, tests/ui/specs/TabLayout/WithPanelsHeader/TabLayoutWithPanelsHeader-specs.js
The reported issue is that when the `TabLayout` is in `Panels` and move focus from the tab contents via 5-way key, focus moved to the button located in `Header` rather than the tab menu.
navigableFilter in TabLayout/RefocusDecorator filters tab menu buttons and makes to return the button in Header as the nextSpot item when calling Spotlight.move(direction) in the onKeyDown handler.
In this commit, we check the nextSpot item without setting filter by using `getTargetByDirectionFromElement`. And if the next spot is located in tab menu, make focus to be moved by spotlight`s default onKeyDown handler after the …
=> WRQ-18041: Fix TabLayout to move focus to the tab menu when it is in panels (2.7.x)

ThemeDecorator/screenTypes.json
We need to support QHD resolution for TV.
Because TV model which needs for QHD is based on sandstone 2.7.x version, this PR is for release/2.7.x.develop branch.
I copied changed code of https://github.com/enactjs/sandstone/pull/1596
added QHD type in screenTypes.json file.
WRQ-17933
=> WRQ-17933: Support QHD resolution

CHANGELOG.md
QHD is supported in sandstone by this ticket https://github.com/enactjs/sandstone/pull/1599
We need to add CHANGELOG for sandstone QHD support
I added CHANGELOG for sandstone QHD support
WRQ-17933
=> WRQ-17933: Add changelog for QHD support

CHANGELOG.md, PageViews/PageViews.js, PageViews/PageViews.module.less, samples/sampler/stories/default/PageViews.js, tests/screenshot/apps/components/PageViews.js
By adding the `fullContents` prop in PageViews component, make contents of the page to fit into the PageViews component.
Add `fullContents` prop 
WRQ-17937
=> WRQ-17937: Add `fullContents` prop in PageViews

.travis.yml, CHANGELOG.md, FixedPopupPanels/FixedPopupPanels.js, FixedPopupPanels/FixedPopupPanels.module.less
Fixed an issues where FixedPopupPanels were always full height when in high contrast mode.
Added missing styles to FixedPopupPanels and added noOutline to PopupDecorator to prevent outlines from being duplicated.
WRQ-22257
=> WRQ-22257: Fixed an issues where FixedPopupPanels were always full height when in high contrast mode

.travis.yml, TabLayout/tests/TabGroup-specs.js, internal/DateTime/DateTime.module.less, internal/Picker/tests/Picker-specs.js
As DOM structure of ui/Spottable is updated in enactjs/enact/pull/3243, the corresponding internal style sheet needs to be updated.
Updated the related styles.
Also, unit tests for TabLayout and Picker are updated due to DOM structure changes.
WRQ-19325
enactjs/enact/pull/3243
=> WRQ-19325: Updated DateTime's internal style to work with changed DOM structure of Spottable

ContextualPopupDecorator/ContextualPopupDecorator.js, Dropdown/DropdownList.js
When migrate with the enact(https://github.com/enactjs/enact/commit/33c27d5040459063bc13901d0cc76e0fb3a8731d), DOM structure of `ContextualPopupDecorator` has two dummy `div` which caused the contextual popup's position to be calculated incorrectly.
No invalid DOM structure was found in `DropdownList`, but we also fix DropdownList.
Fix `ContextualPopupDecorator` and `DropdownList` to use WithRef to add sibling DOM node. 
[//]: # (Were any side-effects …
=> WRQ-19324: Fix `ContextualPopupDecorator` and `DropdownList` to add sibling DOM node using WithRef instead of adding sibling DOM node manually.

TabLayout/TabLayout.js, TabLayout/tests/TabLayout-specs.js
Temporal code to cancel back key behavior of TabLayout remains even app developers don't need it as they can handle the case with a normal onKeyUp handler.
Removed unnecessary code.
WRQ-7995
=> WRQ-7995: Clean up unnecessary code to cancel back key behavior by app scenarios

.travis.yml, Marquee/Marquee.js
Fix `Marquee` to not override `marqueeDirection`(that code moved to `@enact/ui/Marquee.MarqueeDecorator`)
Remove `marqueeDirection` override in `Marquee`
WRQ-17541
=> WRQ-17541: Fix Marquee to not override marqueeDirection

CHANGELOG.md, Scroller/EditableWrapper.js, samples/sampler/stories/qa/IconItem.js, samples/sampler/stories/qa/Scroller.js
In edit mode, the focused item in Editable Scroller seems not properly blurred when the pointer leaves the item.
The problem here is that there is `focusItemRef` to focus the IconItem by pointer but there is no way to blur it when the pointer leaves. Since we are manually adding `.focused` class by function.
So I added `blurItemRef` to get the function to blur the item and call it when the pointer leaves the item container.
If I call the function when the IconItem gets blurred, there is no way to select the additional button showing above (e.g. remove button). …
=> WRQ-25442: Fixed Editable Scroller to blur the focused item properly

samples/sampler/stories/qa/VirtualGridList.js
In qa-sampler > VirtualGridList > `with Button, Spotlight goes to correct target`, scroll with wheel did not work.
`scrollMode` value of VirtualGridList in the sample was `undefined` and this caused the issue.
I added control of `scrollMode`, which have `native` and `translate` value, so `scrollMode` value is passed into VirtualGridList and wheel works well.
WRQ-24170
=> WRQ-24170: Fixed VirtualGridList qa sampler by passing args as a prop

CHANGELOG.md, PageViews/PageViews.js, PageViews/PageViews.module.less, PageViews/tests/PageViews-specs.js, styles/variables.less
According to the recent GUI guide, prev and next navigation buttons seem to be `small` type buttons and icons are `arrowlargeleft` and `arrowlargeright`. 
I updated prev and next navigation buttons to `small` type when `pageIndicatorType` is `dot`.
I updated prev and next navigation buttons icons to be `arrowlargelft` and `arrowlargeright`.
I modified PageViews.module.less to update navigation button …
=> WRQ-27016: Fix PageViews styling as GUI guide

samples/sampler/package.json, samples/sampler/src/ThemeEnvironment/ThemeEnvironment.js
Storybook reads and applies colors fetched from service settings
Storybook reads and applies colors fetched from service settings
Added `@enact/webos` as sampler dependency
WRQ-28743
=> WRQ-28743: Storybook - Read custom colors/presets from luna settings service

.travis.yml, samples/qa-a11y/src/views/VirtualGridList.js, samples/qa-a11y/src/views/VirtualList.js
In https://github.com/enactjs/enact/pull/3260, we added support for reading the order of items in VirtualList and VirtualGridList.
So I added qa-a11y samples for this added feature in VirtualList and VirtualGridList. 
Add x of y feature in VirtualList and VritualGridList qa-a11y sample
WRQ-27279
=> WRQ-27279: Added x of y feature to VirtualList and VirtualGridList qa-a11y samples

ColorPickerPOC/ColorPickerSpectrum.js, ColorPickerPOC/ColorPickerSpectrum.module.less
Added Page responsiveness to Spectrum Color Picker
WRQ-32413
=> WRQ-32413: [POC] webOS ColorPicker - add responsiveness

Alert/Alert.js, CHANGELOG.md, tests/screenshot/apps/components/Alert.js, tests/screenshot/apps/components/Alert.module.less
We decided to provide a public class to expand size of title and content in Alert so that full text can be shown wider on the screen.
I added public classes to Alert.
- alert
- fullscreen
- title
- content
Title and content width can be expanded using these public classes.
This PR is for sandstone 2.7 and copied from https://github.com/enactjs/sandstone/pull/1652
WRQ-27436
=> WRQ-27436: Added public classes to expand size of title and content in Alert

samples/sampler/package.json
Update babel-loader v9
Update babel-loader v9
Breaking changes in babel-loader v9 (https://github.com/babel/babel-loader/releases/tag/v9.0.0)
- Require babel ^7.12.0 and Node.js >= 14.15.0 versions
- Remove dependency on loader-utils and drop webpack 4 support
WRQ-28043
=> WRQ-28043: Update babel-loader v9

ColorPickerPOC/ColorPickerPOC.js, ColorPickerPOC/ColorPickerSpectrum.js, ColorPickerPOC/ColorPickerSpectrum.module.less
onPointerDown currently activates long press, which is ok for touch screens, but not for click.
Removed mouse event handlers for favorite color buttons
Added an useEffect to update component state when the props for current color of favorite colors change.
WRQ-32437
Enact-DCO-1.0-Signed-off-by: Daniel Stoian ([daniel.stoian@lgepartner.com](mailto:daniel.stoian@lgepartner.com))
=> WRQ-32437: Fixed deletion of favorite colors for ColorPicker

CHANGELOG.md, useScroll/ScrollbarTrack.module.less
The small indicator for Scrollbar when `focusableScrollbar` prop is true is not showing since 2.6.0.
​​![image](https://github.com/user-attachments/assets/45969a7c-e02e-4e07-9203-c5b0e396c4b8)
While we were updating LESS v3 to v4, we missed to migrate the code that needs to be wrapped in parentheses to force math division. Because it doesn't have spaces between `/` it could have been missed from our "search".
So I fixed the code as well as adding sapces.
This PR is …
=> WRR-2431: Fix `Scroller` to show scroll indicator on scrollbar when `focusableScrollbar` prop is `true`

samples/sampler/stories/qa/VirtualList.js
When the content of the virtual list changed, there was a issue that the scroller could not move to the end of the scroller.
This issue fixed in https://github.com/enactjs/enact/pull/3279 implementation. In this PR, we will add this issue case in qa-sampler.
In virtualList qa-sampler, I added case where the contents of a VirtualList change between fixed size and variable size
[//]: # (Related issues, …
=> WRR-2172: Update VirtualList qa-sampler for cases where the contents of a VirtualList change between fixed size and variable size contents

CHANGELOG.md, Panels/Header.js, samples/sampler/stories/qa/WizardPanels.js
When using WizardPanels, if the subtitles are long, they appear long for a moment and then shorten.
This is because the sizes of slotAfter and slotBefore are fixed after the subtitle is drawn. For centering of the title, the slot is measured after the element is drawn.
I adjusted the timing of when the slot is fixed and when the subtitle and title are drawn.
Specifically, I modified the subtitle and title to be drawn together when the slot is drawn.
Therefore, the phenomenon of the subtitle appearing long for a moment and then appearing short disappears.
[//]: # …
=> WRR-3137: Fixed `Panels.Header` to show title and subtitle properly in `WizardPanels`

CHANGELOG.md, samples/sampler/stories/qa/Panels.js, useScroll/ScrollbarPlaceholder.js
When a `Scroller` with a `focusableScrollbar` contains a button and is located in a `Panel`, the read-out feature behaved differently than we expected.
Screen reader read "Button A" before "This is a panel" was fully read, so the user would only hear the aria label of the `button`.
```
<Panel aria-label = 'This is a panel'>
<Header title = 'Title' />
<Scroller focusableScrollbar>
<Button onClick={() => this.setState({index: 0})}>Button A</Button>
</Scroller>
</Panel>
```
* This issue occurred because when `focusableScrollbar` was enabled, …
=> WRR-4572: Fix `Scroller` to read out its content properly when it is located in `Panel`

CHANGELOG.md, VideoPlayer/VideoPlayer.js
There is an issue where the media slider appears when you press the play/pause button on the remote control.
But only mini feedback content should appear.
I set the initial value for playbackRate.
Previously, the playbackRate value was always set via the setPlaybackRate function when the play and pause functions were called.
Now, playbackRate is set only when in seeking mode when the play/pause functions were called. Therefore, the initial value of playbackRate is missing and set to undefined. Because of this, the visibility conditions of the media slider have changed.
[//]: # (How should the change be …
=> WRR-4591: Fix `VideoPlayer` to show only the mini feedback when pressing play/pause key

CHANGELOG.md, useScroll/useEvent.js
When a focusable node inside a scroller is sticked to the top, it cannot be focused after scroll by voice control.
The cause is a logic to check if the candidate focus target is inside of a scroller viewport. When a focusable node is touching the boundary of a viewport, the existing logic does not consider the node as visible since it missed simply '='.
I updated to recognize the case that boundaries are the same.
I also refine some code with another commit.
[//]: # …
=> WRR-4590: Fix to focus the topmost element after scroll by voice control

styles/mixins.scss, styles/utils.scss, styles/variables.scss
Converted mixins to SCSS: `sand-item-icon-tap-area-adjust`, `sand-alert-title` and `sand-alert-subtitle`.
WRR-5235
=> WRR-5235: Converted remaining Sandstone mixins to SCSS

CHANGELOG.md, MediaPlayer/MediaControls.js, samples/sampler/stories/default/VideoPlayer.js
We ​​need to allow overriding the aria-label of JumpButtons in `MediaControls`
Added `jumpBackwardAriaLabel` and `jumpForwardAriaLabel` props
WRR-4628
=> WRR-4628: Added `jumpBackwardAriaLabel` and `jumpForwardAriaLabel` props

CHANGELOG.md, PageViews/PageViews.module.less
The issue is that the navButtonContainer area of the PageViews was too tight, so the shadow of navigation buttons was clip when `fullContents` prop is `true`.
Set the height of the `navButtonContainer` to twice the height of the button.
And the formula related to `top`is a calculation that will position the navButtonContainer in the center.
WRR-4660
=> WRR-4660: Fixed `PageViews` to not clip the shadow of navigation buttons

CHANGELOG.md, PageViews/PageViews.js, PageViews/PageViewsRouter.js
Even if autoFocus is set to none to PageViews and noAutoFocus is set to true to ThemeDecorator, there is an issue where focus is set to the navigation button of PageViews.
I added autoFocus as a prop so that it can be set to a received value rather than a fixed value.
WRR-5417
=> WRR-5417: Modified so that PageViews do not receive focus when autoFocus is set to none

CHANGELOG.md, IconItem/IconItem.js, Scroller/EditableWrapper.js, samples/sampler/stories/qa/IconItem.js
When there is long `label` inside `IconItem` in editable `Scroller`, after done editing the marquee stops and it will never start again.
When completing edit, the DOM changes its order and it makes the marquee stops. I guess it's from engine but unfortunately, I coundn't find the specific logic or part. As far as I investigate, JS code has nothing to do with stopping maruee.
To resolve this issue, I chose to let `Marquee` to invalidate its metrics to restart safely with `invalidateProps` of `MarqueeDecorator`. I've added `order` as `invalidateProps` and pass it to `Marquee` through `IconItem` in JSX so that …
=> WRR-6050: Fixed `IconItem` to restart marquee after done editing in `Scroller` with `editable` prop

CHANGELOG.md, PageViews/PageViews.js, PageViews/PageViews.module.less, QuickGuidePanels/QuickGuidePanels.js, QuickGuidePanels/QuickGuidePanels.module.less, Steps/Steps.js, Steps/Steps.module.less, styles/colors.less, styles/variables.less
The dot type page indicators in `PageViews` seems not center aligned.
We've tried to adjust align with the icon font but it's hard to implement with font.
So I implemented with pure div with CSS style instead of Icon component.
I've modified `QuickGuidePanels` too since it's also using `Steps` to show page indicators. I think we need to make a new component "PageIndicator" rather than using `Steps` eventually. I'll make another ticket for this.
[//]: # (Related …
=> WRR-4972: Fixed `PageViews` and `QuickGuidePanels` dot page indicators to be aligned center

.travis.yml, CHANGELOG.md, ContextualPopupDecorator/ContextualPopupDecorator.js, ContextualPopupDecorator/tests/ContextualPopupDecorator-specs.js
When ContextualPopupDecorator or ContextualMenuDecorator is open, rotating the device in the inspector should change the popup's position. Currently the popup is fixed and does not update.
I needed to check whether the position had not been updated or the value had been entered incorrectly. When rotated, I saw that when I refreshed, the position was calculated normally again. Therefore, the position calculation was no problem.
The position is updated with the positionContextualPopup function, which is not called when the window size changes, including when the screen is rotated. Therefore, I modified it to …
=> WRR-976: ContextualPopupDecorator: Modified to update position when screen orientation change

CHANGELOG.md, Input/Input.module.less, styles/variables.less, tests/screenshot/apps/components/Input.js
With portrait fullscreen or overlay type, keypad of number type input should have 3 columns.
But in largeText mode, keypad has 2 columns now.
This is because width is set to exactly fit normal mode.
I added keypad width values for largeText mode in portrait fullscreen & overlay type.
WRR-9101
=> WRR-9101: Fixed `Input` keypad layout in largeText mode

samples/sampler/stories/qa/VirtualList.js
When the size of the item in VirtualList changed, there was an issue that virtualList did not recalculate the position of the item.
The issue fixed in https://github.com/enactjs/enact/pull/3293 implementation. In this PR, we will add this issue case in qa-sampler.
I added issue case in virtualList qa-sampler. 
WRR-9866
=> WRR-9866: Added VirtualList qa-sampler for case where the size of each item is changed 

samples/sampler/stories/qa/VirtualList.js
When the size of the item in VirtualList changed, there was an issue that virtualList did not recalculate the position of the item.
The issue fixed in https://github.com/enactjs/enact/pull/3293 implementation. In this PR, we will add this issue case in qa-sampler.
I added issue case in virtualList qa-sampler. 
WRR-9866
=> WRR-9866: Added VirtualList qa-sampler

CHANGELOG.md, Slider/SliderBehaviorDecorator.js
When a user drags a slider with touch to move the slider, a console error occurs.
The console error occurs because a _ref_ is not properly passed to ui/Slider so I created the patch first. But, after investigation and tests, I concluded that the logic using the _ref_ is actually not needed anymore. Therefore, I want to remove the issued logic.
The issued logic is to focus a slider knob even a user touch slightly out of the slider knob to show a focus effect on the …
=> WRR-6683: Remove logic to focus a slider when dragging with touch 

CHANGELOG.md, useScroll/useEvent.js
When scrolling down with voice control in certain apps, focus is not restored.
Currently, when scrolling with voice control, focus is moved only when the bounds of the viewport include all bounds of the node.
Therefore, it is necessary to handle the case where the node's bounds are not all included in the viewport's bounds.
(when there is a large node that goes out of bounds, the upper part is visible but the lower part is cut off, etc.)
Added focus logic for cases where the top of the node is long and the bottom of the node is long using node Bounds and viewports Bounds. Since I need to receive and check …
=> WRR-9115: `Scroller`: Fixed to focus properly when the spottable node is bigger than the viewport by scrolling with voice control

CHANGELOG.md, QuickGuidePanels/QuickGuidePanels.js
The UX Guide of QuickGuidePanels read out feautre is updated. 
Instead of `Step ${num}` calcualte aria-label as `Page {num} out of {total}` in QuickGuidePanels.
WRR-10531
=> WRR-10531: Changed QuickGuidePanels to read out more details

.travis.yml, CHANGELOG.md, samples/sampler/stories/qa/Scroller.js, useScroll/useScroll.js
When the Scroller has a button that opens FixedPopupPanel. The issue is that when press the down key at the moment the popup is opened the scroller behind the FixedPopupPanel scrolls down.
To fix this issue, we have to prevent the native scrolling behavior caused by keydown events.
I created preventScroll function which call `preventDefault` when a keydown event is caused by a directional key and the spotlight is paused.
I added this preventScroll function to useThemeScroll so that it can be passed to ui/Scroller and used as prop.
Also I added …
=> WRR-11077: Fixed Scroller to prevent the native scrolling behavior caused by keydown events when the popup is opened

samples/sampler/stories/qa/VirtualList.js
To verify https://github.com/enactjs/enact/pull/3299, we need a qa-sampler.
This PR adds a VirtualList qa-sampler for changing both `dataSize` and `itemSizes`.
Added a VirtualList qa-sampler for changing both `dataSize` and `itemSizes`.
WRR-12807
=> WRR-12807: Added VirtualList qa-sampler for changing `dataSize` and `itemSizes`

samples/sampler/stories/helper/icons.js, samples/sampler/stories/qa/TabLayout.js
As TabLayout sampler uses an icon list that is changing by font update, our screenshot tests are affected.
I made a fixed list for TabLayout sampler so that a list of icons would not be affected by font changes.
WRR-11059
=> WRR-11059: update TabLayout storybook sample's icons

tests/ui/apps/PageViews/PageViewsAutoFocus-View.js, tests/ui/specs/PageViews/PageViews-specs.js, tests/ui/specs/PageViews/PageViewsPage.js
I Implemented UI test for WRR-5417. 
Needed to test when autoFocus='none' in PageViews.
Check if there is an activeElement when autoFocus='none' for PageViews, autoFocus='none' for Panel, 
and noAutoFocus=true is set in ThemeDecorator's config.
WRR-14027
=> WRR-14027: Added UI test when PageViews' autoFocus is 'none'

internal/Panels/Arrangers.js
Default value of `arranger` prop in `Sandstone/Panels` does not match the documentation.
Documentation says the default is `ui/ViewManager.SlideLeftArranger`, but actual value is `BasicArranger` from `internals/Panles/Arrangers.js`.
Default value was changed in https://github.com/enactjs/sandstone/pull/315 from `SlideLeftArranger` to `BasicArranger` and `arrange` in `BasicArranger` was changed to `deferArrange` in https://github.com/enactjs/sandstone/pull/577
But `BasicArranger` is for internal use.
So instead of updating documentation of `arranger` in `Sandstone/Panels`, I updated documentation of …
=> WRR-387: `Panels`: Updated documentation for arranger

Scroller/EditableWrapper.js, samples/sampler/stories/qa/IconItem.js
Current editable `Scroller` uses static classname checking like `ev.target.className.includes('Button')`.
This would not work when https://github.com/enactjs/cli/pull/361 merged.
Changed the code uses static classname to see `role` instead.
WRR-8543
=> WRR-8543: Fixed editable `Scroller` not to use static classname

CHANGELOG.md, Scroller/EditableWrapper.js, useScroll/HoverToScroll.js, useScroll/HoverToScroll.module.less
Update editable scroller to support drag and drop in touch mode
Cherry-pick dd3917b8078cda1ef7ba5d99c8bd44ea988e1ac8 to support touch mode in editable scroller
Fix editable scroller to enable hover-to-scroll by touch 
WRR-14337
=> WRR-14337: Update editable scroller to support touch mode

CHANGELOG.md, TooltipDecorator/useTooltip.js, samples/sampler/stories/qa/Tooltip.js
After tapping a disabled component with a tooltip once, a tooltip does not disappear even by tapping other components or empty space. This issue occurs only by touch inputs.
There was a bug that show a tooltip again after hiding only for disabled components. I fixed the logic not to show again a tooltip.
WRR-14835
=> WRR-14835: TooltipDecorator to hide a tooltip when tapping outside of disabled components

QuickGuidePanels/QuickGuidePanels.js
Because the $L string of `PageViews` and `QuickGuidePanels` was different, there was an issue where the translation did not work properly.
Update `QuickGuidePanels` $L string to be translated. 
WRR-15666
=> WRR-15666: Fix $L string in QuickGuidePanels to be translated properly

Scroller/EditableWrapper.js, useScroll/HoverToScroll.js, useScroll/HoverToScroll.module.less
Fix editable scroller to enable hoverToScroll via touch 
Added `--scroller-hover-to-scroll-by-touch` css variable to set `pointer-events` value to true in touch mode 
WRR-14337
=> WRR-14337: Fix EditableWrapper to enable hoverToScroll via touch

Scroller/EditableWrapper.js, useScroll/HoverToScroll.js, useScroll/HoverToScroll.module.less
Fix editable scroller to enable hoverToScroll via touch 
Added `--scroller-hover-to-scroll-by-touch` css variable to set `pointer-events` value to true in touch mode 
WRR-14337
=> WRR-14337: Fix editable scroller to enable hoverToScroll via touch 

CHANGELOG.md, ContextualPopupDecorator/ContextualPopupDecorator.js, samples/qa-dropdown/src/views/MainPanel.js, samples/sampler/stories/qa/Dropdown.js
After the dropdown is opened, if the DOM tree changes, the position of the dropdown will not change.
Because Dropdown component uses ContextualPopupDecorator, I added mutationObserver to ContextualPopupDecrator to detect changes in the DOM tree. Since we don't know which part of the DOM will change, I attach an observer to document.body and update the location when there is a change.
WRR-16145
Enact-DCO-1.0-Signed-off-by: Hyelyn …
=> WRR-16145: ContextualPopupDecorator: Modified to update position when DOM tree changes

CHANGELOG.md, TooltipDecorator/useTooltip.js, samples/sampler/stories/qa/Tooltip.js
After tapping a disabled component with a tooltip once, a tooltip does not disappear even by tapping other components or empty space. This issue occurs only by touch inputs.
There was a bug that show a tooltip again after hiding only for disabled components. I fixed the logic not to show again a tooltip.
WRR-14835
=> WRR-14835: `TooltipDecorator` to hide a tooltip when tapping outside of disabled components
