.travis.yml
Recently, we updated Lerna version for Enact from 2.x to 4. Due to a breaking change from Lerna 3, Travis CI test for this library does not work properly.
Also, we're using node 10 for Travis CI and it looks better to use LTS version of node for long-term testing.
Update node version to LTS and update a Lerna option in .travis.yml.
PLAT-139487
=> PLAT-139487: Update travis CI configuration

samples/sampler/stories/qa/Text.js
Added Font Weight to Languages sampler
ENYO-6223
=> ENYO-6223: Add Font Weight to the sample Text > Languages

tests/ui/specs/WizardPanels/WizardPanelsPage.js
- Need to increase timeout limit for WizardPanels api.
- Increase timeout limit for WizardPanels api.
PLAT-139789
=> PLAT-139789: Fix ui-test fail on WizardPanels

CHANGELOG.md, ImageItem/ImageItem.js, samples/sampler/stories/default/ImageItem.js
Fixed ImageItem resizing issues. Added scaling to parent div in sampler and imported Image instead of ImageBase for the imageComponent prop, as Image component is wrapped in the ResponsiveImageDecorator which fixes the problem concerning the updating of the image to reflect the new sizing.
PLAT-111125
=> PLAT-111125: ImageItem resizing issues

samples/sampler/stories/qa/ContextualPopupDecorator.js
Created QA sample for ContextualPopupDecorator with Slider to test ContextualPopupDecorator arrow.
ENYO-6198
=> ENYO-6198: Sample added to test ContextualPopupDecorator arrow with SliderTooltip

tests/ui/apps/PopupTabLayout/PopupTabLayout-View.js, tests/ui/specs/PopupTabLayout/PopupTabLayout-specs.js, tests/ui/specs/PopupTabLayout/PopupTabLayoutPage.js
- Need to fix ui-test fail on PopupTabLayout for changed ux.
- Fix ui-test fail on PopupTabLayout for changed ux.
PLAT-140826
=> PLAT-140826: Fix ui-test fail on PopupTabLayout

CHANGELOG.md, MediaPlayer/MediaSlider.module.less, Slider/Slider.module.less, TabLayout/TabLayout.js, ThemeDecorator/ThemeDecorator.js, ThemeDecorator/ThemeDecorator.module.less, package-lock.json, package.json, samples/sampler/npm-shrinkwrap.json, samples/sampler/stories/qa/PopupTabLayout.js, useScroll/ScrollbarTrack.module.less, useScroll/useOverscrollEffect.js
We want to provide better UX on touchable display.
Tweaks spotlight effect not to show on touch inputs.
PLAT-132837
=> PLAT-132837: Enhance touch support

samples/sampler/stories/qa/Marquee.js
This sample needs to be updated for the appropriate fonts to test
Change text in the button so that can test remeasurement of marquee
PLAT-139774
=> PLAT-139774: QA Sampler - Marquee>I18n: Ellipsis (3 dots) do show when they should not

tests/ui/apps/VirtualList/VirtualGridList/VirtualGridList-View.js, tests/ui/specs/VirtualList/VirtualGridList/ElementSize/VirtualGridList-GT-28445-specs.js, tests/ui/specs/VirtualList/VirtualGridList/ElementSize/VirtualGridList-GT-28446-specs.js, tests/ui/specs/VirtualList/VirtualGridList/VirtualGridList-specs.js, tests/ui/specs/VirtualList/VirtualGridList/VirtualGridListPage.js, tests/ui/specs/VirtualList/VirtualGridList/With5-way/VirtualGridList-GT-28449-specs.js, tests/ui/specs/VirtualList/VirtualGridList/With5-way/VirtualGridList-GT-28451-specs.js, tests/ui/specs/VirtualList/VirtualGridList/With5-way/VirtualGridList-GT-28454-specs.js, tests/ui/specs/VirtualList/VirtualGridList/With5-way/VirtualGridList-GT-28455-specs.js, tests/ui/specs/VirtualList/VirtualGridList/With5-way/VirtualGridList-GT-28565-specs.js, tests/ui/specs/VirtualList/VirtualGridList/With5-way/VirtualGridList-GT-28584-specs.js, tests/ui/specs/VirtualList/VirtualGridList/onScroll/VirtualGridList-GT-28555-specs.js, tests/ui/specs/VirtualList/VirtualGridList/onScroll/VirtualGridList-GT-30066-specs.js
- Need to add VirtualGridList ui-test.
- Need to add and modify api for VirtualGridList ui-test.
- Add VirtualGridList ui-test.
- Add and modify api for VirtualGridList ui-test.
PLAT-139787
=> PLAT-139787:  Add VirtualGridList UI Test.

samples/sampler/stories/qa/Spinner.js
Sample created using Moonstone's Input needs to be updated using Sandstone's InputField
Replace Input with InputField
PLAT-105485
=> PLAT-105485: QA-Sampler - Spinner>with Input: needs to be fixed in Sandstone

CHANGELOG.md, Input/Input.js, Input/InputField.js, Input/InputField.module.less, Input/util.js, samples/sampler/stories/default/Input.js, samples/sampler/stories/default/InputField.js
Need tel type VKB for input number and special characters
Add tel, passwordtel type in Input component
N/A
https://jira2.lgsvl.com/browse/PLAT-142922
N/A
=> PLAT-142922: Input: Add tel, passwordtel type

CHANGELOG.md, Scroller/useThemeScroller.js
Scroll position moves abnormally in RTL horizontal scroller.
Apply negative coordinate for calculatePositionOnFocus in `Scroller`. 
PLAT-144650
=> PLAT-144650: Fix scroller moves abnormally in RTL locales

.travis.yml, ContextualPopupDecorator/tests/ContextualPopupDecorator-specs.js, DayPicker/DaySelectorDecorator.js, Image/Image.js, MediaPlayer/MediaControls.js, MediaPlayer/MediaSliderDecorator.js, Panels/tests/Panels-specs.js, TabLayout/RefocusDecorator.js, ThemeDecorator/AccessibilityDecorator.js, ThemeDecorator/I18nFontDecorator.js, VirtualList/tests/VirtualList-specs.js, VirtualList/useThemeVirtualList.js, internal/SharedStateDecorator/tests/SharedStateDecorator-specs.js, samples/qa-a11y/src/views/FixedPopupPanels.js, samples/qa-a11y/src/views/VirtualGridList.js, samples/qa-a11y/src/views/VirtualList.js, samples/sampler/stories/qa/Marquee.js, samples/sampler/stories/qa/PopupTabLayout.js, samples/sampler/stories/qa/VirtualList.js, tests/screenshot/apps/Sandstone-View.js, tests/screenshot/apps/components/Icon.js, tests/ui/apps/VirtualList/VirtualGridList/VirtualGridList-View.js, tests/ui/apps/VirtualList/VirtualList/VirtualList-View.js, tests/ui/apps/VirtualList/VirtualList/VirtualListInPanels/VirtualListInPanels-View.js, tests/ui/apps/VirtualList/VirtualList/VirtualListInScroller/VirtualListInScroller-View.js, tests/ui/apps/VirtualList/VirtualList/VirtualListWithSpotlight/VirtualListWithMultipleSpottables-View.js, tests/ui/specs/WizardPanels/WizardPanels-specs.js
=> Enyo-5941 : Fix --report-unused-disable-directives warnings and enable for Travis

samples/sampler/stories/qa/VirtualGridList.js
The sample for snapToCenter is not showing properly.
Update the width
PLAT-142133
=> PLAT-142133: Sampler fix

useScroll/HoverToScroll.js
Isomorphic test failed.
Added guard code.
=> Fix isomorphic test failure

samples/sampler/stories/qa/VirtualGridList.js
Add sampler to test restore focus on VirtualGridList within Scroller
PLAT-144225
=> PLAT-144225: Add qa-sampler to test restore focus on VirtualGridList within Scroller

CHANGELOG.md, useScroll/HoverToScroll.js
`hoverToScroll` does not work as expected when there is no scrollbar due to a rendering cycle of the current implementation
Fix to work as expected
PLAT-145113
=> PLAT-145113: Fix to scroll by hover properly when there is no scrollbar

CHANGELOG.md, Slider/Slider.module.less
GUI team request expand hover area of Slider
The area is modified
N/A
PLAT-128265
=> PLAT-128265: Expand hover area in Slider

CHANGELOG.md, Popup/Popup.js
We've reverted https://github.com/enactjs/sandstone/pull/948 from 2.0.0-rc.2 and this PR is adding the feature back with guard.
PLAT-127486
=> PLAT-127486: Fixed Popup to have proper focus when `noAnimation`

samples/sampler/stories/qa/FixedPopupPanels.js
Accidentally omit the sampler
PLAT-127486
=> PLAT-127486: QA sampler Popup: Added back the sample change

CHANGELOG.md, WizardPanels/Panel.js, WizardPanels/WizardPanels.js
Reverts #975 
it is reverted due to below issues.
- After changing the panel, the focus is not visible (WRN-2302)
- Panel contents was not updated properly after changing state. (WRN-2389)
=> Revert "PLAT-143483: Fixed Wizardpanel to not re-render the previous panel"

samples/qa-virtualgridlist/package.json, samples/qa-virtualgridlist/template.ejs
To apply css variable to override
Added template to load configuration css file.
You should create "custom_skin.css" like below.
```
.sandstone-theme {
--sand-accent-color: orange;
}
```
WRN-1582
=> WRN-1582: POC2: Apply and load configuration file

samples/qa-virtuallist/package.json, samples/qa-virtuallist/template.ejs
To override font face
Added template.ejs to add custom_skin.css
WRN-1581
=> WRN-1581: POC: Overriding font face

Input/InputField.module.less, Scroller/Scroller.module.less, ThemeDecorator/ThemeDecorator.js, internal/Picker/Picker.module.less, styles/color-mixins.less, styles/colors.less
PoC to use CSS variables for custom skin
WRN-1579
=> WRN-1579: PoC to use CSS variables for custom skin

Checkbox/tests/Checkbox-specs.js, CheckboxItem/tests/CheckboxItem-specs.js
Migrated `Checkbox` and `CheckboxItem` unit tests from Enzyme to React Testing Library
WRN-1346
=> WRN-1346: Migrate Checkbox and CheckboxItem unit tests to Testing Library

TimePicker/tests/TimePicker-specs.js
=> WRN-1378: Migrated tests for TimePicker.

Sprite/tests/Sprite-specs.js
Migrated `Sprite` unit tests to react-testing-library
WRN-1359
=> WRN-1359: Migrate Sprite unit tests to Testing Library

KeyGuide/tests/KeyGuide-specs.js
=> WRN-1350: Migrated tests for KeyGuide.

Picker/tests/Picker-specs.js
=> WRN-1352: Migrated tests for Picker.

ImageItem/tests/ImageItem-specs.js
Migrated unit tests from Enzyme to Testing Library for ImageItem component.
WRN-1368
=> WRN-1368: Migrate ImageItem unit tests to Testing Library

tests/ui/specs/Slider/Sliders-specs.js
- Need to enough delay for Slider ui-test.
- Add delay for Slider ui-test.
WRN-2487
=> WRN-2487: Fix ui-test fail on Slider

DayPicker/tests/DayPicker-specs.js
Migrated `DayPicker` unit tests to react-testing-library
WRN-1364
=> WRN-1364: Migrate DayPicker unit tests to Testing Library

Steps/tests/Steps-specs.js
Migrated `Steps`'s unit tests to react-testing-library
WRN-1377
=> WRN-1377: Migrate Steps unit tests to Testing Library

FixedPopupPanels/tests/FixedPopupPanels-specs.js
Migrated unit tests from Enzyme to Testing Library for FixedPopupPanels component.
WRN-1365
=> WRN-1365: Migrate FixedPopupPanels unit tests to Testing Library

Item/tests/Item-specs.js
Migrated unit tests from Enzyme to Testing Library for Item component.
WRN-1365
=> WRN-1372: Migrated unit tests for Item to Testing Library

Button/tests/Button-specs.js
Migrated unit tests from Enzyme to Testing Library for Button component.
WRN-1379
=> WRN-1379: Migrated unit tests for Button to Testing-Library

FixedPopupPanels/tests/FixedPopupPanels-specs.js
Refactored FixedPopupPanels unit tests based on testing-library best practices.
WRN-1365
=> WRN-1365: Refactored FixedPopupPanels unit tests based on testing-library best practices

Item/tests/Item-specs.js
Refactored Item unit tests based on testing-library best practices
WRN-1372
=> WRN-1372: Refactored Item unit tests based on testing-library best practices

KeyGuide/tests/KeyGuide-specs.js
=> WRN-1350: Refactored KeyGuide unit tests based on testing-library best practices

ProgressBar/tests/ProgressBar-specs.js, ProgressButton/tests/ProgressButton-specs.js
=> WRN-1353: Refactored ProgressBar and ProgressButton unit tests based on testing-library best practices

DatePicker/tests/DatePicker-specs.js
=> WRN-1363: Refactored DatePicker unit tests based on testing-library best practices

ImageItem/tests/ImageItem-specs.js
Refactored ImageItem unit tests based on testing-library best practices.
WRN-1368
=> WRN-1368: Refactored ImageItem unit tests based on testing-library best practices

Button/tests/Button-specs.js
Refactored Button unit tests based on testing-library best practices
WRN-1379
=> WRN-1379: Refactored Button unit tests based on testing-library best practices

Checkbox/tests/Checkbox-specs.js, CheckboxItem/tests/CheckboxItem-specs.js
Refactored Item unit tests based on testing-library best practice
WRN-1346
=> Refactored Checkbox and CheckboxItem unit tests based on testing-library best practice

ActionGuide/tests/ActionGuide-specs.js, RadioItem/tests/RadioItem-specs.js
Refactored ActionGuide and RadioItemunit tests based on testing-library best practice
WRN-1351
=> Refactored ActionGuide and RadioItemunit tests based on testing-library best practice

Picker/tests/Picker-specs.js
=> WRN-1352: Refactored Picker unit tests based on testing-library best practices

Switch/tests/Switch-specs.js, SwitchItem/tests/SwitchItem-specs.js
Refactored Switch and SwitchItem unit tests based on testing-library best practices.
WRN-1360
=> WRN-1360: Refactored Switch and SwitchItem unit tests based on testing-library best practices

TimePicker/tests/TimePicker-specs.js
=> WRN-1378: Refactored TimePicker unit tests based on testing-library best practices

Input/tests/Input-specs.js, Input/tests/InputField-specs.js
=> WRN-1381: Migrate Input and InputField unit tests to Testing Library.

RangePicker/tests/RangePicker-specs.js
=> WRN-1356: Migrated tests for RangePicker.

Region/tests/Region-specs.js, Spinner/tests/Spinner-specs.js
Refactored Region and Spinner unit tests based on testing-library best practices.
WRN-1357
=> WRN-1357: Refactored Region and Spinner unit tests based on testing-library best practices

BodyText/tests/BodyText-specs.js, Heading/tests/Heading-specs.js
Migrated `BodyText` and `Heading` unit tests to react-testing-library
WRN-1345
=> WRN-1345: Migrate BodyText and Heading unit tests to Testing Library

ContextualPopupDecorator/tests/ContextualPopupDecorator-specs.js
Refactored ContextualPopupDecorator unit tests based on testing-library best practices.
WRN-1347
=> WRN-1347: Refactored ContextualPopupDecorator unit tests based on testing-library best practices

DatePicker/tests/DatePicker-specs.js, TimePicker/tests/TimePicker-specs.js, internal/Picker/tests/Picker-specs.js
=> WRN-1382: Migrate internal/Picker unit tests to Testing Library.

FlexiblePopupPanels/tests/FlexiblePopupPanels-specs.js
Migrated `FlexiblePopupPanels` unit tests to react-testing-library
WRN-1366
=> WRN-1366: Migrate FlexiblePopupPanels unit tests to Testing Library

DayPicker/tests/DayPicker-specs.js
Refactored DayPicker tests based on testing-library best practice
WRN-1364
=> Refactored DayPicker tests based on testing-library best practice

TooltipDecorator/tests/TooltipDecorator-specs.js
Migrated unit tests for TooltipDecorator to testing-library
WRN-1361
=> WRN-1361: Migrated unit tests for TooltipDecorator to testing-library

Popup/tests/Popup-specs.js
Migrated unit tests from Enzyme to Testing Library for Popup component.
WRN-1375
=> WRN-1375: Migrate Popup unit tests to Testing Library

Alert/tests/Alert-specs.js
=> WRN-1362: Migrate Alert unit tests to Testing Library.

VirtualList/tests/VirtualList-specs.js
=> WRN-1386: Migrate VirtualList unit tests to Testing Library.

internal/SharedStateDecorator/tests/SharedStateDecorator-specs.js
=> WRN-1371: Migrate SharedStateDecorator unit tests to Testing Library. 

Slider/tests/Slider-specs.js
=> WRN-1383: Migrate Slider unit tests to Testing Library.

Scroller/tests/Scroller-specs.js
Migrated unit tests from Enzyme to Testing Library for Scroller component.
WRN-1376
=> WRN-1376: Migrate Scroller unit tests to Testing Library

Steps/tests/Steps-specs.js
Updated tests to reflect recent changes in standards.
WRN-3614
=> WRN-3614: Fixed Steps unit tests to match new standards.

Panels/tests/Header-specs.js, Panels/tests/Panels-specs.js
Migrated Header and Panels unit tests to testing library.
WRN-1373
=> WRN-1373: Migrated Header and Panels unit tests to testing library.

TabLayout/tests/TabGroup-specs.js, TabLayout/tests/TabLayout-specs.js
Migrated `TabGroup` and `TabLayout` unit tests to react-testing-library
WRN-1384
=> WRN-1384: Migrate TabGroup and TabLayout unit tests to Testing Library

LICENSE
Added LICENSE in repo
Added LICENSE in repo
WRN-3545
=> WRN-3545: Added LICENSE file

CHANGELOG.md, Input/Input.js, Input/InputField.js, Input/InputField.module.less, Input/NumberField.js, Input/util.js, samples/sampler/stories/default/Input.js, samples/sampler/stories/default/InputField.js
Cherri Pick from https://github.com/enactjs/sandstone/pull/907 
Add `tel` `passwordtel` type to Input component
=> WRN-3771: Cherry-pick PLAT-142922 (PR #907)

Checkbox/Checkbox.module.less, Icon/Icon.module.less, ImageItem/ImageItem.module.less, Input/InputField.module.less, Scroller/Scroller.module.less, Skinnable/Skinnable.js, Switch/Switch.module.less, ThemeDecorator/ThemeDecorator.js, samples/sampler/src/ThemeEnvironment/ThemeEnvironment.js, styles/color-mixins.less, styles/colors-custom.less, styles/colors.less, styles/skin.less
New skin 'custom' for customization support.
WRN-2914
=> WRN-2914: Add a new skin 'custom'

PopupTabLayout/tests/PopupTabLayout-specs.js
Added unit tests using Testing Library for PopupTabLayout component.
WRN-5321
=> WRN-5321: Added unit tests for PopupTabLayout

MediaOverlay/tests/MediaOverlay-specs.js
Added unit tests for MediaOverlay
WRN-5320
=> WRN-5320: Add unit tests to MediaOverlay

FormCheckboxItem/tests/FormCheckboxItem-specs.js
There were no tests for FormCheckboxItem.
Created tests for FormCheckboxItem.
WRN-5319
=> WRN-5319: Add unit tests to FormCheckboxItem.

ContextualMenuDecorator/tests/ContextualMenuDecorator-specs.js
Added unit tests for ContextualMenuDecorator
WRN-5318
=> WRN-5318: Added units tests for ContextualMenuDecorator

tests/screenshot/apps/components/Item.js
There are screenshot test case errors on Item. 
(it was found on jenkins 581, 573)
Two test cases are recognized as the same test case. because the name is same.
Rename the tests to distinguish them.
WRN-5911
=> WRN-5911: Avoid duplicate on screenshot TC name

CHANGELOG.md, internal/Picker/Picker.module.less, styles/colors.less
GUI update: incrementer/decrementer colors of vertical joined picker are updated.
Updated styling
WRN-6849
=> WRN-6849: Update colors of incrementer and decrementer in vertical joined picker

CHANGELOG.md, DatePicker/DatePicker.module.less, DatePicker/DatePickerBase.js, TimePicker/TimePicker.module.less, TimePicker/TimePickerBase.js, internal/DateComponentPicker/DateComponentPicker.js, styles/variables.less
In some locales, DatePicker and TimePicker animate abnormally.
Added min-width
We need a blink ticket for this issue.
WRN-7354
=> WRN-7354: Fixed Date/TimePicker animation

tests/screenshot/apps/components/BodyText.js, tests/screenshot/apps/components/Button.js, tests/screenshot/apps/components/Dropdown.js, tests/screenshot/apps/components/Icon.js, tests/screenshot/apps/components/Image.js, tests/screenshot/apps/components/InputField.js, tests/screenshot/apps/components/Item.js, tests/screenshot/apps/components/Picker.js, tests/screenshot/apps/components/Popup.js, tests/screenshot/apps/components/ProgressBar.js, tests/screenshot/apps/components/RadioItem.js, tests/screenshot/apps/components/RangePicker.js, tests/screenshot/apps/components/WizardPanels.js
- Need to change the TC number in the SS-Test
- Change the TC number in the SS-Test
WRN-5910
As the TC moves from Jira to CLM change the TC number in the SS-Test.
=> WRN-5910: Sync up SS-Test and TC.

DatePicker/DatePicker.module.less, DatePicker/DatePickerBase.js, RangePicker/RangePicker.js, RangePicker/RangePicker.module.less, TimePicker/TimePicker.module.less, TimePicker/TimePickerBase.js, internal/DateComponentPicker/DateComponentPicker.js, internal/DateComponentPicker/DateComponentPicker.module.less, internal/DateComponentPicker/DateComponentRangePicker.js, internal/Picker/Picker.js, styles/variables.less
Remove workaround code related to picker animation as web engine patch applied
Remove 
- https://github.com/enactjs/sandstone/pull/1067
- https://github.com/enactjs/sandstone/pull/1081
WRN-8252
=> WRN-8252: Remove workaround code related to picker animation

ContextualPopupDecorator/ContextualPopup.module.less
Remote workaround code related to chrome rendering issue as patch has been applied.
chromium issue link: https://bugs.chromium.org/p/chromium/issues/detail?id=996931
Revert https://github.com/enactjs/enact/pull/2501
WRN-6719
=> WRN-6719: Revert ContextualPopupDecorator arrow patch

tests/screenshot/apps/components/Picker.js, tests/screenshot/apps/components/ProgressBar.js, tests/screenshot/apps/components/Scroller.js, tests/screenshot/apps/components/Slider.js, tests/screenshot/apps/components/VirtualGridList.js
- Need to fix strange results in screenshot test.
- Fix strange results in screenshot test.
WRN-10109
=> WRN-10109: Fix strange results in the screenshot test

samples/sampler/stories/qa/ContextualPopupDecorator.js
Tooltip arrow was not aligned with the slider knob
Removed unnecesary style for parent element
WRN-12699
=> WRN-12699: Fixed slider tooltip arrow position in qa-sampler for ContextualPopupDecorator

samples/sampler/src/ThemeEnvironment/ThemeEnvironment.js
…contrast
Changing global controls for Large Text and High Contrast did not have any impact over the rendered components
Fixed the setting of these props in ThemeEnvironment
WRN-12844
=> WRN-12844: Fixed global controls for large text and high contrast in sampler app

samples/sampler/stories/default/Marquee.js
Marquee does not work when loading `Marquee` sample on phone device
Changed width of Marquee in order to work on smaller resolution
WRN-12702
=> WRN-12702: Cross-Platform Enact Android/iOS: Marquee - text doesn't marquee

CHANGELOG.md, Input/InputField.module.less, samples/sampler/stories/default/CheckboxItem.js
Adjusted line-height for small inputField so that input text is centered vertically.
WRN-6748
=> WRN-6748: Fixed Cross-Platform Enact iOS: The placeholder of the input is biased downward

Drawing/Drawing.js, Drawing/Drawing.module.less, samples/sampler/stories/default/Drawing.js
Added disabled styles
WRN-17309
=> WRN-17309: [DrawingComponent]Add 'disabled' functionality

Drawing/Drawing.js
Added JSDoc for sandstone/Drawing
WRN-17311
=> WRN-17311: Added JSDoc for sandstone/Drawing

samples/sampler/stories/qa/Item.js, samples/sampler/stories/qa/VirtualList.js
After CLI updates to 4.1.7, lint warning shows.
Fix lint warning
WRN-14981
=> WRN-14981: Fix lint warnings

Drawing/Drawing.js, Drawing/Drawing.module.less
Added functionality for importing a custom background image for the Drawing component
WRN-17318
Enact-DCO-1.0-Signed-off-by: Clapou George-Vladut [vladut.clapou@lgepartner.com]
=> WRN-17318: [Drawing POC] Add Import custom background functionality

Drawing/Drawing.js
Added fill functionality for sandstone/Drawing
WRN-17312
=> WRN-17312: Added fill functionality for sandstone/Drawing

Drawing/Drawing.js
Added a new button that calls the export function from UIDrawing.
WRN-17317
=> WRN-17317: Add canvas export functionality.

Drawing/ColorPicker.js, Drawing/ColorPicker.module.less, Drawing/Drawing.js, Drawing/Drawing.module.less, samples/sampler/stories/default/Drawing.js
Applied proper styling for drawing component.
WRN-18219
=> WRN-18219: [Drawing POC] - Styling

Drawing/Drawing.js
Added geometric shapes options to drawingTool
WRN-17507
=> WRN-17507: Add functionality to draw geometrical shapes (line, circle, triangle, rectangle)

samples/sampler/stories/qa/Scroller.js
2023 UX needs center aligned Scroller List 
Add center aligned list of image item
WRN-17868
=> WRN-17868: Add a scroller sample of centered items

ImageItem/ImageItem.js, samples/qa-a11y/src/views/TabLayout.js, samples/qa-a11y/src/views/VideoPlayer.js, samples/qa-a11y/src/views/VirtualGridList.js, samples/qa-virtualgridlist/src/utils/index.js, samples/qa-virtualgridlistnative-preserve-focus/src/components/SampleVirtualGridList.js, samples/sampler/stories/default/Panel.js, samples/sampler/stories/default/Panels.js, samples/sampler/stories/default/TabLayout.js, samples/sampler/stories/default/VideoPlayer.js, samples/sampler/stories/default/VirtualGridList.js, samples/sampler/stories/qa/VirtualGridList.js, tests/ui/apps/ImageItem/ImageItem-View.js, tests/ui/apps/VirtualList/VirtualGridList/VirtualGridList-View.js
Changed image service.
WRN-17786
=> WRN-17786: Changed Placehold.it Image service

tests/ui/specs/PopupTabLayout/PopupTabLayout-specs.js, tests/ui/specs/PopupTabLayout/PopupTabLayoutPage.js, tests/ui/specs/RadioItem/RadioItem-specs.js, tests/ui/specs/RadioItem/RadioItemPage.js, tests/ui/specs/Scroller/ListOfThings/Scroller-QWT-2516-specs.js, tests/ui/specs/Scroller/ListOfThings/Scroller-QWT-2564-specs.js, tests/ui/specs/Scroller/ListOfThings/Scroller-QWT-2659-specs.js, tests/ui/specs/Scroller/ListOfThings/Scroller-QWT-2662-specs.js, tests/ui/specs/Scroller/ListOfThings/Scroller-QWT-2664-specs.js, tests/ui/specs/Scroller/Scroller-nativeScroll-specs.js, tests/ui/specs/Scroller/Scroller-translateScroll-specs.js, tests/ui/specs/Scroller/Scroller-utils.js, tests/ui/specs/Scroller/ScrollerPage.js, tests/ui/specs/Scroller/WithSpottable/ScrollerWithSpottable-specs.js, tests/ui/specs/Slider/SliderPage.js, tests/ui/specs/Slider/Sliders-specs.js, tests/ui/specs/SwitchItem/SwitchItem-specs.js, tests/ui/specs/SwitchItem/SwitchItemPage.js, tests/ui/specs/spotlight/Spotlight-specs.js, tests/ui/specs/spotlight/SpotlightMultiplePage.js
Migrated UI test for asynchronous running.
WRN-16898
=> Feature/WRN-16898: [Sandstone tests] UI Tests Migration - PopupTabLayout to SwitchItem 

tests/screenshot/apps/components/Picker.js, tests/ui/apps/Picker/Picker-View.js, tests/ui/specs/Picker/Picker-specs.js, tests/ui/specs/Picker/Picker-utils.js, tests/ui/specs/Picker/PickerPage.js
WRN-17762: Updated ss tests and added async ui tests for Picker
WRN-17762
=> WRN-17762: Updated ss tests and added async ui tests for Picker

tests/ui/apps/ContextualPopupDecorator/ContextualPopupDecorator-View.js, tests/ui/specs/ContextualPopupDecorator/ContextualPopupDecorator-specs.js, tests/ui/specs/ContextualPopupDecorator/ContextualPopupDecoratorPage.js
Async migration of tests for ContextualPopupDecorator
WRN-17763
Enact-DCO-1.0-Signed-off-by: Clapou George-Vladut [vladut.clapou@lgepartner.com](mailto:vladut.clapou@lgepartner.com)
=> WRN-17763: Updated async ui tests for ContextualPopupDecorator

samples/sampler/stories/qa/VideoPlayer.js
Enact-DCO-1.0-Signed-off-by: SJ RO (sj.ro@lge.com)'
qa-sampler test case fail.
fix the bug to call right function.
WRN-18420
=> WRN-18420: [QA Sampler] VideoPlayer>Preload Videos: 'videoPlayerOption' does not work properly.

Drawing/Drawing.js
Implemented undo/redo functionality for the Drawing component
WRN-18994
=> WRN-18994: [Drawing POC] Undo/Redo Functionality

.travis.yml, CHANGELOG.md, VirtualList/VirtualList.js, VirtualList/tests/VirtualList-specs.js, VirtualList/useThemeVirtualList.js, useScroll/useScroll.js
Reverts enactjs/sandstone#1188
=> Revert "WRN-842: Add webos-voice props to VirtualList"

samples/sampler/stories/qa/Panel.js, samples/sampler/stories/qa/Panels.js
Added an Panel qa-sampler example that controls the timing of restoring focus when transitioning 
WRN-12949
=> WRN-12949: Added an Panel qa-sampler example that controls the timing of restoring focus when transitioning 

Drawing/DrawingUtils.js
Added undo/redo to drawingUtils
WRN-18652
=> WRN-18652: Add undo/redo to drawingUtils

CHANGELOG.md, internal/Picker/Picker.module.less
To enhance user experience in the touch environment, we need to remove press effects for DatePicker and TimePicker.
Update styles to show effects only for key and pointer inputs.
WRN-19573
=> WRN-19573: Remove focus and press effect on touch input for a joined vertical picker

Spinner/Spinner.module.less
Less 4 has breaking change that parentheses are required (by default) around division-like expressions, to force math evaluation.
Added parentheses to spinner.module.less
WRN-18582
=> WRN-18582: Update the syntax for Less 4

Alert/Alert.module.less, CHANGELOG.md, Icon/Icon.js, Icon/IconList.js, Input/Input.module.less, Panels/Header.js, Panels/tests/Header-specs.js, RadioItem/RadioItem.js, samples/qa-videoplayer/src/views/MainPanel.js, samples/sampler/stories/default/Button.js, samples/sampler/stories/qa/Spotlight.js, samples/sampler/stories/qa/Touchable.js, styles/variables.less
Add or fix touch support for sandstone components
`sandstone/Alert` and `sandstone/Input`: Add support for vertical screen
`sandstone/Icon`: Add a new icon wallpaper
`sandstone/RadioItem`: Replace onTap with onClick to get focus and recieve event function
WRO-2833
=> WRO-2833: Add or fix touch support for sandstone components

Scroller/EditableWrapper.js, samples/event-logger/src/components/InputBoard/InputBoard.js, samples/event-logger/src/components/Log/Logs.js, samples/perf-virtuallist-native-with-different-item-size/src/App.js, samples/perf-virtuallist-native-with-different-item-size/src/views/HorizontalDifferentWidthItemList.js, samples/perf-virtuallist-native-with-different-item-size/src/views/VerticalDifferentHeightItemList.js, samples/perf-virtuallist-native-with-different-item-size/src/views/VerticalExpandableDifferentHeightItemList.js, samples/qa-virtualgridlistnative-preserve-focus/src/store/store.js, samples/qa-virtuallist/src/store/index.js, samples/qa-voice-control/src/index.js, samples/sampler/stories/qa/Heading.js, samples/sampler/stories/qa/Scroller.js, samples/sampler/stories/qa/Touchable.js
- Fix selected item not disappearing while reordering items with hoverToScroll
Recalculate offset of selected item when items moved by scroll event
WRO-574
=> WRO-574: Refine hoverToScroll for a editable scroller

.travis.yml
Requires travis test on multiple node versions including lts
Update .travis.yml so that it can be tested on multiple node versions (lts(16), node(18))
- ubuntu 20 is required for node 18 ( https://docs.travis-ci.com/user/reference/focal/)
- 'npm link' behavior is different between npm6(node14) and npm8(node16,node18) so 'npm install' is done before 'npm link'
WRO-4551
=> WRO-4551:Update the node version of travis

.travis.yml, samples/sampler/stories/qa/Heading.js
- Need to add longer text in heading sample for TV test.
- Add longer text in heading sample for TV test.
WRO-2588
QWT-4470
=> WRO-2588: Need longer text to marquee in Heading sample.

.travis.yml, Input/InputFieldSpotlightDecorator.js
Need to supplement previous PR (https://github.com/enactjs/sandstone/pull/1223) in preparation for edge cases.
Set the values ​​of this.focused, this.node and this.fromMouse to be similar to the code before refactoring since we are not sure if there are any edge cases.
WRO-3994
Enact-DCO-1.0-Signed-off-by: SJ RO ([sj.ro@lge.com](mailto:sj.ro@lge.com))
=> WRO-3994:[PR supplement]InputFieldSpotlightDecorator : remove unnecessary setState structure

Alert/Alert.module.less, CHANGELOG.md, ContextualPopupDecorator/ContextualPopup.module.less, VideoPlayer/MediaTitle.module.less, internal/Picker/Picker.module.less, styles/colors-game.less, styles/colors-highcontrast.less, styles/colors-light.less, styles/colors.less
There are many LESS variables for colors and some semantic relations between variables were missing.
Add more relations between color variables and restructure color-based definitions to semantic-based definitions
Some colors for light skin are updated for better visibility
WRO-396
=> WRO-396: Restructure color variables for predefined skins

tests/ui/apps/VirtualList/VirtualGridList/ScrollTo/VirtualGridListScrollTo-View.js
- Need to change scrollTo() api to work after setState.
- Change scrollTo() api to work after setState.
WRO-5933
=> WRO-5933: Fix ui test fail on jenkins(VirtualGridList)

.travis.yml, Button/Button.js
Updated JSDoc for Button's  minWidth
WRO-4909
=> WRO-4909: Updated JSDoc for Button's  minWidth

Button3D/Button3D.js, ImageItem3D/ImageItem3D.js, Item3D/Item3D.js, samples/sampler/stories/default/Button3D.js, samples/sampler/stories/default/Gallery3D.js, samples/sampler/stories/default/ImageItem3D.js, samples/sampler/stories/default/Item3D.js
Made the components show better that they are 3D components.
Added edge highlights in components and better lighting for VRCanvas in stories.
WRO-8003
=> WRO-8003: Enact WebXR Components - Update Button3D and Item3D/ImageItem3D

tests/screenshot/apps/components/BodyText.js, tests/screenshot/apps/components/Button.js, tests/screenshot/apps/components/Dropdown.js, tests/screenshot/apps/components/Icon.js, tests/screenshot/apps/components/Image.js, tests/screenshot/apps/components/InputField.js, tests/screenshot/apps/components/Item.js, tests/screenshot/apps/components/Picker.js, tests/screenshot/apps/components/Popup.js, tests/screenshot/apps/components/ProgressBar.js, tests/screenshot/apps/components/RadioItem.js, tests/screenshot/apps/components/RangePicker.js, tests/screenshot/apps/components/Scroller.js, tests/screenshot/apps/components/WizardPanels.js
- Need to sync TC number in ss Test(QWT > QWTC).
- Sync TC number in ss Test(QWT>QWTC).
WRO-7726
=> WRO-7726: Sync TC number in ss Test(QWT>QWTC)

Button3D/Button3D.js, Gallery3D/Gallery3D.js, ImageItem3D/ImageItem3D.js, Item3D/Item3D.js
Add Interactions when the VR Mode is active. The user should be able to click a Button, select an Item etc.
Wrapped 3D components in <Interactive /> and added events for select, hover, blur and squeeze.
WRO-8012
=> WRO-8012: [POC] Enact WebXR Components - Add VR interactions

Button3D/Button3D.js, ImageItem3D/ImageItem3D.js, Item3D/Item3D.js, internal/util/util.js, samples/sampler/stories/default/Button3D.js, samples/sampler/stories/default/ImageItem3D.js, samples/sampler/stories/default/Item3D.js
Code cleanup for Sandstone 3d components
WRO-8014
=> WRO-8014: [POC] Enact WebXR Components - Code cleanup

samples/sampler/stories/qa/Scroller.js
- Need to add more sample for nested scroller.
- Need to add 'scrollMode' prop in nested scroller sample.
- Add more sample for nested scroller.
- Add 'scrollMode' prop in nested scroller sample.
WRO-615
=> WRO-615: Add new nested scroller sample in qa-sampler.

CHANGELOG.md, Icon/Icon.js, Icon/IconList.js, samples/sampler/stories/helper/icons.js
Adding a new icon `r2rappcall` to Sandstone icon
WRO-9306
=> WRO-9306: Adding a new icon`r2rappcall`

tests/screenshot/apps/components/Alert.js
- Need to add screenshot test cases for some components in Alert
- Add screenshot test cases for some components in Alert
WRO-8207
=> WRO-8207: Add ss test cases for Alert

TransferList/TransferList.js, TransferList/TransferList.module.less, samples/sampler/stories/default/TransferList.js
Added drag animations to TransferList
WRO-10607
=> WRO-10607: Apply drag animation

TransferList/TransferList.js, samples/sampler/stories/default/TransferList.js
Applied 5-way transfer items option.
WRO-10609
=> WRO-10609:  Apply 5-way selection/ordering of items.

package.json
Need to update homepage information in the sandstone page of npmjs.com
Add 'homepage' and 'repository' field to package.json according to the guide of https://docs.npmjs.com/cli/v8/configuring-npm/package-json
WRO-11514
Enact-DCO-1.0-Signed-off-by: SJ RO ([sj.ro@lge.com](mailto:sj.ro@lge.com))
=> WRO-11514: Add Repository/Hompage address to @enact/sandstone at npmjs.com

tests/ui/specs/VideoPlayer/VideoPlayer-specs.js
- Need to add ui test cases for VideoPlayer.
- Add ui test cases for VideoPlayer.
WRO-11626, QWTC-2524
=> WRO-11626: Add ui test cases for VideoPlayer(QWTC-2524)

ProgressBar/tests/ProgressBar-specs.js
Increased code coverage for ProgressBar over 90%.
Added test cases for ProgressBar tooltip and managed to improve code coverage to 100%.
WRO-12041
Enact-DCO-1.0-Signed-off-by: Andrei Tirla [andrei.tirla@lgepartner.com](mailto:daniel.stoian@lgepartner.com)
=> WRO-12041: Increase code coverage for ProgressBar

package.json, samples/event-logger/package.json, samples/perf-scroller-native/package.json, samples/perf-scroller-translate/package.json, samples/perf-virtualgridlist-native/package.json, samples/perf-virtualgridlist-translate/package.json, samples/perf-virtuallist-native-with-different-item-size/package.json, samples/perf-virtuallist-native/package.json, samples/perf-virtuallist-translate/package.json, samples/qa-a11y/package.json, samples/qa-dropdown/package.json, samples/qa-fonts/package.json, samples/qa-i18n-async/package.json, samples/qa-i18n/package.json, samples/qa-scroller/package.json, samples/qa-videoplayer/package.json, samples/qa-virtualgridlist/package.json, samples/qa-virtualgridlistnative-preserve-focus/package.json, samples/qa-virtuallist/package.json, samples/qa-voice-control/package.json, samples/sampler/package.json
Isomorphic test fail due to ilib 14.15.0 released on Sep 2nd
Temporarily fixed ilib version to 14.14.0
WRO-11786
=> WRO-11786: Fix isomorphic test for sandstone

samples/sampler/stories/qa/Marquee.js
Sample text needed inside Marquee component.
Added text to Marquee.
WRO-10812
Enact-DCO-1.0-Signed-off-by: Andrei Tirla [andrei.tirla@lgepartner.com](mailto:daniel.stoian@lgepartner.com)
=> WRO-10812: Added bidirectional text for Marquee QA-sampler

Slider/tests/Slider-specs.js, Spinner/tests/Spinner-specs.js
Added missing tests for 
- Slider: drag and drop and for wheel events
- Spinner: default aria label
Util function for drag and drop was copied for the example on the testing library website: https://testing-library.com/docs/example-drag/
WRO-12043
=> WRO-12043: Increased code coverage for Slider and Spinner

Image/tests/Image-specs.js, ImageItem/tests/AsyncRenderChildren-specs.js, ImageItem/tests/ImageItem-specs.js
Added missing tests for Image, ImageItem and ImageItem/AsyncRenderChildren
Existing tests for Image do not increase code coverage. Testing library does not work well with window resizing, so we cannot test the resize event to cover the missing code lines
WRO-12042
=> WRO-12042: Increased codecov for Image and ImageItem

Popup/tests/Popup-specs.js, PopupTabLayout/tests/PopupTabLayout-specs.js
Code coverage for Popup and PopupTabLayout needs to be over 80%.
Increased code coverage to 80.88% for Popup and to 61.90% for PopupTabLayout.
WRO-12044
=> WRO-12044: Increase code coverage for Popup/PopupTabLayout

Alert/Alert.module.less, CHANGELOG.md, styles/colors-light.less, styles/colors.less
There are LESS variables that are unused and CSS variables that do not work in overlay type Alert.
- Removed unused LESS variables related to ProgressBar and Picker as they are not removed properly from past works.
- Added overridable CSS variables to work properly in overlay type Alert.
WRO-10673
=> WRO-10673: Refine dangled color variables

ContextualMenuDecorator/tests/ContextualMenuDecorator-specs.js, ContextualPopupDecorator/tests/ContextualPopupDecorator-specs.js, DatePicker/tests/DatePicker-specs.js, DayPicker/tests/DayPicker-specs.js, Picker/tests/Picker-specs.js, TimePicker/tests/TimePicker-specs.js, internal/Picker/tests/Picker-specs.js
Increase code coverage for:
ContextualPopup+ContextualMenuDecorator 
DatePicker+TimePicker+DayPicker+Picker+internal/Picker
WRO-12045
=> WRO-12045: Increase code coverage for ContextualPopup and Picker component families.

TabLayout/tests/TabGroup-specs.js, TabLayout/tests/TabLayout-specs.js, TooltipDecorator/tests/TooltipDecorator-specs.js
Increase code coverage for TabLayout/TooltipDecorator.
For the TabLayout/TabLayout.js I've only managed to increase coverage to 73.33%. Even though for the entire TabLayout folder the coverage is 84.05%, if the reviewers have any sugestions on how to do additional tests I would be grateful if they will share them in a comment below.
WRO-12375.
=> WRO-12375: Increase code coverage for TabLayout/TooltipDecorator

samples/sampler/.qa-storybook/main.js, samples/sampler/.storybook/main.js
Fixed legacy hierarchy separator storybook warning by adding `warnOnLegacyHierarchySeparator: false` in storybook configuration
WRO-13686
=> WRO-13686: sampler: Fix warning warnOnLegacyHierarchySeparator

TransferList/TransferList.js, samples/sampler/stories/default/TransferList.js
Changed the component to use VirtualList so it is more efficient.
WRO-14597
=> WRO-14597: Changed component to use VirtualList.

TransferList/TransferList.js
Added custom drag image - one when a single item is selected and dragged and one when multiple items are being dragged
WRO-14593
=> WRO-14593: TransferList POC -  Added custom drag image

TransferList/TransferList.js, TransferList/TransferList.module.less, samples/sampler/stories/default/TransferList.js
Added disabled prop and min-max capacity for transfer lists
WRO-14592
=> WRO-14592: [TransferList POC] - Disable items or Allow transfer functionality

TransferList/TransferList.js, samples/sampler/stories/default/TransferList.js
TransfterList POC - Fixes for multipleDrag and drag image after migration to VirtualList
WRO-14599
=> WRO-14599: TransferList POC - Fixes for multipleDrag and drag image after migration to VirtualList

TransferList/TransferList.js
At the moment, when dropping an item into the destination list, the scrollbar does not become visible.
1. When an item is moved via 5-way or by button click, the destination scrolls to the position of the dropped item.
2. When an item is moved by drag-and-drop, the destination list centers the dropped items and scrollbar is visible for a few moments.
WRP-4951
=> WRP-4951: Add velocity to show scrollbar after drag and drop

Alert/AlertImage.js
JSDoc for AlertImage proprtypes misses ".prototype" This leads to a different structure of the documentation
Added the missing string ".proptypes"
WRP-5054
=> WRP-5054: Fixed AlertImage jsdoc

tests/screenshot/apps/components/RangePicker.js, tests/ui/apps/RangePicker/RangePicker-View.js, tests/ui/specs/RangePicker/RangePicker-RTL-specs.js, tests/ui/specs/RangePicker/RangePicker-specs.js, tests/ui/specs/RangePicker/RangePickerPage.js
- Need to add ui tests for RangePicker.
- Add ui tests for RangePicker
WRP-5664
QWTC-2144
QWTC-2145
QWTC-2148
QWTC-2629
=> WRP-5664: Add UI test for Rangerpicker.

tests/screenshot/apps/components/Header.js, tests/screenshot/apps/components/Heading.js
- Need to add ss tests for Header.
- Need to add ss tests for Heading.
- Add ss tests for Header.
- Add ss tests for Heading.
WRP-6294
=> WRP-6294: Increase automated tests for Header/Heading.

samples/sampler/stories/qa/VirtualGridList.js
- Need to fix sample to display properly in RTL.
- Fix sample to display properly in RTL.
WRP-7232
=> WRP-7232: Fix VirtualGridList qa-sample.

samples/sampler/stories/qa/VirtualGridList.js
Reverts enactjs/sandstone#1395 as founding mistates
=> Revert "WRP-7232: Fix VirtualGridList qa-sample."

codecov.yml
Need to status check for blocking PR
Update codecov.yml file to apply status check of codecov
(https://docs.codecov.com/docs/commit-status)
For merge block, need to change github branches setting too.
(https://github.com/enactjs/sandstone/settings/branches)
WRP-3007
=> WRP-3007 : Apply Status checks  of codecov

CHANGELOG.md, IconItem/IconItem.js
`IconItem` component needs to be public.
Changed `IconItem` component to be public.
WRP-12063
=> WRP-12063: Changed `IconItem` component to be public

tests/ui/specs/TabLayout/VerticalTabsWithIcons/VerticalTabsWithIcons-specs.js, tests/ui/specs/VideoPlayer/VideoPlayer-specs.js
- Need to add delay for PopupTabLayout ui-test.
- Need to fix VideoPlayer ui-test.
- Add delay for TabLayout ui-test.
- Add step to focus on actionguide button(VideoPlayer).
WRP-14885
=> WRP-14885: Fix failed ui-test on jenkins

Button/tests/Button-specs.js, Checkbox/tests/Checkbox-specs.js, CheckboxItem/tests/CheckboxItem-specs.js, ContextualMenuDecorator/tests/ContextualMenuDecorator-specs.js, ContextualPopupDecorator/tests/ContextualPopupDecorator-specs.js, DatePicker/tests/DatePicker-specs.js, DayPicker/tests/DayPicker-specs.js, Dropdown/tests/Dropdown-specs.js, FlexiblePopupPanels/tests/FlexiblePopupPanels-specs.js, FormCheckboxItem/tests/FormCheckboxItem-specs.js, Input/tests/Input-specs.js, Input/tests/InputField-specs.js, Panels/tests/Panels-specs.js, Popup/tests/Popup-specs.js, PopupTabLayout/tests/PopupTabLayout-specs.js, RangePicker/tests/RangePicker-specs.js, Switch/tests/Switch-specs.js, SwitchItem/tests/SwitchItem-specs.js, TabLayout/TabLayout.js, TabLayout/tests/TabGroup-specs.js, TabLayout/tests/TabLayout-specs.js, TimePicker/tests/TimePicker-specs.js, VideoPlayer/tests/VideoPlayer-specs.js, WizardPanels/tests/WizardPanels-specs.js, internal/Picker/tests/Picker-specs.js
`@testing-library/user-event` version 14 introduced API changes so we need to update unit tests.
Updated tests that are using `@testing-library/user-event` module.
TBD
This PR should be merged after @enact/cli 6.0.0 is released, otherwise, Travis will be broken.
WRP-14328
=> WRP-14328: Update unit tests to work with `@testing-library/user-event` 14

README.md
Update README.md
Added Sandstone docs and sampler links
Attached Sandstone component screenshot
WRP-593
=> WRP-593: Update README.md 

TransferList/TransferList.js
Added helpful comments through the code
WRP-15613
=> WRP-15613: [TransferList POC] Add documentation

ColorPicker/ColorPicker.js, ColorPicker/ColorPicker.module.less, ColorPicker/package.json, samples/sampler/stories/default/ColorPicker.js
I added a ColorPicker component in sandstone, based on the agate one.
The reason I did not make the PR into develop is because we have no tests for this component. I did not add any tests for this component, because we have no specifications for it. When/if we will get them, I will add some unit/ui/screenshot tests.
WRP-17881
=> WRP-17881: Create a color picker component.

TransferList/ButtonList.js, TransferList/RenderItem.js, TransferList/TransferList.js, TransferList/utils.js
I moved some parts of the component to their own folder, in order to increase code readability and make the main file less bloated.
WRP-15626
=> WRP-15626: Refactor the component.

tests/ui/specs/PopupTabLayout/default-sampler/PopupTabLayout-QWTC-2523-specs.js
- Need to add delay for PopupTabLayout ui-test.
- Add delay for PopupTabLayout ui-test.
WRP-21653
=> WRP-21653: Fix ui test fail on jenkins(PopupTabLayout)

CHANGELOG.md, Scroller/EditableWrapper.js, samples/sampler/stories/qa/IconItem.js, samples/sampler/stories/qa/IconItem.module.less, samples/sampler/stories/qa/Scroller.js
This PR fixed 4 reported issues and few potential bugs
- Reported Issues
1) When pressing the left or right key in the leftmost/rightmost iconItem in the editable scroller, the buttons of iconItem remain shown -> fixed to disappear when the focus leaves (commit 59cb2fc)
2) IconItem can be selected even when disabled -> fixed to not select when it is disabled iconItem (9343926, 4d0bad0)
3) When pressing the down key in the iconItem in the editable scroller,  buttons disappear -> fixed not to disappear (91df15c)
4) While moving iconItem in the editable scroller, the focus effect needs to be fixed (91df15c, 7d1a7a6)
- Additional fixed issues (97c9b7c)
1) When the data size of editableScroller changed, centeredOffset …
=> WRP-21715: Fix `sandstone/EditableWrapper` to handle focus properly 

samples/sampler/stories/qa/IconItem.js
Sampler code needs to be updated for #1488.
Sampler code is updated.
WRP-24016
=> WRP-24016: Update sampler for EditableScroller

CHANGELOG.md, IconItem/IconItem.module.less, styles/colors.less
GUI is updated for `IconItem` when disabled.
Updated `IconItem` to match the latest design.
WRP-23104
=> WRP-23104: Update `IconItem` color when disabled

tests/screenshot/apps/components/Marquee.js, tests/screenshot/apps/components/Marquee.module.less
For https://github.com/enactjs/enact/pull/3171 PR, screenshot test need to be added
Add screenshot test of marquee case
WRP-24097
=> WRP-24097: Add screenshot test of `marquee`

tests/ui/specs/PopupTabLayout/PopupTabLayout-specs.js
Add popupTabLayout UI test to test https://github.com/enactjs/sandstone/pull/1500 changes
Update popupTabLayout UI test
WRP-29597
=> WRP-29597: Add PopupTabLayout UI test

package-lock.json, package.json, samples/event-logger/package.json, samples/qa-virtualgridlist/package.json, samples/qa-virtualgridlistnative-preserve-focus/package.json, samples/qa-virtuallist/package.json, samples/sampler/package.json
Updated dependencies' minor version.
Updated dependencies' minor version.
N/A
WRQ-415
=> WRQ-415: Update minor dependencies to fix vulnerabilities

tests/ui/specs/VirtualList/VirtualList-utils.js
- Need to add dealy for VirtualList ui-test.
- Add dealy for VirtualList ui-test.
WRQ-3746
=> WRQ-3746: Fix failed ui test on jenkins(VirtualList)

samples/qa-a11y/src/views/TabLayout.js
Fix qa-a11y sample tabLayout view to focus handle properly when entering tabLayout view
WRQ-1307
=> Update qa-a11y tablayout view

.travis.yml, Scroller/tests/EditableWrapper-specs.js
Unit Test of editalbe scroller needed to be added.
I added 2 tests for editable scroller.
- should have selected class and custom selected class when item is selected
- should not have selected class and custom selected class and should have custom focused class when item is unselected
WRQ-156
Enact-DCO-1.0-Signed-off-by: Jiye Kim ([jiye.kim@lge.com](mailto:jiye.kim@lge.com))
=> WRQ-156: [Codecov] Increase coverage for editable scroller

samples/event-logger/package.json, samples/qa-virtualgridlist/package.json, samples/qa-virtualgridlistnative-preserve-focus/package.json, samples/qa-virtuallist/package.json
Updates redux related modules' major version
Updates redux related modules' major version
- @reduxjs/toolkit    ^1.9.7  →    ^2.0.1
- react-redux         ^8.1.3  →    ^9.1.0
- redux               ^4.2.1  →    ^5.0.1
This release has breaking changes but they did not affect the sandstone code.
- [@reduxjs/toolkit](https://github.com/reduxjs/redux-toolkit/releases/tag/v2.0.0): (No changes related to sandstone code)
- …
=> WRQ-7044: Updates redux related modules' major version

tests/screenshot/apps/components/Button.js, tests/screenshot/apps/components/FixedPopupPanels.js, tests/screenshot/apps/components/FlexiblePopupPanels.js, tests/screenshot/apps/components/FormCheckboxItem.js, tests/screenshot/apps/components/Header.js, tests/screenshot/apps/components/RadioItem.js, tests/screenshot/apps/components/Slider.js, tests/screenshot/apps/components/SwitchItem.js, tests/screenshot/apps/components/VirtualGridList.js, tests/screenshot/apps/components/VirtualList.js, tests/ui/specs/Picker/Picker-specs.js, tests/ui/specs/Scroller/WithEditableSelectItemByLongPress/ScrollerWithEditableSelectItemByLongPress-specs.js, tests/ui/specs/Scroller/WithEditableSelectItemByPress/Scroller-QWTC-568-specs.js, tests/ui/specs/Scroller/WithEditableSelectItemByPress/Scroller-QWTC-569-specs.js, tests/ui/specs/Scroller/WithEditableSelectItemByPress/Scroller-QWTC-570-specs.js, tests/ui/specs/Scroller/WithEditableSelectItemByPress/ScrollerWithEditableSelectItemByPress-specs.js
Even though test cases were created ui or screenshot tests, some cases were not commented.
- Sync up ui/screenshot tests and test cases.
WRQ-8428
=> WRQ-8428: Sync up ui/screenshot tests and test cases.

tests/ui/specs/PopupTabLayout/PopupTabLayout-specs.js
- Need to fix failed ui-test(PopupTabLayout).
- Add delay for PopupTabLayout ui-test.
WRQ-10752
=> WRQ-10752: Fix failed ui test (PopupTabLayout)

package-lock.json, package.json
To fix the validate-docs error while Travis test, Update @enact/docs-utils version to 0.4.8.
Update @enact/docs-utils version to 0.4.8
=> Update @enact/docs-utils version to ^0.4.8 in package.json file

.travis.yml, Input/InputField.js, MediaPlayer/MediaSliderDecorator.js, Scroller/useThemeScroller.js, Slider/SliderBehaviorDecorator.js, ThemeDecorator/ThemeDecorator.js, VideoPlayer/VideoPlayer.js, internal/Picker/Picker.js, useScroll/useEvent.js, useScroll/useScroll.js
As [core/platform's API is updated](https://github.com/enactjs/enact/pull/3208/), internal codes need to be updated.
Updated affected API calls.
No changelog as only internal calls are updated.
WRQ-188
[enactjs/enact PR #3208](https://github.com/enactjs/enact/pull/3208/)
=> WRQ-188: Update internal calls to the updated core/platform APIs

CHANGELOG.md, VirtualList/useThemeVirtualList.js
When the focus moves to an item of a list toward on unscrollable direction, the list does not scroll properly in some cases so that the item is not fully visible.
Fixed the calculation bug for a scrolling distance.
WRQ-11772
=> WRQ-11772: Fixed `VirtualList` to show the focused item properly when focus moved toward on unscrollable direction

TransferList/ButtonList.js, TransferList/TransferList.js, TransferList/TransferList.module.less, samples/sampler/stories/default/TransferList.js
Applied UX scenario to TransferList sample
Added remove button, fixed Drop Border, and added the option of fixing the items from the first list
WRQ-8002
Enact-DCO-1.0-Signed-off-by: Ion Andrusciac ion.andrusciac@lgepartner.com
=> WRQ-8002: Applied UX scenario to TransferList sample

tests/screenshot/apps/components/Button.js, tests/screenshot/apps/components/CheckboxItem.js, tests/screenshot/apps/components/DatePicker.js, tests/screenshot/apps/components/DayPicker.js, tests/screenshot/apps/components/VirtualGridList.js, tests/ui/apps/Scroller/WithHorizontal/ScrollerWithHorizontal-View.js, tests/ui/specs/Scroller/WithHorizontal/Scroller-QWTC-1981-specs.js, tests/ui/specs/Scroller/WithHorizontal/Scroller-QWTC-1982-specs.js
- Need to add ui/screenshot tests.
- Add ui/screenshot tests
WRQ-11311
=> WRQ-11311: Increase ui and screenshot tests

Image/tests/Image-specs.js, ImageItem/ImageItem.js, tests/ui/apps/ImageItem/ImageItem-View.js, tests/ui/apps/Scroller/WithEditableSelectItemByLongPress/ScrollerWithEditableSelectItemByLongPress-View.js, tests/ui/apps/VirtualList/VirtualGridList/VirtualGridList-View.js
Fixed image placeholder URLs
Fixed image placeholder URLs
WRQ-12609
=> Fixed image placeholder URLs

TransferList/ButtonList.js, TransferList/CustomDragImage.js, TransferList/TransferList.js, TransferList/utils.js
Investigated performance of TransferList component
`ButtonsList` and `CustomDragImage` were wrapped in `React.memo` to avoid some unnecessary re-renders. Also, some code was refactored, wrapped in functions, and moved to the `utils` file.
WRQ-12616
Enact-DCO-1.0-Signed-off-by: Ion Andrusciac ion.andrusciac@lgepartner.com
=> WRQ-12616: Investigated performance of TransferList component

PageViews/PageViews.js
Fix isomorphic error in PageViews 
WRQ-14550
=> WRQ-14550: Fix isomorphic error in PageViews

package.json, samples/event-logger/package.json, samples/perf-scroller-native/package.json, samples/perf-scroller-translate/package.json, samples/perf-virtualgridlist-native/package.json, samples/perf-virtualgridlist-translate/package.json, samples/perf-virtuallist-native-with-different-item-size/package.json, samples/perf-virtuallist-native/package.json, samples/perf-virtuallist-translate/package.json, samples/qa-a11y/package.json, samples/qa-dropdown/package.json, samples/qa-fonts/package.json, samples/qa-i18n-async/package.json, samples/qa-i18n/package.json, samples/qa-scroller/package.json, samples/qa-tablayout/package.json, samples/qa-videoplayer/package.json, samples/qa-virtualgridlist-datasize-changing/package.json, samples/qa-virtualgridlist/package.json, samples/qa-virtualgridlistnative-preserve-focus/package.json, samples/qa-virtuallist/package.json, samples/qa-voice-control/package.json, samples/sampler/package.json
Fix TimePicker to apply locale properly in ta-IN locale
Fix ilib version to 14.19.0
=> Fix ilib version to 14.19.0

TransferList/ButtonList.js, TransferList/TransferList.js, TransferList/TransferList.module.less, TransferList/utils.js
Changed control button height
Added tooltips to control buttons
Added labels that show number of selected items from each list
Solved a bug that an item was not deselected after a move operation if it was present in the other list
Solved a bug that if you selected multiple elements to move from a list and if one of them was in the other list, the elements would not get deleted from the first list.
WRQ-15786 …
=> WRQ-15786: TransferList enhancements (control button height, tooltips)

tests/screenshot/apps/components/QuickGuidePanels.js
Fix screenshot test of quickguidepanels
Update import statement
WRQ-420
=> Fix Quick Guide Panels screenshot tests

CHANGELOG.md, IconItem/IconItem.module.less, ImageItem/ImageItem.module.less, Skinnable/Skinnable.js, ThemeDecorator/AccessibilityDecorator.js, samples/sampler/.qa-storybook/preview.js, samples/sampler/.storybook/preview.js, samples/sampler/src/ThemeEnvironment/ThemeEnvironment.js, samples/sampler/stories/qa/IconItem.module.less, samples/sampler/stories/qa/Spotlight.js, samples/sampler/stories/qa/Spotlight.module.less, styles/mixins.less, tests/screenshot/apps/Sandstone-View.js, tests/screenshot/apps/components/IconItem.js, tests/screenshot/apps/components/ImageItem.js
With updated GUI, IconItem and ImageItem can have focus ring in the focusHighlight mode
Add .sand-focus-highlight mixins
WRQ-14896
=> WRQ-14896: Add focus highlight mode 

tests/ui/specs/TabLayout/VerticalTabsWithIcons/VerticalTabsWithIcons-specs.js, tests/ui/specs/TabLayout/VerticalTabsWithoutIcons/VerticalTabsWithoutIcons-specs.js
- Need to delay for TabLayout ui-test.
- Add to delay for TabLayout ui-test.
WRQ-18301
=> WRQ-18301: Fix failed ui-test on jenkins(TabLayout)

samples/sampler/stories/qa/Marquee.js
Relates to https://github.com/enactjs/enact/pull/3247 PR, I added marquee qa samples to test 
changing contents of marquee which is used with marqueeController in this PR.
Add samples
WRQ-24303
=> WRQ-24303: Add marqueeController with content changed samples in marquee qa-sampler

.travis.yml
travis error occurs due to a lot of console warnings.
https://github.com/enactjs/sandstone/runs/27544617755 
we checked this error does not occur with cli master branch,
so we change cli branch in travis.yml file to master temporarily.
after fixing the problem, we should revert the branch.
WRQ-29884
=> WRQ-29884: Change cli branch in travis.yml to master

ColorPickerPOC/ColorPickerGrid.js, ColorPickerPOC/ColorPickerGrid.module.less, ColorPickerPOC/utils.js
[POC] Added Grid Color Picker
Optimized styling for grid color picker
WRQ-30516
Enact-DCO-1.0-Signed-off-by: Daniel Stoian ([daniel.stoian@lgepartner.com](mailto:daniel.stoian@lgepartner.com))
=> WRQ-30516: Optimized styling for grid color picker

ColorPickerPOC/ColorPickerPOC.js, ColorPickerPOC/ColorPickerPOC.module.less, ColorPickerPOC/ColorPickerSlider.js, ColorPickerPOC/ColorPickerSlider.module.less, ColorPickerPOC/utils.js, styles/colors.less
Added slider type panel for the WebOS ColorPicker. 
WRQ-30517
=> WRQ-30517: Slider type panel for the WebOS ColorPicker.

ColorPickerPOC/ColorPickerPOC.js, ColorPickerPOC/ColorPickerSpectrum.js, ColorPickerPOC/ColorPickerSpectrum.module.less, ColorPickerPOC/SpectrumIndicator.js, ColorPickerPOC/utils.js
Implement Spectrum Color Picker POC
WRQ-30519
=> WRQ-30519: [POC] webOS ColorPicker - spectrum color picker

ColorPickerPOC/ColorPickerSpectrum.js
Fixed spectrum color picker canvas size
WRQ-30519
=> WRQ-30519: Fixed spectrum color picker canvas size

ColorPickerPOC/ColorPickerPOC.js, ColorPickerPOC/ColorPickerSlider.js, ColorPickerPOC/ColorPickerSlider.module.less, ColorPickerPOC/utils.js
Changed the size of the knob for the slider and added a version of HSL for ColorPickerSlider.
WRQ-30517
=> WRQ-30517:  Create a slider type for webOS ColorPicker (part2)

PageViews/Page.js, PageViews/Page.module.less, PageViews/PageViews.js, PageViews/PageViews.module.less, QuickGuidePanels/QuickGuidePanels.js, QuickGuidePanels/QuickGuidePanels.module.less, samples/sampler/stories/default/PageViews.js
`PageViews` and `QuickGuidePanels` need to be cleaned up.
- Added proper spaces and comments
- Changed default arranger for PageViews to `BasicArranger`
- Sorted some props alphabetically
- Cleaned code
I've found some of API need to be public or modified.
I'll address them in the ticket in more detail.
This PR is made during the review of #1648 .
WRQ-22396
=> WRQ-22396: Miscellaneous fix for `PageViews` and `QuickGuidePanels`

CHANGELOG.md, PageViews/Page.js, PageViews/Page.module.less, PageViews/PageViews.js, PageViews/PageViews.module.less, QuickGuidePanels/QuickGuidePanels.js, QuickGuidePanels/QuickGuidePanels.module.less, Steps/Steps.js, Steps/Steps.module.less, samples/sampler/stories/default/PageViews.js, samples/sampler/stories/default/QuickGuidePanels.js, samples/sampler/stories/default/QuickGuidePanels.module.less, styles/colors.less, styles/variables.less
- QuickGuidePanels sampler needs to be more real world example.
- Steps used in QuickGuidePanels and PageViews need refactoring (Fix layout prop to have more appropriate values)
- Fix Steps used in QuickGuidePanels and PageViews accroding to the GUI guide.
- Update QuickGuidePanels sampler
- Fix Steps size prop to accept Number type as icon size prop
- Fix Steps layout prop
WRQ-22396
=> WRQ-22396: Refactoring Steps and update QuickGuidePanels sampler

ColorPickerPOC/ColorPickerSlider.js, ColorPickerPOC/ColorPickerSlider.module.less, ColorPickerPOC/utils.js
Changed the switch to a dropdown to chose between HSL or RGB format. Added an extra input for selecting a color in HEX value.
WRR-1870
=> WRR-1870: Adjust Slider ColorPicker based on feedback

package-lock.json, package.json, samples/event-logger/package.json, samples/perf-scroller-native/package.json, samples/perf-scroller-translate/package.json, samples/perf-virtualgridlist-native/package.json, samples/perf-virtualgridlist-translate/package.json, samples/perf-virtuallist-native-with-different-item-size/package.json, samples/perf-virtuallist-native/package.json, samples/perf-virtuallist-translate/package.json, samples/qa-a11y/package.json, samples/qa-dropdown/package.json, samples/qa-fonts/package.json, samples/qa-i18n-async/package.json, samples/qa-i18n/package.json, samples/qa-scroller/package.json, samples/qa-tablayout/package.json, samples/qa-videoplayer/package.json, samples/qa-virtualgridlist-datasize-changing/package.json, samples/qa-virtualgridlist/package.json, samples/qa-virtualgridlistnative-preserve-focus/package.json, samples/qa-virtuallist/package.json, samples/qa-voice-control/package.json, samples/sampler/package.json
Update dependencies' minor and patch version
Update dependencies' minor and patch version
WRR-1519
=> WRR-1519: Update dependencies' minor and patch version

.travis.yml
This is a PR that has been modified to receive cli from tarvis as version 6.0.x.
This may be useful when the next patch for version 6.0 of cli is released.
It is not directly related to WRR-976 implementation and was written only for node version changes.
Modified to receive 6.0.x version of cli
WRR-976
=> WRR-976: Modified travis config to use the latest CLI 6.0.x version

Dropdown/DropdownList.js
Convert DropdownList to functional component
WRR-10094
=> WRR-10094: Convert Dropdown/DropDownList to functional component

Calendar/Calendar.js, Calendar/Calendar.module.less, Calendar/utils.js, samples/sampler/stories/default/Calendar.js, styles/variables.less
We need to create the core structure for the new Calendar component, and add a monthly layout for the days.
Created basic layout for Calendar:
- added dropdown for year
- added dropdown for Month
- added next/previous buttons
- added sampler
WRR-17099
=> WRR-17099: Created monthly layout for Calendar component

ContextualPopupDecorator/ContextualPopupDecorator.js, ContextualPopupDecorator/tests/ContextualPopupDecorator-specs.js, internal/Picker/Picker.js, internal/Picker/SpottablePicker.js, samples/sampler/npm-shrinkwrap.json, samples/sampler/stories/default/QuickGuidePanels.js
Modified the react dependency of the feature/react19 branch to 19 or higher. Errors that occur afterward should be fixed.
For detailed information about the error, please refer to WRR-14717.
Changed the order of refs so they are not ignored, and changed to use div elements instead of Fragments.
WRR-16137
=> WRR-16137: Fix errors that occur after React version 19
